### PR TITLE
Square icon for cdemu-client.

### PR DESCRIPTION
**Pull request by W-Floyd**
iconified_cdemu-client

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
The shadows on the symbol itself need to be adjusted.

**Comment by W-Floyd** [comment]
Ah, yup, didn't notice those. They're only 0.5px offset, is that standard for internal shadows?
iconified_cdemu-client

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
No, there are 1/1px offsets for internal shadows as well. The .5px offsets were chosen where 1/1 caused too much of a 3D or height effect.

**Comment by W-Floyd** [comment]
Okay, that's what I figured. Still working out what rules to go by :)

**Pull request merged**
