### PR TITLE
[Square] Visual Studio Code

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Here's my first attempt ever to use Inkscape : 
vscode

I used the Square template on templates folder, and copied the symbol from the circle icon :)

### CODE REVIEW

**Comment by palob** [comment]
The shadow needs to be shifted 1px to the left for Square icons and the file should be saved as *Optimised SVG* from Inkscape (with the CSS to XML option unchecked).

Happy Inkscaping :)

**Comment by bilelmoussaoui** [comment]
Thanks! I have done that :)

**Review by palob — APPROVED** [review]
Thanks!

**Review by Foggalong — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
@Foggalong Before i remove this branch, as @palob mentioned it seems that all the icons i've pushed does not have a linear gradient see #3683. Anyway, i've used the square template as a start. If it's an issue, this and the square template should be both fixed see #3678

**Comment by palob** [comment]
Indeed, there's no gradient in here. I'll take care of the template.

**Comment by bilelmoussaoui** [comment]
Alright, i will fix this icon pretty soon with the rest of my PR's

**Pull request merged**
