### PR TITLE
Icons for 2064: Read Only Memories

### LINKED ISSUE #2653: Read Only Memories (Steam)
Wanting feedback on a proposal for a fullscreen icon for Read Only Memories.

SteamID: 330820

Original icon: 
unityplayer

Proposal:
steam_icon_330820
**SVG:** https://dl.dropboxusercontent.com/u/40932393/steam_icon_330820.svg

Notes: The game is about a sapient AI (the character on both the original icon and my proposal), trans-humanism and other cyberpunk themes. It has a very "early-90s Japanese adventure game" style, similar to games like Policenauts and Snatcher.
Having the icon be the main character's head seemed like a good idea, as he represents the game pretty well, has a round head and bright colors.

Note 2: If necessary, I could remove the symbol at the top of its head, if it doesn't fit in the guideline. It would make the character a bit less recognizable, but it would still work, imho.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28165258-read-only-memories-steam?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by maxtron95**
Fixes #2653

2064-read-only-memories-ci svg
2064-read-only-memories-sq svg

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
I'm not so much a fan of this design, I think this would be better suited to being on a symbol (probably just a centred circular head) rather than full baseplate as it is now.

**Comment by maxtron95** [comment]
@Foggalong I pushed these new icons:

2064-rom-ci
2064-rom-sq

**Comment by palob** [comment]
Could you please try symbol-on-symbol shadows?

**Review by palob — CHANGES_REQUESTED** [review]
Looks way better now, the shadow should reach the upper circle limit though, meaning you need to build the shadows using the original, non-intersected shapes you used for the face features.

**Review by Foggalong — COMMENTED** [review]
This looks so much better! Once @palob's changes are in there this is definitely mergeworthy :heart:

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
