### PR TITLE
Icons for Spine

### PR DESCRIPTION
**Pull request by sprocketc**
http://esotericsoftware.com/

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square|

### CODE REVIEW

**Comment by palob** [comment]
Why did you remove the symlink?

**Review by palob — CHANGES_REQUESTED** [review]
Thanks for your contribution. For the sake of sharpness it might help to fit the kidney things into boxes of integer pixel size.
bildschirmfoto vom 2018-12-31 09-41-06

**Review by palob — COMMENTED** [review]
The lowermost and uppermost are fine now, the ones inbetween need to be tweaked a bit.

**Review by palob — COMMENTED** [review]
Thanks, you tweaks did it. Can you please move symbol+shadow 1px to the left for both icons and 1px up for Square? Looks a bit off-centre right now.

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
Could you reduce the saturation of the red ever so slightly? It's a bit too bright as is

**Review by Foggalong — CHANGES_REQUESTED** [review]
Just noticed a shadow error with Square; the shadow for Square is just 1px under the symbol, rather than 1px right 1px down as with Circle.

**Comment by sprocketc** [comment]
Are you sure? The position of the symbol should be x:18 y :12 and the shadow x:19 y:11

**Comment by palob** [comment]
Huh, Square shadow ought to be jut 1px down :)

**Comment by Foggalong** [comment]
If that's a change you've made it's not one you've pushed. The icons you've pushed have Circle's symbol at (18,11) with (19,10) shadow and Square's symbol at (18,12) with (19,11) shadow. Square's shadow should be at (18,11) instead, directly below the symbol rather than down and right.

**Comment by sprocketc** [comment]
My bad. I thought the shadow guidelines for circle and square icons were the same.
Should be fixed now.

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
