### PR TITLE
Square calendar icons.

### PR DESCRIPTION
**Pull request by W-Floyd**
Day | Blue | Purple | Red
--- | --- | --- | ---
| 1 | iconified_calendar-blue-01 | iconified_calendar-purple-01 | iconified_calendar-red-01 
| 2 | iconified_calendar-blue-02 | iconified_calendar-purple-02 | iconified_calendar-red-02 
| 3 | iconified_calendar-blue-03 | iconified_calendar-purple-03 | iconified_calendar-red-03 
| 4 | iconified_calendar-blue-04 | iconified_calendar-purple-04 | iconified_calendar-red-04 
| 5 | iconified_calendar-blue-05 | iconified_calendar-purple-05 | iconified_calendar-red-05 
| 6 | iconified_calendar-blue-06 | iconified_calendar-purple-06 | iconified_calendar-red-06 
| 7 | iconified_calendar-blue-07 | iconified_calendar-purple-07 | iconified_calendar-red-07 
| 8 | iconified_calendar-blue-08 | iconified_calendar-purple-08 | iconified_calendar-red-08 
| 9 | iconified_calendar-blue-09 | iconified_calendar-purple-09 | iconified_calendar-red-09 
| 10 | iconified_calendar-blue-10 | iconified_calendar-purple-10 | iconified_calendar-red-10 
| 11 | iconified_calendar-blue-11 | iconified_calendar-purple-11 | iconified_calendar-red-11 
| 12 | iconified_calendar-blue-12 | iconified_calendar-purple-12 | iconified_calendar-red-12 
| 13 | iconified_calendar-blue-13 | iconified_calendar-purple-13 | iconified_calendar-red-13 
| 14 | iconified_calendar-blue-14 | iconified_calendar-purple-14 | iconified_calendar-red-14 
| 15 | iconified_calendar-blue-15 | iconified_calendar-purple-15 | iconified_calendar-red-15 
| 16 | iconified_calendar-blue-16 | iconified_calendar-purple-16 | iconified_calendar-red-16 
| 17 | iconified_calendar-blue-17 | iconified_calendar-purple-17 | iconified_calendar-red-17 
| 18 | iconified_calendar-blue-18 | iconified_calendar-purple-18 | iconified_calendar-red-18 
| 19 | iconified_calendar-blue-19 | iconified_calendar-purple-19 | iconified_calendar-red-19 
| 20 | iconified_calendar-blue-20 | iconified_calendar-purple-20 | iconified_calendar-red-20 
| 21 | iconified_calendar-blue-21 | iconified_calendar-purple-21 | iconified_calendar-red-21 
| 22 | iconified_calendar-blue-22 | iconified_calendar-purple-22 | iconified_calendar-red-22 
| 23 | iconified_calendar-blue-23 | iconified_calendar-purple-23 | iconified_calendar-red-23 
| 24 | iconified_calendar-blue-24 | iconified_calendar-purple-24 | iconified_calendar-red-24 
| 25 | iconified_calendar-blue-25 | iconified_calendar-purple-25 | iconified_calendar-red-25 
| 26 | iconified_calendar-blue-26 | iconified_calendar-purple-26 | iconified_calendar-red-26 
| 27 | iconified_calendar-blue-27 | iconified_calendar-purple-27 | iconified_calendar-red-27 
| 28 | iconified_calendar-blue-28 | iconified_calendar-purple-28 | iconified_calendar-red-28 
| 29 | iconified_calendar-blue-29 | iconified_calendar-purple-29 | iconified_calendar-red-29 
| 30 | iconified_calendar-blue-30 | iconified_calendar-purple-30 | iconified_calendar-red-30 
| 31 | iconified_calendar-blue-31 | iconified_calendar-purple-31 | iconified_calendar-red-31

### CODE REVIEW

**Comment by palob** [comment]
The original Square ``office-calendar.svg`` uses clipping which we need to get rid off.
As far as I can see yours don't so it's good to go :+1: 

We need the icons as Optimised SVGs though.

**Comment by W-Floyd** [comment]
Hmm... I thought they were all optimized. Are there any that aren't?

**Comment by palob** [comment]
Ah OK, they are sort of. It's just the metadata at the beginning.

**Comment by W-Floyd** [comment]
Hmm. I see what you mean. So far as I know, it's just the default Inkscape setting, minus the option you told me to keep off. Any ideas? I'm happy to fix it, just not sure how.

**Comment by palob** [comment]
This is the settings I use:
inkscape

**Comment by W-Floyd** [comment]
Same. What about the other tabs?

**Comment by palob** [comment]
inkscape2

inkscape3

**Comment by W-Floyd** [comment]
Ah ha, the second tab was what was different. Got mine set correctly now,
I'll go back through any of my PRs when I get a chance to clean up.

**Comment by W-Floyd** [comment]
Okay, I *think* that's done right now?

**Review by palob — APPROVED** [review]

**Comment by W-Floyd** [comment]
I've gone ahead and added the rest of the colours. I just did a search and replace, it seems to be fine. Hope it's okay.

**Comment by bilelmoussaoui** [comment]
@W-Floyd Thanks for your work on this! :tada:

**Comment by W-Floyd** [comment]
Heh, no problem! Glad I can get the boring stuff out of your way :)

**Comment by Foggalong** [comment]
I've added the optimised SVG settings [to the wiki](https://github.com/numixproject/numix-core/wiki/Optimise-Options) so that I don't have to keep coming back here whenever I forget which to tick :+1:

**Comment by W-Floyd** [comment]
Oh good, I'd been meaning to look into that.

**Pull request merged**
