### PR TITLE
Add icon for Moon Hunters

### LINKED ISSUE #5427: Icon for Moon Hunters
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Moon Hunters`| `steam_icon_320040` | `Moon Hunters.desktop` | steam_icon_320040* |

Description: `Coop mythology storytelling game`

Website: http://www.moonhuntersgame.com/

*: The game only installs this 32x32 icon

### PR DESCRIPTION
**Pull request by mrmeszaros**
Fixes #5427

| Banner | Circle icon | Square icon |
| --- | --- | --- |
| moon-hunters base | moon-hunters circle 384 | moon-hunters square 384 |

Colors seem a bit too bright, currently working on darker shades.
Also, am not fully satisfied with the hair - looking into alternate lining + maybe including that circle hair ornament.

### CODE REVIEW

**Comment by palob** [comment]
Indeed, symbol-baseplate contrast is a bit harsh. Contrast inside the icon seems a bit low. Is there a way to set the different elements better apart colour-wise?
Arms and folded hands could get on-symbol shadows.

**Comment by mrmeszaros** [comment]
A | B | C
-- | -- | --
moon-hunters circle 384 a | moon-hunters circle 384 b | moon-hunters circle 384 c

Okay, so here is a **B** option (**A** is current) - went overall darker, smaller L differences between blues, + de-saturation. Still needs further color correction.

**C** has additionally that hair pin I mentioned - not sure on that. But, I have another design in mind I'll try.

When doing on-symbol shadows - do I do them in a separate path?

**Comment by palob** [comment]
Yes, separate path. First duplicate and merge the paths which should cast a shadow, move them.
Then duplicate the path(s) (and merge) the shadow is cast on and intersect with the resulting path from step 1.

Inner-symbol contrast is still a bit low even in draft C, especially brightness-wise. Shadows will also aid in making the different parts stand out more from one another.

**Comment by mrmeszaros** [comment]
A | B | C | D
-- | -- | -- | --
moon-hunters circle 384 a | moon-hunters circle 384 b | moon-hunters circle 384 c | moon-hunters circle 384 d

C has the darkened tweaked colors. D has some lighter baseplate (trying out stuff).
I'm not yet satisfied with the the body / skin tones.

**Comment by palob** [comment]
Out of those I like D the best.

**Review by palob — COMMENTED** [review]
Could we also get the arms cast shadows over the "crescent"?
shadow

Does it make any sense to deform the right(left) arm to something like this for better alignment?
right arm

**Comment by mrmeszaros** [comment]
Well, first I was skeptical (liked the forearm muscles 😅), but a rework like this looks pretty decent IMHO:

moon-hunters-handnbody-rework

Here are some renders:
Current | Elbow-shadow | Lifted right hand
-- | -- | --
moon-hunters circle 192 a | moon-hunters circle 192 m | moon-hunters circle 192 n

**Comment by palob** [comment]
If this doesn't make the arm look too deformed or the elbow too pointy (from the preview it looks a bit like that) let's go with the right one, otherwise the centre one.

**Comment by mrmeszaros** [comment]
Okay, I feel I am getting close to the end here. I tweaked the hair for better shapes / alignment, and added the hair ornament. Here's version F and E:

moon-hunters-hair-e

moon-hunter-hair-f

E | F
-- | --
moon-hunters circle 384 e | moon-hunters circle 384 f
moon-hunters circle 96 e | moon-hunters circle 96 f
moon-hunters circle 48 e | moon-hunters circle 48 f

I'm a bit undecided - maybe like E more.

Also, tried an adjusted bottom body hue. I kinda like it - what do You think?
moon-hunters circle 384 e moon-hunters circle 384 g

**Review by palob — APPROVED** [review]

**Comment by mrmeszaros** [comment]
@palob I'm sorry - I forgot to commit the drop-shadow fix and some other misc.
What is the path of action in such a case?
New PR? or should I push to the same branch?

Sorry, for the extra hassle - I know it's been a heck, and thanks in advance!

**Comment by palob** [comment]
Both is possible, new PR is the easiest I think. Thanks for the correction and sorry for not spotting the outdated shadow.
The hassle which comes with contributions is always welcome.

**Pull request merged**
