### PR TITLE
Icons for Icon Preview apps

### PR DESCRIPTION
**Pull request by palob**
Icon for the following apps
https://gitlab.gnome.org/World/design/app-icon-preview
https://developer.gnome.org/gtk3/stable/gtk3-icon-browser.html
https://github.com/danrabbit/lookbook
https://invent.kde.org/kde/ikona
https://github.com/santileortiz/Iconoscope

Unlinking from ``numix``, new icon:

icon-preview
icon-preview-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I love this design, but can I be picky and ask that we _not_ put a folder icon on there (unless you've already sorted Numix Folders support). Maybe a terminal or settings icon would be suitably generic?

**Comment by palob** [comment]
Alright, I'll have a look for another one, maybe not the terminal one for it hasn't got a coloured baseplate.

**Comment by palob** [comment]
A few alternatives, terminal works with altered (non-neutral) background.

icon-preview2
icon-preview3
icon-preview4

**Review by Foggalong — CHANGES_REQUESTED** [review]
Let's go with the settings app, I think that works quite well and still incorporates some colour!

**Comment by palob** [comment]
Pushed.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
