### PR TITLE
update Spotify square icon

### LINKED ISSUE #3915: Icon for Spotify is wrong color in Square
Spotify's icon is not "Spotify Green" (#1ED760) in Square.

Spotify in Circle

Spotify in Square

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Update Spotify Square icon
closes #3915

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
The shadow in Square is also wrong, needs to be under rather than down and right.

**Comment by bilelmoussaoui** [comment]
I have fixed that 👍

**Comment by bilelmoussaoui** [comment]
I still feel like the symbol could be -1px to the left, what do you think?

**Comment by Foggalong** [comment]
It looks alright to me: what would a 1px left shift look like?

**Comment by bilelmoussaoui** [comment]
-1px to the left
spotify-client-1
The current icon
spotify-client

**Comment by palob** [comment]
It's hard to spot any difference, I really don't know.

**Comment by Foggalong** [comment]
Stick with it as is. I can see what you're talking about but if I think about it too much the change then looks to far to the left. I think it's just a side effect of the arc design. Good to merge?

**Comment by bilelmoussaoui** [comment]
I think it's ready to merge, unless @palob has something else to say

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
