### PR TITLE
Added winbox icons

### LINKED ISSUE #5740: Icon Request: winbox
| Winbox | winbox | winbox.desktop | Original icon |
| --- | :-- | :-- | :-- |
| `APPLICATION NAME`| `ICON NAME` | `DESKTOP FILE NAME` | winbox64 |

Description: `Mikrotik RouterOS GUI Configurator. `

Website: `https://mikrotik.com/software`

------
Already found good svg variant from their site:

https://i.mt.lv/img/mt/v2/d_reseller.svg

-------
Also,
I love your square variant of numix icons, so already made square one ico (_based on teamviewer.svg)_ :

[winbox-numix-test.svg.zip](https://github.com/numixproject/numix-core/files/6759757/winbox-numix-test.svg.zip)

btw still need some color balance fixes i think.

Thank you.

### PR DESCRIPTION
**Pull request by cuzrawr**
Fixes #5740

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| winbox64 | circlenumixwinbox | squarenumixwinbox |

That app running under wine and need some hardcore fixes, cause most   **.desktop** files are have
```
...
Icon=/usr/share/pixmaps/winbox64.png
StartupWMClass=winbox64.exe
...
```

or just:
```
...
Icon=/usr/share/pixmaps/winbox.png
StartupWMClass=winbox.exe
...
```
Also, replacing ` /usr/share/pixmaps/winbox.png` works. My dockbar app called "plank" shows new icon properly (here how it looks like):
dockWorks111222

 But xfce4-panel looks like this  (_tried many different combinations with png\svg replacement but seems wine didn't eat ico properly and shows hardcoded into .exe_):
buggedOne233344

btw that are not big problem at all, because in my dock now everything is in harmony with square icons. :-)

### CODE REVIEW

**Review by cuzrawr — COMMENTED** [review]
tittle mistype

**Comment by ramonGonzEdu** [comment]
How come the circle icon seems to have a smaller "greener" circle inside? shouldn't it be all 1 color?

**Review by palob — CHANGES_REQUESTED** [review]
Hi, thank you for your contribution. 
Your icons contain encapsulated raster graphics. This defies the purpose of vector (SVG) icons, the icons won't scale up this way.
What is more, when I open the files in Inkscape I just see white circle on top of the baseplate.

**Comment by ingria** [comment]
Something like this maybe?

| 64 | 32 | 16 |
| --- | --- | --- |
|  |   |   |

The shadow looks to thick IMO

  <details>
    <summary>source svg</summary>

winbox_compressed

  </details>

**Comment by palob** [comment]
From distance the symbol looks a bit big. It should fit inside a 30px X 30px circle (like the one in the [template files](https://github.com/numixproject/numix-core/blob/master/templates/circle/48.svg)).

The crescent shapes should be composed by means of a path difference of 2 circles and need to be aligned to the pixel grid.
Can you open a new PR?

**Comment by palob** [comment]
Closing in favour of #5777.

**Pull request closed without merging**
