### PR TITLE
Beaker browser Flatpak symlink

### PR DESCRIPTION
**Pull request by palob**

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
There's some funky spacing going on

**Comment by palob** [comment]
Yeah but as soon as I start editing it's gone. Will try locally.

**Comment by palob** [comment]
Now it's correct locally in gedit but even funkier on GitHub.

**Comment by Foggalong** [comment]
It's still broken. Problem is tabs instead of spaces on that line

2018-06-29-232247_479x238_scrot

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
