### PR TITLE
Icons for 7 Days to Die

### LINKED ISSUE #3875: Icon for 7 Days to Die (Steam)
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `7 Days to Die`| `steam_icon_251570` | `7 Days to Die.desktop` | unityplayer |

Description: `7 Days to Die is an open-world first person shooter, survival horror, tower defense, and role-playing game.`

Website: http://7daystodie.com/?home and http://store.steampowered.com/app/251570/7_Days_to_Die/

### PR DESCRIPTION
**Pull request by maxtron95**
Fixes #3875

7dtd-ci
7dtd-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Could you please find a way to reduce symbol height? This one really looks too tall.

**Comment by maxtron95** [comment]
@palob What size should I reduce the symbol to?

**Comment by palob** [comment]
28px or 26px.

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
Symbol needs moving doing at least 1px on both circle and square to make it look centred (triangle illusion)

**Comment by maxtron95** [comment]
Should I move the symbol up?

**Comment by palob** [comment]
Down I'm pretty sure. @Foggalong Did you refer to the latest pushed icons or the previews above?

**Comment by Foggalong** [comment]
@creepertron95 @palob Yeah that was the latest pushed icons, and definitely down rather than up

**Comment by palob** [comment]
I think the Circle icon looked better before.

**Review by Foggalong — APPROVED** [review]
You're right @palob that it does look a bit odd in isolation, but when it's alongside all the other Circle icons it looks much more centred now.

**Pull request merged**
