### PR TITLE
Add icons for Cyberpunk 2077

### PR DESCRIPTION
**Pull request by BlueManCZ**
| Original icon | Circle icon | Square icon |
| --- | --- | --- |
|  | ![circ][circ] | ![sqr][sqr] |

https://steamdb.info/app/1091500/screenshots/
https://www.cyberpunk.net/

[circ]: https://user-images.githubusercontent.com/17854950/213863059-11b52cc0-9a13-4993-a8c2-d2ac026d7967.png "Circle"
[sqr]: https://user-images.githubusercontent.com/17854950/213863058-f822d15a-fb88-476e-aba5-f6a50936de63.png "Square"

Since Cyberpunk 2077 doesn't have any simple shapes or icons in its logo or graphics, I used my Observer icon (#5443) and recolored it to Cyberpunk colors.

### CODE REVIEW

**Comment by palob** [comment]
What about mirroring the symbol horizontally or removing the "biological" eye to set this apart from the observer icon a bit more? Does this make any sense?

**Comment by BlueManCZ** [comment]
I don't know, mirroring the symbol doesn't feel right, because you look at it the same way you read the text. From left to right - human face -> robotic face - humans becoming machines, the cyberpunk concept (Observer is a cyberpunk game as well). And removing the biological eye also feels and looks wrong. It's very important for the balance of the whole icon.

**Comment by palob** [comment]
Moving the cyborg eye to the centre more akin to the screenshot would be quite the hassle I take it?

**Comment by BlueManCZ** [comment]
Not sure if it would be recognizable anymore - that it is actually a human being. It's probably not worth the time. I wouldn't worry about the similarity with the Observer icon. It's a game with a current daily peak of 10 players.

**Review by palob — APPROVED** [review]
Aye, merging it. And thanks for dropping by again!

**Pull request merged**
