### PR TITLE
Icons for Cytus II (Android)

### PR DESCRIPTION
**Pull request by maxtron95**
https://play.google.com/store/apps/details?id=com.rayark.cytus2
cytus-2

cytus-2-ci
cytus-2-sq

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Did you try pupils or eyebrows? Right now it looks markedly creepier than the original icon.

**Comment by maxtron95** [comment]
Will see if I can try pupils and (or) eyebrows later. I thought something was off when I was creating this icon.

**Comment by maxtron95** [comment]
@palob What do you think of this? I tried adding pupils and eyebrows onto the initial icon. If it looks good, I will go push the new icon onto the branch.

cytus-2-mod

**Comment by palob** [comment]
Yeah, that's definitely better.

**Review by Foggalong — APPROVED** [review]

**Review by palob — APPROVED** [review]

**Pull request merged**
