### PR TITLE
Instagram redesign + symlink for Ramme

### LINKED ISSUE #3604: Icon Request - Ramme
Icon for [Ramme](https://github.com/terkelg/ramme).

```
[Desktop Entry]
Name=Ramme
Comment=Unofficial Instagram Desktop App
Exec="/opt/Ramme/ramme"
Terminal=false
Type=Application
Icon=ramme
```

### PR DESCRIPTION
**Pull request by palob**
Fixes #3604

insta-ci
insta-sq

### CODE REVIEW

**Comment by Foggalong** [comment]
Would this work if it used a pink baseplate still? It feels weird having a white baseplate when the original icon is so colourful.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Would this work if it used a pink baseplate still? It feels weird having a white baseplate when the original icon is so colourful.

**Comment by palob** [comment]
insta-ci
insta-sq

**Review by Foggalong — CHANGES_REQUESTED** [review]
This actually feels more wrong unfortunately. If you don't have any ideas (I know I don't) we'll go with the white baseplate for just being the least bad option.

(Not a slight on your icons, just the unfortunate incompatibility)

**Comment by palob** [comment]
Rolled back to white.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
