### PR TITLE
Icons for Clustertruck

### PR DESCRIPTION
**Pull request by maxtron95**
For #4854

ctruck

clustertruck-ci
clustertruck-sq

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
How would this one look without the outlines around each shape? We don't usually do too many outlines and I have a feeling this would work without them (though I might be wrong, in which case I'd approve this design)

**Comment by maxtron95** [comment]
@palob @Foggalong Something like this?

clustertruck-new svg

**Comment by palob** [comment]
Yes :+1: Plus maybe an on-symbol shadow for the front cabin.

**Comment by palob** [comment]
@creepertron95 Do you happen to have the latest draft somewhere on your disk?

**Pull request merged**
