### PR TITLE
Icons for Cadence apps

### PR DESCRIPTION
**Pull request by palob**
https://github.com/falkTX/Cadence

Cadence
cadence
cadence-ci
cadence-sq

Catarina
catarina
catarina-ci
catarina-sq

Catia
catia
catia-ci
catia-sq

Claudia
claudia
claudia-ci
claudia-sq

Claudia Launcher
claudia-launcher
claudia-launcher-ci
claudia-launcher-sq

### CODE REVIEW

**Comment by maxtron95** [comment]
@palob This could partially resolve #3659

**Comment by palob** [comment]
Indeed. It will **fully** resolve it as we already have got icons for carla. Thanks for the hint.

**Comment by palob** [comment]
Does anybody think this is a better combination of colours?

catia-alt

**Review by Foggalong — CHANGES_REQUESTED** [review]
@palob Yeah looks much nicer to me!

**Comment by palob** [comment]
Applied to all 10 :+1:

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
