### PR TITLE
Updated Mailspring design

### PR DESCRIPTION
**Pull request by BlueManCZ**
| [Original icon](https://github.com/Foundry376/Mailspring/blob/master/app/static/images/mailspring.png) | Circle icon | Square icon |
| --- | --- | --- |
| ![orig][orig] | ![circ][circ] | ![sqr][sqr] |

https://github.com/Foundry376/Mailspring

[orig]: https://user-images.githubusercontent.com/17854950/86519483-6e3c1280-be3b-11ea-83ad-e8041e478469.png "Original"
[circ]: https://user-images.githubusercontent.com/17854950/86519466-3a60ed00-be3b-11ea-9872-a5b943c85365.png "Circle"
[sqr]: https://user-images.githubusercontent.com/17854950/86519468-3df47400-be3b-11ea-8749-ba5b86a913ae.png "Square"

### CODE REVIEW

**Comment by palob** [comment]
In #3984 we opted against this type of design and went with the generic design. @reassessment or no?

**Comment by BlueManCZ** [comment]
We can also try something new, like this.

mailspring

**Comment by palob** [comment]
Oh yeah, that's lovely.

**Review by Foggalong — COMMENTED** [review]
Agreed, I'd be happy with that design!

**Review by palob — APPROVED** [review]

**Pull request merged**
