### PR TITLE
Icons for IPFS Desktop

### PR DESCRIPTION
**Pull request by palob**
https://github.com/ipfs-shipyard/ipfs-desktop

ipfs-desktop
ipfs-desktop-ci
ipfs-desktop-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I like this, but it looks like the cube should be solid with faces rather than hollow. I think use the current baseplate colour for the faces (as in the original) and maybe a light turquoise-grey for the baseplate?

**Comment by palob** [comment]
Like this?
ipfs-2

**Comment by Foggalong** [comment]
@palob Aye but with a much lighter background

**Comment by palob** [comment]
Next try
ipfs2

**Comment by Foggalong** [comment]
That's not what I was envisioning but it actually looks better! Good to go :+1:

**Comment by palob** [comment]
Pushed.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
