### PR TITLE
 compton - Icons and entry for Compton.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #2639

iconified_compton

### CODE REVIEW

**Comment by palob** [comment]
Maybe a slightly darker cog for better contrast?

**Comment by W-Floyd** [comment]
I think you're right.

iconified_compton

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
@W-Floyd can you please mention the issue number on the commit message next time? Github uses it to auto close the issues once the commit is merged

**Comment by W-Floyd** [comment]
Sure, I'll do that from now on :+1:

**Comment by Foggalong** [comment]
@bil-elmoussaoui @W-Floyd You don't even need to do it in the commit message, it can just be in the pull request body. Instead of "For #2639" put "Fixes #2639" and it'll automatically detect it.

**Comment by W-Floyd** [comment]
I noticed, I think that'll be easiest for me :P

**Pull request merged**
