### PR TITLE
add PR & issues template

### LINKED ISSUE #2861: Issue and Pull Request Template
I'm not sure if this is the best way to communicate this but take a look:
https://github.com/blog/2111-issue-and-pull-request-templates

This can make developing workflow a bit better. :smile: 

@Foggalong @palob 

Edit: Even better -> https://help.github.com/articles/helping-people-contribute-to-your-project/

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Fixes #2861 

Issue template : 

| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `APPLICATION NAME`| `ICON NAME` | `DESKTOP FILE NAME` | Original icon|

PR template : 

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| Original icon| Original icon | Original icon|

### CODE REVIEW

**Comment by palob** [comment]
For icon requests I think a link to the project page / application description is helpful.

**Comment by bilelmoussaoui** [comment]
I agree with that. But what do you think is better? add two more rows on the table or just add 
```
Description :

Website : 
```
At the end of the Issue template?

**Comment by palob** [comment]
New lines at the end so as not to look squeezy.

**Comment by bilelmoussaoui** [comment]
@palob Done

**Review by Foggalong — CHANGES_REQUESTED** [review]
For the in issue and pull request template can you use [this as the original icon](https://upload.wikimedia.org/wikipedia/commons/d/d5/Numix_Logo.png) and then upload the actual Circle & Square icons for those two slots (they're in the repo for BFB launchers).

**Comment by bilelmoussaoui** [comment]
@Foggalong Done, I've updated the issue content with the new icons :+1:

**Comment by Foggalong** [comment]
@bil-elmoussaoui Make [this](https://upload.wikimedia.org/wikipedia/commons/d/d5/Numix_Logo.png) the original icon so it's clear it's a different thing :)

**Comment by bilelmoussaoui** [comment]
Don't know why i changed the original one too, but it's ready now ;)

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
