### PR TITLE
kverbos - Icons and entry for kverbos.

### PR DESCRIPTION
**Pull request by W-Floyd**
#2294

`kverbos` has not been updated, as far as I can tell, in [9 years](https://kverbos.en.uptodown.com/ubuntu). Only reason I did this was because it's so simple, and that I would be interested in seeing more flags have icons (if it would be useful).

iconified_kverbos

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
Can you add a drop shadow under the top red segment so it looks as if the yellow is slightly inset?

**Comment by W-Floyd** [comment]
Oh come off it Travis...

iconified_kverbos

**Comment by bilelmoussaoui** [comment]
@W-Floyd It seems that a PR broke the data.json file :(

**Review by Foggalong — APPROVED** [review]

**Comment by palob** [comment]
The yellow band isn't correctly aligned but I can't fix it right now.

**Comment by W-Floyd** [comment]
This should be my fix :/

Edit: Nevermind, I see it's been done already :laughing:

**Pull request merged**
