### PR TITLE
Nuntius

### LINKED ISSUE #2522: Icon for Nuntius
https://github.com/holylobster/nuntius-linux

Name=Nuntius
Icon=nuntius

hicolor_apps_512x512_nuntius
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26379761-icon-for-nuntius?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by W-Floyd**
Resolves #2522

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

Not as... *ahem*... **striking** as the original, but it does indicate the purpose of the program.

### CODE REVIEW

**Comment by Foggalong** [comment]
@wa4557 Am I right in remembering that can't accept any commits which are signed with a verified signature?

**Comment by bilelmoussaoui** [comment]
@Foggalong Yep, they cause an issue with the PPA (launchpad..)

**Comment by W-Floyd** [comment]
lol Wow, ummm... What now?

**Comment by palob** [comment]
Is there a way to have the red-white edge in line with the grid?

red-white

Just like in ``blueman-device.svg``.

**Comment by W-Floyd** [comment]
Hmm... that *could* happen, but it would require changing other things. I'm struggling to find a solution that fits within the notification bubble.
image

So, we could:
* attempt to draw a new bluetooth logo that fits in the bubble and sits on lines correctly
* use the current logo
* make a larger notification bubble to accommodate one of the existing, larger logos

I'd prefer the first option personally.

**Comment by palob** [comment]
Thanks, feel free to have a bash at option 1.

**Comment by W-Floyd** [comment]
I found some official bluetooth branding literature, and this is pretty much a trace of it.

image
image

Personally, I don't much like the official one (too skinny), but it does seem to align better in this instance.

**Comment by palob** [comment]
Yeah, that's probably too flimsy to be recognisable at smaller sizes.

**Comment by W-Floyd** [comment]
I'll keep fiddling then :)

**Comment by palob** [comment]
Delighted too see a new enthusiastic contributor :)

**Comment by W-Floyd** [comment]
Enthusiastic != Talented, but I'm giving it a go :D

**Comment by W-Floyd** [comment]
image

Now it's too fat :P

**Comment by W-Floyd** [comment]
My conclusion thus far is that it isn't really possible for the bluetooth logo to be constructed in this space using stroked lines alone. That is, they must be disjointed (as previous icons have been).

**Comment by W-Floyd** [comment]
This doesn't seem too bad.

image
image

**Comment by palob** [comment]
I don't think the fat ones are all that bad. How do they scale down?

**Comment by W-Floyd** [comment]
As for scaling, the fat ones weren't *too* bad. The second one is best IMO.

**Comment by W-Floyd** [comment]
Okay, I finally worked out how to tell git *not* to sign my commits.

**Comment by palob** [comment]
Can you please "resave" those again for full optimisation?

**Comment by W-Floyd** [comment]
Ah, yup, forgot about this PR :P

**Comment by W-Floyd** [comment]
For clarity's sake...
iconified_nuntius

**Review by palob — APPROVED** [review]

**Pull request merged**
