### PR TITLE
Icons for cawbird

### PR DESCRIPTION
**Pull request by palob**
https://github.com/IBBoard/cawbird

cawbird
cawbird-ci
cawbird-sq

+small alignment fixes for corebird.

### CODE REVIEW

**Comment by Foggalong** [comment]
Seeing the corebird design for the first time in quite a while I'm realising it probably shouldn't be full baseplate anymore. Maybe just a purple squashed circle on a darkish blue background with the additional features overlapped? Then something similar for Corebird

**Review by Foggalong — CHANGES_REQUESTED** [review]
Seeing the corebird design for the first time in quite a while I'm realising it probably shouldn't be full baseplate anymore. Maybe just a purple squashed circle on a darkish blue background with the additional features overlapped? Then something similar for Corebird

**Comment by palob** [comment]
This is my take on this.
cawbird-draft svg
corebird-draft
corebird-draft2

Looks cool but on the other hand it's an icon predestined for a full-baseplate design. Maybe the symbol is just too big at the moment?

**Comment by Foggalong** [comment]
I love this design update, definitely go with that! Full-baseplate designs are something I want to gradually faze out from the theme so there's certainly no harm done with this change

**Comment by palob** [comment]
brain oder no-brainer for corebird?

**Comment by Foggalong** [comment]
@palob Let's keep the brain lines yeah. Thanks again for your work on this!

**Comment by palob** [comment]
Pushed

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
Perfect :heart:

**Pull request merged**
