### PR TITLE
Dedicated icons for adriconf

### PR DESCRIPTION
**Pull request by palob**
In lieu of the symlinks in #4568

adriconf-ci
adriconf-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
Can we tried this with an actual cog symbol rather than a cut out?

**Comment by palob** [comment]
Here's a white cog
adriconf-test

**Comment by Foggalong** [comment]
@palob That's good with me :+1:

**Comment by palob** [comment]
Pushed :+1:

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
