### PR TITLE
Icons for Edraw Max

### LINKED ISSUE #5607: Icon Request: Edraw Max
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Edraw Max`| `edrawmax` | `edrawmax.desktop` | edrawmax |

Description: `All-in-One Diagram Software`

Website: `https://www.edrawsoft.com/download-edrawmax.html#linux`

### PR DESCRIPTION
**Pull request by really-need-an-api-key**
Fixes #5607.

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| original |  circle | square |

### CODE REVIEW

**Comment by really-need-an-api-key** [comment]
Looking at it now I think the symbol could be nudged 1px to the right to center it visually.
circle

**Comment by palob** [comment]
I haven't had a close look so maybe yes. There is the baseplate bevel though which counteracts the left-heaviness a bit.
Looking from distance, maybe the symbol could be a bit brighter, more like the original one. Right now it looks like there even is a coloured tint (my eyes?).

**Comment by really-need-an-api-key** [comment]
I've used #ddd for the symbol, but I could bump it up to #f9f9f9. And the horizontal line too.
Screenshot_2021-03-22_10-23-28

**Comment by palob** [comment]
Yes, I prefer this version.

**Comment by really-need-an-api-key** [comment]
circle
square

**Review by palob — APPROVED** [review]

**Comment by really-need-an-api-key** [comment]
Fixed gradient range as per your comment in #5710.
circle-edraw-max
square-edraw-max

**Review by palob — APPROVED** [review]
Thank you.

**Pull request merged**
