### PR TITLE
imdb - Icons and entry for IMDb.

### LINKED ISSUE #2895: Icon for IMDb (Chrome Web App)
A numix-circle icon for IMDb is missing.
Thanks for great work!

[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=IMDb
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=ciioilnaleldclnoaglmkejfikodhdai
Icon=chrome-ciioilnaleldclnoaglmkejfikodhdai-Default
StartupWMClass=crx_ciioilnaleldclnoaglmkejfikodhdai

imdblogo

### PR DESCRIPTION
**Pull request by W-Floyd**
Fixes #2895

As simple as the IMDb text is, it's hard to get pixel aligned and not look weird. As is, the cutouts in 'D' and 'b' are 1/2px off.

iconified_imdb

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Can you add the Android entry too please? :+1:

**Comment by W-Floyd** [comment]
So, like this?

```
    "imdb": {
        "android": {
            "root": "com.imdb.mobile"
        },
        "linux": {
            "root": "chrome-ciioilnaleldclnoaglmkejfikodhdai-Default"
        }
    },
```

**Comment by bilelmoussaoui** [comment]
Nop, android icons doesn't have a root icon. It should be a list of icons that uses this one. So something like this
```
        "android":[
"com.imdb.mobile"
      ]
```
with the correct indent of course :p

**Comment by W-Floyd** [comment]
Ah, yep, so:

```
    "imdb": {
        "android": [
            "com.imdb.mobile"
        ],
        "linux": {
            "root": "chrome-ciioilnaleldclnoaglmkejfikodhdai-Default"
        }
    },
```

**Review by Foggalong — CHANGES_REQUESTED** [review]
Some of the lettering could be slightly better aligned to grid. Not ever line has to be bang on (it's especially difficult to do with alphabet) but there are a few that are already quite close and just not quite there

**Comment by W-Floyd** [comment]
How about this? I ended up snapping almost everything, seems okay still, since I retained the shaping.

iconified_imdb

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
