### PR TITLE
Icons for Date Countdown

### LINKED ISSUE #4087: Icon Request: Date Countdown
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Date Countdown | `com.github.rickybas.date-countdown` | `com.github.rickybas.date-countdown.desktop` | Date Countdown| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

### PR DESCRIPTION
**Pull request by really-need-an-api-key**
Another long overdue one. Fixes #4087.

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| image | circle-date-countdown | square-date-countdown

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
The slash path is slightly misaligned. The nodes are placed at integer coordinates, with nodes arranged like that, this makes the shape exceed the pixel grid though. You can fix this by resizing the slash to 10px X 10px and recentering.

**Comment by really-need-an-api-key** [comment]
Like so? 
image

**Review by palob — CHANGES_REQUESTED** [review]
Exactly! 

Sorry for not noticing earlier, I think the upper circle can by moved down by 0.5 px without distorting the symbol too much.

circle

**Comment by really-need-an-api-key** [comment]
Yeah, I left it at half coords because the middle of it was in line with the outer circle.
Moved it down.

**Review by palob — CHANGES_REQUESTED** [review]
Thank you.
Both symbol shadows are sitting 1 px too low now.

**Comment by really-need-an-api-key** [comment]
D'oh.

**Review by palob — APPROVED** [review]

**Pull request merged**
