### PR TITLE
Specific icon for OpenERP

### PR DESCRIPTION
**Pull request by Foggalong**
Actually just a recolour of Opera's original icon, but who's counting

### CODE REVIEW

**Comment by Foggalong** [comment]
Hmmm, seems there's some significant cruft being left in the circle icon. Will investigate what that is.

**Comment by Foggalong** [comment]
Just an extra gradient, all good! :+1: Gonna take a look at the other Opera icons too and update them to the new design

**Comment by Foggalong** [comment]
Also a cheeky reuse of the old Opera Next colour scheme for the refreshed Opera Widget icon :grin:

**Comment by Foggalong** [comment]
@palob From what I can tell there aren't actually any build issues, but Travis isn't happy that our tester depends on Python 3.4 - pinged Bilal about sorting that in #4048

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
As an aside, OpenERP seems to be [odoo](https://www.odoo.com) these days.

**Comment by Foggalong** [comment]
Oh my word, if I'm reading this right what was one app has since been split into over 40. If someone requests we'll cover it but probably not one to go out of our way to preempt.

**Pull request merged**
