### PR TITLE
Icon and entries for Stardew Valley.

### PR DESCRIPTION
**Pull request by W-Floyd**
Going with the idea of sane naming of these sorts of things, I've gone with `stardew_valley` for the filename, root name `gog-stardew-valley`, and symlink to `steam_icon_413150`. This has been languishing in a branch of mine for a while, finally got around to processing it (hopefully) correctly.

iconified_stardew_valley

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Can you try a greenish or blueish background?

**Comment by W-Floyd** [comment]
Any input?
image
Personally, I don't mind this blue.

**Comment by Foggalong** [comment]
Good call @palob! And yeah @W-Floyd I like that blue also :+1:

**Comment by W-Floyd** [comment]
iconified_stardew_valley

**Review by palob — APPROVED** [review]

**Pull request merged**
