### PR TITLE
Icons for The Signal From Tölva

### PR DESCRIPTION
**Pull request by BlueManCZ**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| original | steam_icon_457760 | steam_icon_457760 |

https://steamdb.info/app/457760/

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution.
A few things need to be adressed:
+ All icons need an entry in the database file ``data.json``. It's ordered alphabetically. Just take a look, if it isn't self-explaining enough don't hesitate to ask back
+ All horizontal vertical lines need to be aligned with the pixel grid (´´#´´ key in Inkscape to toggle it), otherwise the icon will appear blurry. In most cases nodes should be placed at integer px coordinates as well.
align
+ Please save your icons as *Optimised SVG* with options as shown here https://github.com/numixproject/numix-core/wiki/Optimise-Options

**Comment by BlueManCZ** [comment]
I will keep this in mind. Thank you for letting me know.

**Review by palob — CHANGES_REQUESTED** [review]
Thank you, alignment is spot-om now.

The icons files need to be named ``the-signal-from-tolva.svg``, otherwise the build script fails.

**Comment by BlueManCZ** [comment]
Oh, got it. My bad, sorry. :see_no_evil:

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]
Excellent first contribution, thanks @BlueManCZ!

**Pull request merged**
