### PR TITLE
Icons for Eclipse C/C++ Debugger

### PR DESCRIPTION
**Pull request by palob**
eclipse-cdt
eclipse-cdt-ci
eclipse-cdt-sq

+ optimisations and coloured baseplates for existing Eclipse icons.

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I like the new baseplate, but I think we're gonna have to do some artistic interpretation here and treat the white bars on both icons as clippings from the symbol. As is the light purple and the white don't work great together

**Comment by palob** [comment]
Same treatment for the original Eclipse icon?

**Comment by palob** [comment]
eclipse-cdt-ci
eclipse-cdt-sq
eclipse-ci
eclipse-sq

**Comment by Foggalong** [comment]
That's perfect!

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
