### PR TITLE
Icon for Sequeler

### PR DESCRIPTION
**Pull request by palob**
https://github.com/Alecaddd/sequeler

com github alecaddd sequeler

sequeler-numix

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Maybe trying a lighter grey with a bit darker green?

**Review by Foggalong — CHANGES_REQUESTED** [review]
Yeah, this design doesn't sit very well with me. How does it look with the servers in there too?

**Comment by palob** [comment]
sequeler svg

**Comment by palob** [comment]
server

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
