### PR TITLE
7BD8_halo.0: Adds icon for Halo (Wine app)

### PR DESCRIPTION
**Pull request by W-Floyd**
The game plays well under wine, love the nostalgia :)
iconified_7bd8_halo 0

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
@W-Floyd @palob @Foggalong I think it's better to name the Wine & Chrome apps icons as `halo` (in this case) and a symlink to the real icon name. This will make it easier for us to find

**Comment by W-Floyd** [comment]
Sounds like a good idea to me. Would the same apply to steam icons?

Just to confirm:
```
    "halo": {
        "linux": {
            "root": "7BD8_halo.0"
        }
    },
```

And, should there be a symlink (once [IO1](https://installation01.org/) is released, for example):
```
    "halo": {
        "linux": {
            "root": "7BD8_halo.0",
            "symlinks": [
                "installation-01"
            ]
        }
    },
```

**Comment by Foggalong** [comment]
@bil-elmoussaoui @W-Floyd Yeah, I agree! That's why core was built so the linux root didn't have to match the icon name :)

**Comment by palob** [comment]
I think it'd be cool to have descriptive names in core in the long term and get rid of the unwieldy ones.
Not only DB entries but base icon names as well.
Makes it easier to see what's covered.

**Comment by Foggalong** [comment]
Base and in base icon theme? I don't follow

**Comment by palob** [comment]
Basically this #3701

**Comment by bilelmoussaoui** [comment]
@Foggalong @palob It would be even better if we can split the icons into different categories: Games, Web Apps, Browsers, Multimedia, Tools... This way, it will be much easier to find an icon (there's more than 2000 at the moment...) and things will get more complicated ones we merge in the Android icons in the future

**Comment by Foggalong** [comment]
@bil-elmoussaoui Only problem I've been able to come up with doing that is some apps may fit into two categories; e.g a web app that's a game, or a multimedia tool

[Moka](https://github.com/snwh/moka-icon-theme/tree/master/src) sorts things by first letter (and then weirdly `web-*.svg`) but that again has the problem that you might not know what name an app is using.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
