### PR TITLE
11 new icons

### PR DESCRIPTION
**Pull request by hmlendea**
I have created this icons a long time ago and I used them for myself for a while. I want to share them with the rest of the community. Unfortunately I don't have the original icons since I don't have the software they were created for installed anymore. Also, I don't have Square versions for all of them.

aom - Age of Mythology
awe - Ancient Wars Sparta
bomberman - Atomic Bomberman / other Bomberman games
emu8086 - EMU 8086 Assembler and Emulator
landrule - Landrule (Android game)
maple - Maple (Technical computing software)
nfsc - Need for Speed Carbon
starcraft - Starcraft & SC Broodwar & SC Remastered
starcraft2 - Starcraft 2 & all of its expansions
starcraft2mr - Starcraft 2 Mass Recall (mod)
stronghold - Stronghold & the HD edition

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
There's some missing square icons, can you take care of that? Plus, the icons must be saved as optimized, you can find the Inskcape options we use in our wiki

**Comment by hmlendea** [comment]
I get an python-lxml error when trying to save as optimised, even tho I have the package installed.

**Comment by hmlendea** [comment]
Done

**Comment by palob** [comment]
Hi, thanks for contributing. For unrelated icons we prefer one PR for each icon so we can review and merge separately.

Design-wise I can say that all symbols are too big and need alignment to the pixel grid. Please take a look at our non-exhaustive [design guidelines](https://github.com/numixproject/numix-core/wiki/Guidelines) and feel free to ask for further assistance.
Some icons are too detailed and fine-grained to fit into our theme right now.

**Review by Foggalong — CHANGES_REQUESTED** [review]
:(

**Comment by hmlendea** [comment]
I completely forgot about this, lol. I was so busy with other stuff lately.

I will see if I can have time this weekend to learn how to apply the requested changes.

**Comment by hmlendea** [comment]
Hello. I cannot finish this unfortunately :( Can someone else finish the necessary changes or will those icons be lost?

**Comment by mrmeszaros** [comment]
@hmlendea I can take it - if you do not mind.
@palob should I create a separate PR (or multiple ones) for the icons, or am I able to commit on this PR somehow?

**Comment by bilelmoussaoui** [comment]
It will take longer for you to commit directly to this PR than creating a new one. It's better to have an icon per PR which makes the review easier 👍

**Comment by Foggalong** [comment]
Will close this one then, with @matemeszaros having the intent to open more to replace it :)

**Pull request closed without merging**
