### PR TITLE
Icons for The Talos Principle 

### PR DESCRIPTION
**Pull request by maxtron95**
For #4854

the-talos-principle-ci
the-talos-principle-sq

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Comment by maxtron95** [comment]
@palob Can I add icons for the game "The Talos Principle VR" to this PR?

**Comment by palob** [comment]
Aye, go ahead please.

**Comment by maxtron95** [comment]
Added Icons for The Talos Principle VR

https://store.steampowered.com/app/552440/

talos-vr

talos-vr-ci
talos-vr-sq

**Review by palob — CHANGES_REQUESTED** [review]
Could you please change the baseplate gradient to ``e1e1e1`` -> ``ebebeb``?
Otherwise the icon will stand out brighter from our other "white" icons.

**Review by palob — APPROVED** [review]

**Pull request merged**
