### PR TITLE
distributor-logo-tails - Icons and entry for Tails.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #2183

iconified_distributor-logo-tails

### CODE REVIEW

**Review by palob — COMMENTED** [review]
I like the symbol but it could be a bit bigger. Did you try?

**Comment by W-Floyd** [comment]
Yeah, I'll give that a go. Will take a bit of fiddling, that's all.

**Comment by W-Floyd** [comment]
iconified_distributor-logo-tails

That's a lot better, IMO.

**Comment by palob** [comment]
Makes better use of the baseplate 👍

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
