### PR TITLE
Icons for Atom Zombie Smasher

### PR DESCRIPTION
**Pull request by maxtron95**
https://store.steampowered.com/app/55040/

atom-zombie-smasher

atom-zombie-smasher-ci
atom-zombie-smasher-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
That's a cool design, the guy should cast a shadow on the circle though.
I think you can be a bit more casual about alignment for the hands/arms so that they look less deformed.

**Comment by maxtron95** [comment]
@palob Was that tag supposed to a `merge` tag?

**Comment by palob** [comment]
Well spotted, thank you :)

**Comment by palob** [comment]
If the guy is supposed to be a zombie his arms can stay deformed of course.

**Review by palob — APPROVED** [review]

**Pull request merged**
