### PR TITLE
Icons for Killing Floor

### PR DESCRIPTION
**Pull request by maxtron95**
https://store.steampowered.com/app/1250/

killing-floor

killing-floor-ci
killing-floor-sq

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Comment by Foggalong** [comment]
I could have sworn I'd made an icon for this at some point but I can't find it _anywhere_. Maybe I made it for another theme? Either way, this is great!

**Comment by palob** [comment]
We've got this in another colouring, don't remebmber the name.

**Comment by Foggalong** [comment]
It was the name rather than the design that sounded familiar. I think we had one like this for Plague Inc maybe?

**Comment by maxtron95** [comment]
Yes, I used the Plague Inc icon as a template because Killing Floor uses a bio-hazard icon as well.

**Comment by BlueManCZ** [comment]
I would move symbol in circle icon 1px upside. What do you think?

| Original | Moved |
| - | - |
|  |  |

**Comment by palob** [comment]
From this view it looks a bit more centered indeed.

**Pull request merged**
