### PR TITLE
Add icons and entry for Piper.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #3889

Hope it's okay that I played with the perspective for the square symbol. It didn't feel right to keep it the same as the circle but change the shadows.

iconified_piper

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Cool design but looks a bit busy I'm afraid. Is it recognisable even at 48px?
I think the baseplate should get a more distinctly contrasting colour.

**Comment by W-Floyd** [comment]
So-so, I guess. Any ideas?

iconified_piper

**Comment by palob** [comment]
I haven't come up with a better idea either so far which is why I've chickened out of doing this icon.

**Comment by W-Floyd** [comment]
I see... I don't see other icon packs that have made one either.

**Review by Foggalong — APPROVED** [review]
It's not perfect, but better than nothing. We can come back to it later if needed

**Pull request merged**
