### PR TITLE
Square: Remove clip stuff

### PR DESCRIPTION
**Pull request by palob**
For #3482
Couldn't find any broken icons.

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I just spent about an hour writing a review of this pull request, got about 500 icons in and then my computer crashed deleting all of it. Unfortunately I didn't back it up and I don't have time to redo it right now, but there are a quite a few icons which have errors. When I've got some free time I'll go back through and redo it, but that might be in a couple of weeks.

**Comment by palob** [comment]
How did you find the errors, I mean what was the viewer or the file manager?

**Comment by Foggalong** [comment]
@palob Viewer to check for them, verified in file manager and Inkscape once spotted :)

**Comment by palob** [comment]
But which viewer and file manager so I can reproduce it?

**Comment by Foggalong** [comment]
Ohhh I get you. The GitHub viewer for the initial pass (it can't handle clips). The file manager wasn't used for checking clips I just meant I'd downloaded them :)

**Comment by palob** [comment]
I'll check again but as far as I recall GitHub-broken icons can still be fine in the wild.

**Comment by Foggalong** [comment]
Huh, I wasn't aware of that! That must be an extra thing GitHub SVG hasn't implemented. But yeah, of the specific errors here I noticed through GitHub all were present when examined locally.

**Comment by palob** [comment]
Couldn't find any broken icons so far.

**Comment by palob** [comment]
Ah, found a missing shadow, now let's see...

**Comment by palob** [comment]
Checked again three times and I could only identify ``8bitmmo`` and ``audience`` as broken. Will fix this along with other minor issues spotted.

**Comment by palob** [comment]
Should be fixed.

**Comment by Foggalong** [comment]
@palob Checking this over again this evening, got some free time to delve back through them all :smiley:

**Comment by Foggalong** [comment]
Sorry to disappoint your :rocket: but I got distracted by other things (see #4737 and [here](https://github.com/Foggalong/hardcode-fixer)) so I'll have to come back to this again later in the week. It's only week one so time will (hopefully) be fairly free

**Comment by palob** [comment]
Alright, I'll probably be snowed under for a few days as well.

**Review by Foggalong — CHANGES_REQUESTED** [review]
This is the longest code review I've done for a single PR in quite a while, about five hours total. Because of the size I guarantee I won't have caught everything but I think I've got most of the main ones here. Your last commit also addressed a couple of others.


## :red_circle: Blocking
These the major issues which must be fixed before this PR can be merged.

### File Inclusion
- [x] scouring.sh accidentally included
- [x] svgclean accidentally included

### High Priority Design Issues
- [x] circle/unity-tweak-tool: incorrect symbol shadow
- [x] square/kairo: symbol has circle specific cropping
- [x] square/minecraft: symbol borked completely
- [x] both/login: symbol transparency
- [x] both/syspeek: symbol transparency


## :large_orange_diamond: Priority Design Issues
Ideally these should be fixed before this is merged because it's not great that they've gone unchecked. We may as well address them now while their icons are being touched. Unless specified, the issue affects Circle & Square. However, if you don't have time right now let me know and I'll give them a bash (or otherwise open new issues).

### Base-Symbol Shadow
These apps have a symbol which is transparent and appears close to the colour of the baseplate. It looks a bit weird (to the point of looking like a bug) and could do with being change to solid colours.
- [ ] qtapps:
    - [ ] qmlscene
    - [ ] qtassistant
    - [ ] qtconfig
    - [ ] qtcreator
    - [ ] qtcreatorubuntu
    - [ ] qtdbusviewer
    - [ ] qtdesigner
    - [ ] qtlinguistic
- [x] terra
- [x] yakuake

### Gradients
These icons have gradients which just need stripping out for solid colours.
- [x] security-medium
- [x] tomate
- [x] thunderbird-trunk
- [x] vmware-player

### Edge Misalignment
While I daresay there are other examples of icons in the theme with non-aligned edges, these are mostly straight edged icons which are still misaligned.
- [x] draftsight
- [ ] kingsoft:
    - [ ] kingsoft-presentation
    - [ ] kingsoft-spreadsheets
    - [ ] kingsoft-writer
- [ ] phpstorm
- [x] system-config-samba
- [x] web-yahoo

### Symbol Outlines
Symbols with outlines rarely look in place within Numix (thought there are a few that work) but these especially egregious examples really need changing.
- [x] pacmanxg
- [x] pgadmin
- [ ] pycad
- [x] tupi (use outline colour for baseplate)

### Medium Priority Design Issues
- [x] gtk-recordmydesktop: symbol colour needs changing
- [x] musescore: symbol strokes are way too thin
- [x] super-meat-boy: kill chin shadow
- [ ] unity-monodevelop: symbol needs overhaul


## :blue_heart: Further Improvements
These are honestly not a priority. If you don't have time to (or otherwise don't fancy doing it) address them now let me know and I'll file them off into their own issues where applicable.

### Folder Symbols
These should be standardised to the new design, with respective alts added for numix-folders.
- [x] gnome-commander
- [x] krusader:
    - [x] krusader-root
    - [x] krusader-user
- [x] mansa
- [x] marlin
- [x] nemo
- [x] shares

### Symbol-on-Symbol Shadow
These apps have distinct symbols layered on symbols which look like there should have be too distinct shadows, but don't. However this issue is relatively minor, not detracting much from the appearance.
- [ ] cxmenu:
    - [ ] cxmenu-cxoffice-0-cxregister
    - [ ] cxmenu-cxoffice-0-cxreset
    - [ ] cxmenu-cxoffice-0-cxrun
    - [ ] cxmenu-cxoffice-0-cxuninstall
- [x] movie-editor
- [ ] oracle-sqldeveloper

### Low Priority Design Issues
- [x] chromium-bsu: pink baseplate
- [x] dart: light blue baseplate
- [ ] teamviewer: symbol should be cutout or other colour
- [ ] ubuntu-tweak: green cog needs changing
- [x] wmtweaks: close button misalignment
- [ ] xdiagnose: symbol shouldn't be a cut out

**Comment by palob** [comment]
Wow, thanks for taking this much time. Yeah, the Qt icons have been odd since my first contact with Numix but so far I've steered clear. I'll do a redesign taking into account the new (not so new anymore) Qt logo/typeface.

I take it the folder icons need only updating for Square?

**Comment by Foggalong** [comment]
Excellent! If at any point you want any of the above transitioning to a new issue (i.e. so it's not blocking the merge of this pull) let me know and I can get that transferred. For now I just thought it'd be easiest to have them all handled here but there's of course no pressure to do that. 

Re folders, I think for all of them it's a case of just the Square design lagging behind the Circle one.

**Comment by palob** [comment]
Some reminders for me:
* [x] **login.svg** use symbol transparency as well.
* [x] Include a fix for #4654

**Comment by palob** [comment]
I'll leave ``phpstorm`` untouched because that's one of the jetbrains icons which need to be redesigned to be in line with Circle anyway. It's those Circle icons with two-colour baseplates.

**Comment by palob** [comment]
Done items are checked off. I won't probably have much time in the coming weeks so you can merge this (if there's no blockers left).

The icons for Qt, Kingsoft, as well as all Adobe icons which need rework too are candidates for separate issues.

The new Square folder icons need to be updated in numix-folders.

**Comment by Foggalong** [comment]
@palob As a heads up, reverted the last commit. I get what you were going for with the design update moving it closer to the original icon, but it's a bit too spiky compared to what we had and that. Happy to take updates on that at a later time though, realise you're busier rn so didn't want to pressure you into fixing it now :)

**Comment by Foggalong** [comment]
I accidentally added some stuff back when resolving conflicts, will fix this in ~2 hours and build.

**Comment by Foggalong** [comment]
New issues following on from this one are:
* #4762 for the Qt Apps
* #4763 for Kingsoft misalignment
* #4764 for PHP Storm misalignment
* #4765 for PyCAD redesign
* #4766 for PacmanXG redesign
* #4767 for Unity Mono-Develop
* #4768 for miscellaneous symbol-on-symbol fixes
* #4769 for Ubuntu Tweak tweaks
* #4770 for XDiagnose redesign

**Review by Foggalong — APPROVED** [review]
Grand  job @palob on this PR! Lots of behind the scenes work we've long neglected went into this so much appreciated :smiley:

**Comment by palob** [comment]
Thanks for the laurels. There isn't much left to be done for the life-tasky #3482. The jetbrains icons + some minor, mostly under-the-hood issues. In some places Square is evn more streamlined compared to Circle.

**Pull request merged**
