### PR TITLE
Icon and entry for Crux.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #2183

iconified_distributor-logo-crux

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Does this work with a beefier, better contrasting baseplate colour?

**Comment by W-Floyd** [comment]
Something coloured you think?

1. image

2. image

3. image

4. image

5. image

**Comment by palob** [comment]
I'd say 2,3 or 5.

**Comment by W-Floyd** [comment]
Arbitrary perhaps, but 5 is based on the colours from their website, so that might be the best.

**Comment by palob** [comment]
Alrighty then :)

**Comment by W-Floyd** [comment]
iconified_distributor-logo-crux

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
Wow, looking at this from another display and it's a horse of different colours.

**Comment by W-Floyd** [comment]
lol In a good way or bad way?

**Comment by palob** [comment]
I'm now back at my own laptop and yeah, it was better, more saturated that is.

**Comment by W-Floyd** [comment]
Ah, great :)

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
