### PR TITLE
Icons for electrum-ltc

### PR DESCRIPTION
**Pull request by palob**
https://github.com/pooler/electrum-ltc

electrum-ltc
electrum-ltc-ci
electrum-ltc-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I think this one can definitely manage without a gradient, just on the orbits use a flat shade which is slightly darker than the one used for the L

**Comment by palob** [comment]
Alright, will change this for the original electrum icons as well then.

**Comment by palob** [comment]
The icons for katomic, Atomic Game Engine and Scientific Linux are based on this design as well IIRC.

**Comment by palob** [comment]
Removed the gradients, think it's all.
One example:
electrum--no-gradient

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
