### PR TITLE
Icons for Grand Theft Auto V

### LINKED ISSUE #5420: Icon Request: Grand Theft Auto V
| Game | Steam AppID | Icon name | Original icon | Banner | Logo |
| --- | :-- | :-- | :-- | :-- | :-- |
| `Grand Theft Auto V` | `271590` | `steam_icon_271590` | original | banner | logo |

Description: `Steam Play whitelested game`

Website: `https://store.steampowered.com/app/271590`

### PR DESCRIPTION
**Pull request by BlueManCZ**
Closes: https://github.com/numixproject/numix-core/issues/5420

| Original icon | Circle icon | Square icon |
| --- | --- | --- |
| ![orig][orig] | ![circ][circ] | ![sqr][sqr] |

https://steamdb.info/app/271590/

[orig]: https://user-images.githubusercontent.com/17854950/86363759-94b15080-bc77-11ea-96df-5015735b6675.png "origi"
[circ]: https://user-images.githubusercontent.com/17854950/86363816-a72b8a00-bc77-11ea-99a7-37874ee0bb9d.png "circ"
[sqr]: https://user-images.githubusercontent.com/17854950/86363830-ae529800-bc77-11ea-8d2e-5e643de0022f.png "sqr"

### CODE REVIEW

**Comment by palob** [comment]
I'm not sure about the black background. Is there any characteristic GTA V colour?
Or maybe it's the white part of the letter which could be bright or dark green with little saturation.

**Comment by BlueManCZ** [comment]
I don't know. Does this look better?

export3
gta

**Review by Foggalong — CHANGES_REQUESTED** [review]
I like the brown but maybe a darker shade (maybe from the buildings)?

**Comment by BlueManCZ** [comment]
GG

**Comment by palob** [comment]
Sorry for the back and forth, could we please try dark brown for the white part and a bright baseplate?

**Comment by BlueManCZ** [comment]
Something like this? 

gta

I don't know, in my opinion it lacks that GTA5 vibes.

**Comment by palob** [comment]
The thing is, the original icon has white and black outlines. I'm not sure, mayve be it's is the perpective of the outline. Maybe it should be isometric.
Could you please try the previous draft (dark baseplate) with a little more brightness+saturation in the baseplate and the *V* serifs increased to a height of 3 px like this?
serif

**Comment by BlueManCZ** [comment]
GS

**Comment by BlueManCZ** [comment]
GA

**Comment by palob** [comment]
The V is still a strange mix of 2D and 3D but an isometric outline doesn't look that nice or does it?
gta

Any ideas, @Foggalong @creepertron95 @mrmeszaros ?
Otherwise I'd say let's go with what's pushed.

**Comment by mrmeszaros** [comment]
If I recall correctly, the banner of GTA games looks usually like this:
gta banner
You could try to incorporate the comic book panel style into the base plate - without much detail to look numixy.

Maybe just pastel colored panels separated by black beams (low contrast) and the "V" in the foreground.
The banner has blue, green, yellow and purple - and in GTA3 they were the colors of the objectives / cash in game.
The white border should provide enough contrast to separate it from the background.

This is risky, and might turn out bad, but might be worth a try.

**Comment by Foggalong** [comment]
@BlueManCZ I like the colours in the pushed version, thanks for bearing with while we  workshopped that!

@palob agreed, I hadn't noticed it until you mentioned it but yeah it looks so much better when that 3D element is taken out.

@mrmeszaros Nay on the comic book panel; we're trying to avoid creating new icons which use the full baseplate now, and at some point those that already do will be reviewed.

**Comment by palob** [comment]
Well, maybe the comic thing as a rectangle instead of full baseplate with a simple V on it.

**Comment by BlueManCZ** [comment]
I made some drafts as @palob suggested. Maybe you will like something, maybe not. We can always change colours, it's just to give you an idea.
|A|B|C|D|E|
|-|-|-|-|-|
|g|g4|g3|g2|g7|


If I can express my subjective opinion, I agree with @palob 

> an isometric outline doesn't look that nice

especially in the small resolutions. Maybe with the thicker outline, it could be fine.

And to this comic style rectangle, I had to shrink the V letter to fit inside. With a smaller resolution, it becomes harder to recognize.

g5 g8 g6

**Comment by BlueManCZ** [comment]
There is also possible extreme like this.

g9
g10

**Review by Foggalong — CHANGES_REQUESTED** [review]
Yeah very much not a fan of the comic books symbols; it was worth a shot but I think it just makes the icon look messy without actually adding much. The cutout one looks okay, but personally not a fan of going with cutout designs when a shapes-on-shapes one is workable.

I would say push [these colours](https://github.com/numixproject/numix-core/pull/5441#issuecomment-653656480) but with [this](https://github.com/numixproject/numix-core/pull/5441#issuecomment-653665236) outlining. We should avoid having too much of a 3D look with it and the original off-centredness comes from the black outline which created that in the original icon.

**Comment by mrmeszaros** [comment]
@BlueManCZ From the ones I like B most, but @Foggalong is right - these do not look numixy to me either.

**Comment by BlueManCZ** [comment]
gta
gta2

**Review by palob — APPROVED** [review]
Thank you for your perseverance :-)

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
