### PR TITLE
Icons for Snapchat (Android)

### PR DESCRIPTION
**Pull request by maxtron95**
https://www.snapchat.com/

snapchat

snapchat-ci
snapchat-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
I see it's from the originl icon but this a very garish colour combination for Numix.
Could you try a brighter and less saturated variant of the baseplate?

These lines should begin straight as in the original icon.
ttt

**Review by palob — CHANGES_REQUESTED** [review]
Baseplate is better now but yellow+white still is a combination I'm not particularly fond of.

Thanks for the straightened sides. However the transition from straight to curve should be smooth.

curving

**Comment by Foggalong** [comment]
I was under the impression we already had a snapchat icon! Will go digging for it

**Comment by Foggalong** [comment]
@creepertron95 It would seem we have a lot of Android icons which were in those themes but never ported over to the Core system: [Circle](https://github.com/numixproject/com.numix.icons_circle/tree/master/Icons) and [Square](https://github.com/numixproject/com.numix.icons_square/tree/master/Icons). I was under the impression I had merged them across but apparently not! It'll be worth one of us digging through that folder and seeing what's worth salvaging from there.

**Review by palob — APPROVED** [review]
I still don't like the colour combination and the outline from the original icon but I can't think of an obvious workaround.

**Pull request merged**
