### PR TITLE
Icon for Google Fit

### LINKED ISSUE #3242: Icon for Google Fit (Chrome Web App)
A numix-circle icon for Google Fit is missing.
Thanks for great work!

[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Google Fit
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=ofbpedjdfkboehhknoohhenbpmgcjoik
Icon=chrome-ofbpedjdfkboehhknoohhenbpmgcjoik-Default
StartupWMClass=crx_ofbpedjdfkboehhknoohhenbpmgcjoik

googlefit

### PR DESCRIPTION
**Pull request by really-need-an-api-key**
Fixes #3242.

googlefit 48
googlefit 192

### CODE REVIEW

**Comment by really-need-an-api-key** [comment]
I see the folders were moved around, should I strip or rebase or something on all my PRs?

**Comment by Foggalong** [comment]
@really-need-an-api-key You can either rebase or just move the icon to the new location in a seperate commit :)

**Comment by really-need-an-api-key** [comment]
Done.

**Comment by Foggalong** [comment]
@really-need-an-api-key Can you also add the lines needed for the `data.json` file?

**Comment by really-need-an-api-key** [comment]
Oh, sorry, I swear I was about to get to it tonight.

**Comment by Foggalong** [comment]
@really-need-an-api-key It's no problem! After some experimenting I realised it couldn't be done without messing about merging in the upstream repo restructure so I just added them in after the fact :)

**Pull request merged**
