### PR TITLE
Icons for esys-escript

### PR DESCRIPTION
**Pull request by maxtron95**
https://flathub.org/apps/details/au.edu.uq.esys.escript
https://github.com/aellery/esys-escript

au edu uq esys escript

escript-ci
escript-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
I think this would work much better with a triangle grid as symbol. Right now it is not obvious that this is about triangulation, some shapes aren't triangles.

**Comment by palob** [comment]
Or maybe a symbol without outlines but (less) differently coloured triangles.

**Comment by maxtron95** [comment]
@palob Do you know why the check failed?

**Comment by palob** [comment]
Couldn't make it out so far.

**Comment by maxtron95** [comment]
@palob Can you show me what you mean by triangle grid how you envisioned it?

**Comment by palob** [comment]
Well, the lines between the triangles which make out the grid.
A rough estimate would be our ``soundnode`` icon (please disregard the two-tone baseplate:) ).

**Comment by palob** [comment]
@creepertron95 @Foggalong Unfortunately I don't remember how I envisaged that "triangle grid".

I'm not sure the following ideas are recognisable metaphors. Any ideas?
esys1
esys2

**Comment by Foggalong** [comment]
@palob maybe you meant the original symbol as pushed but with more differing colours to make it obvious each shape was a triangle?

**Comment by palob** [comment]
Ah thanks, will try that. Maybe needs reducing the number of triangles.

**Pull request merged**
