### PR TITLE
Add icons for The Final Station

### LINKED ISSUE #3713: Icon for The Final Station (Steam)
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `The Final Station`| `steam_icon_435530` | `The Final Station.desktop` | the_final_station 48 |

Description: "Travel by train through a dying world. Look after your passengers, keep your train operational, and make sure you can always reach the next station."

Website: http://thefinalstation.com/

### PR DESCRIPTION
**Pull request by mrmeszaros**
Fixes  #3713

| Circle icon | Square icon |
| :-: | :-: |
| the-final-station circle 96 | the-final-station square 96 |

* I will add the shadows if the skull symbol is acceptable

### CODE REVIEW

**Comment by palob** [comment]
Can you make it work with the "middle bar" as a 2px wide line in line with the grid?

There is a stacking problem. You shouldn't implement the black between the white bars as a path on top of the outer path. Instead the baseplate should shine through. This is a cleaner solution involving less paths.

**Comment by mrmeszaros** [comment]
Thanks for the quick review @palob!

I am still working on alternatives for the eyes / nose. I will look into the "tooth" thing you mentioned.
The stacking problem is intentional: it is much easier to create alternatives with this method.

I will flatten and add the shadow when the symbols parts will be acceptable.

**Comment by mrmeszaros** [comment]
Hey,
Here are two options with the _middle bar_ change in place:

| A | B |
|---|---|
| mouth-a | mouth-b |

Also here are some options for the eyes.
* Current is **D**
* I like **E** the most

| D | E | F |
|---|---|---|
| eyes-d | eyes-e | eyes-f |

Maybe the nose could be reworked too...

**Comment by palob** [comment]
Yeah, E looks best albeit I prefer the eyes from D. And I think a rounded off nose will look better.

**Comment by mrmeszaros** [comment]
@palob Added a round top for the nose - here it is rendered (_in 512x512, with shadow_):
the-final-station 512

**Comment by palob** [comment]
Alright, can you add the shadow and finalise the stacking?

**Review by Foggalong — APPROVED** [review]
This looks ready to me now. @palob?

**Comment by palob** [comment]
Yeah, good to go.

**Review by palob — APPROVED** [review]

**Pull request merged**
