### PR TITLE
More Square maintenance

### PR DESCRIPTION
**Pull request by palob**
For #3482 + Circle fixes

square12
some-more

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
* shadow on the circle icon is for square
* the smile for reddit looks creepy - make it flatter
* general comment: why the change to the wine colour?

**Comment by palob** [comment]
Regarding the wine colour I thought I'd make it a bit more [Windowsy](https://de.wikipedia.org/wiki/Microsoft#/media/File:Microsoft_logo_(2012).svg ). Got a bit exaggerated maybe.

**Comment by Foggalong** [comment]
Comparison of the old colours, new colours, and the ones from the official logo:

2018-03-13-145319_1093x484_scrot

It might actually be the green which needs to be a shade darker rather than the yellow

**Comment by palob** [comment]
Everything's fixed!

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
