### PR TITLE
updated GTK logo

### PR DESCRIPTION
**Pull request by palob**
old
gtk-old
new
gtk-upd

updated the gtkhash icon accordingly
gtkhash
gtkhash-old
gtkhash-upd

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I like the GTK update but I think the gtkhash design needs some work, though that's not helped by the new upstreamdesign being nooooot great. Is there a way to tweak the design so that it doesn't look like it has an outline?

**Comment by palob** [comment]
My first idea was to just slap a plain right-angled **#** on it but then I thought the idea of the original one of having the **#**-lines following the ones of the GTK cube was not the worst as it makes the icon look less cluttered. It does work without the meme-style outline but the **#** will look a bit flimsy then.

**Comment by palob** [comment]
I'll try how it looks with the outline turned white.

**Comment by palob** [comment]
Does this look better?
gtkhash2

**Comment by Foggalong** [comment]
Yeah, like that much more!

**Comment by palob** [comment]
Pushed.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
