### PR TITLE
[Square] Gitter

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Gitter Square icon

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Review by palob — CHANGES_REQUESTED** [review]
Gradient looks to be placed 48px too far up.

**Comment by bilelmoussaoui** [comment]
Fixed

**Review by palob — CHANGES_REQUESTED** [review]
No it's horizontal instead of vertical.

**Comment by bilelmoussaoui** [comment]
Should be okay now :)

**Review by palob — APPROVED** [review]

**Pull request merged**
