### PR TITLE
Update qgis icon.

### LINKED ISSUE #4227: Update to new QGIS icon
| Aplication name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `QGIS`| `qgis` or `qgis-icon` | `qgis.desktop` | original |

Description: `A Free and Open Source Geographic Information System`

Website: `https://qgis.org/`

*Proposed idea for new QGIS icon (Numix-square style)*:
QGIS icon - Numix-square style

### PR DESCRIPTION
**Pull request by W-Floyd**
Resolves #4227

Before:

iconified_qgis

After:

iconified_qgis

### CODE REVIEW

**Comment by msevilla00** [comment]
I like mi proposal: https://github.com/numixproject/numix-core/issues/4227
with green gradient withing the "Q" and a white-grey background
Anyway I guess it is necessary to change old icon and replace with a variation of the official one.
Good work!

**Comment by palob** [comment]
The old icon needs to be kept as ``merkaartor`` which is symlinked right now.
Maybe while you are at it you couls do #3333? The QGIS symbol on an earth icon?

The **Q** stick sticks a bit far out on the Circle icon. Maybe a 28x28 or a 26x26 circle for the symbol?

**Comment by msevilla00** [comment]
I would change QGIS Browser icon to a Q (from this proposal) with a folder. I do not like current/official one.
But in case of use a earth you could use a browser one changing colors to green.

**Review by Foggalong — CHANGES_REQUESTED** [review]
As @palob says, the design can't just be updated because there are non-qgis icons linked to it. The old design needs renaming to `merkaartor` and the JSON file needs switching around.

**Comment by W-Floyd** [comment]
iconified_qgis

**Review by Foggalong — APPROVED** [review]

**Review by palob — APPROVED** [review]

**Review by palob — APPROVED** [review]

**Pull request merged**
