### PR TITLE
Some more distro icons

### PR DESCRIPTION
**Pull request by palob**
For #2183 
distros

distros-square

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
For the most part looking good!

* Voyager symbol is too big - it's supposed to be 24px for perfect squares
* Why the split baseplate on the arya icon?
* Use a light pink baseplate for pepermint

**Comment by palob** [comment]
Revised:
distros2
distros2-sq

**Comment by palob** [comment]
void

**Comment by Foggalong** [comment]
@palob I legit fixed that locally and then pushed & deleted the wrong version. Silly me :angry: what settings are you using btw for saving as optimised SVGs? It looks like yours are coming about a bit leaner than mine

**Review by Foggalong — APPROVED** [review]

**Comment by palob** [comment]
options as shown here #3772.

**Pull request merged**
