### PR TITLE
Icons for Wiznote

### LINKED ISSUE #2571: Icon request for Wiznote
Website: [Wiznote](http://www.wiz.cn/)

```
[Desktop Entry]
Name=WizNote
Name[zh_CN]=为知笔记
Name[zh_TW]=为知笔记
Comment=cloud based note-taking application
Comment[zh_CN]=开源云笔记
Comment[zh_TW]=开源云笔记
Exec=WizNote
Terminal=false
Type=Application
StartupNotify=true
Icon=wiznote
Categories=KDE;Qt;Utility;
```

screenshot from 2015-09-27 12 04 48
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26978432-icon-request-for-wiznote?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by really-need-an-api-key**
Fixes #2571.

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| 94ab7d68-6510-11e5-8722-d402cf66c960 | wiznote circle | wiznote square |

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Could you somehow wrench the symbol to a 24x22 size (slightly bigger) with the individual **W** lines aligned with the grid?

**Comment by really-need-an-api-key** [comment]
Sure I'll give it a try,

**Review by Foggalong — CHANGES_REQUESTED** [review]
@really-need-an-api-key Any update on this? :)

**Comment by really-need-an-api-key** [comment]
Hah sorry, been a little busy. Will try to fix it tonight.

**Comment by Foggalong** [comment]
@really-need-an-api-key Any joy? No worries if not :)

**Comment by palob** [comment]
@really-need-an-api-key Are you still interested in doing this? Otherwise I'll do it.

**Comment by Foggalong** [comment]
@palob I think you can claim this one as yours :+1:

**Comment by palob** [comment]
wiz-ci
wiz-sq

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]
Thanks @palob :+1:

**Pull request merged**
