### PR TITLE
Better Symbol-on-Symbol Designs

### LINKED ISSUE #4768: Symbol-on-Symbol Tweaks
These icons just need a bit of a tweak to make better use of symbol-on-symbol shadows.
* [x] cxmenu-cxoffice-0-cxregister
* [x]  cxmenu-cxoffice-0-cxreset
* [x]  cxmenu-cxoffice-0-cxrun
* [x]  cxmenu-cxoffice-0-cxuninstall
* [x]  oracle-sqldeveloper
* [x]  teamviewer

Teamviewer in particular, the white symbol on symbol should either be a cut out, have a drop shadow, or be a different colour. It looks oddly flat as is being the same colour as the baseplate.

### PR DESCRIPTION
**Pull request by Foggalong**
Some minor tweaks and improvements for icons which had weird symbol-on-symbol designs. Primarily fixes #4768, but happy to include other icons if people find similar ones which need fixing.

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Comment by Foggalong** [comment]
@palob Hold your horses, still got 5 more to come :sweat_smile: 

What are your thoughts on this change for the SQL dev icon? At the time (and in my head) I thought the shadows would be an improvement it but now I'm not so sure.


sql-old sql

**Comment by palob** [comment]
The left one tells the discs touch, the right one that there's air in between.
I prefer it with some fresh air :)

**Comment by Foggalong** [comment]
This is how it looks with Square for comparison (the design there needs updating either way).

sql-sqr

Are the disks supposed to touch? I'm actually clueless where this metaphor comes from :stuck_out_tongue: I assume something to do with old harddrives but no idea where the three stack comes into that

**Comment by palob** [comment]
Found this https://stackoverflow.com/questions/6111610/what-is-the-database-symbol-supposed-to-represent

So there is gaps. That aside I think the one without shadows looks somewhat broken/unfinished.

**Comment by palob** [comment]
Same with floppy icons still used as metaphor for *save*.

**Comment by Foggalong** [comment]
Rad, TIL there! I'll push the one with the shadows now but will leave cxmenu for this weekend :)

**Comment by Foggalong** [comment]
Longest weekend ever :P Life has been busy, but am hoping to come back to this soon.

**Comment by Foggalong** [comment]
Damn it, totally forgot Square :joy:

**Comment by Foggalong** [comment]
@palob After what is possibly the longest weekend on record I believe we're good to go with this one!

**Review by palob — APPROVED** [review]
That's a lot of icons for one app. Thank you and Happy New Year!

**Comment by Foggalong** [comment]
I know right. I get the feeling they went to the WINE school of application design: launchers for everything!

**Pull request merged**
