### PR TITLE
Macos Dependencies

### PR DESCRIPTION
**Pull request by Supernova4422**
I recently installed this package on my mac, and had a bit of trouble getting it started. These are the dependencies that led me to getting it working, so I thought the documentation could be used to help people in the future.

### CODE REVIEW

**Comment by Foggalong** [comment]
I'm not gonna merge this yet (think there's probably a better way to format the macOS dependency info) but out of curiosity, why? Are you building the themes for macOS, Linux, or just playing with the repo out of curiosity?

**Comment by Supernova4422** [comment]
I was looking to build the repo on mac so I could use the icons on mac (since I can use an app like liteicon to add it). I ended up finding there not to be enough icons for the apps I use so I've ended up using  a different icon set. I think these notes may be reused for the linux build process perhaps (if it is similar).

**Comment by Foggalong** [comment]
@BKrajancic That's useful to know, thanks! Do you know if it was mainly macOS specific application we were missing or were there cross platform apps too? For context, I've been looking at adding more full support for macOS for a while now. Not being a Apple person myself it's been hard to judge whether this will be a case of adding support for a lot of new icons, or whether it'll be a couple of those and then mainly relying on our existing icons.

If you don't mind me asking also, which icon theme did you go with? Always curious to see the competition and with macOS specifically good to see how other themes structure their repos/packages :)

**Comment by Supernova4422** [comment]
It wasn't just system apps which I couldn't find a substitute for, it was a combination of missing system apps and cross platform apps which led me to using another icon pack. Some of the main missing apps I had were the microsoft office apps (word, excel etc.), qbittorrent, sourcetree, vscode, iterm (I can list more if needed). 

I did keep end up using the numix icon folders, they're fantastic and i've not been able to find anything better. 

I used the clay icon pack for most icons:
https://www.deviantart.com/octaviotti/art/Clay-OS-8-A-macOS-IconPack-705013399 

I also used ARC OSX for any icons which were missing from Clay: 
https://github.com/iurrieta/Arc-OSX-Icons

**Comment by Foggalong** [comment]
No pressure to jump ship because obviously if you prefer the other one then use that one, but for future reference if you need it we cover all of the MS Office suite (inc. [word](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/ms-word.svg) and [excel](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/ms-excel.svg)), [qbittorrent](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/qbittorrent.svg), and [vscode](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/visualstudiocode.svg). We don't have specific icons yet for iTerm or sourcetree yet but might add them in future.

And cheer re the folders, glad you liked them!

**Comment by Supernova4422** [comment]
Ah I'll make sure to take another look. For vscode is there an insiders icon as well? I'm not sure if it was numix or clay which didn't have it.

**Comment by Foggalong** [comment]
No icon for insiders yet, but #3902 is open for it to be covered :)

**Comment by Supernova4422** [comment]
Hi, i've decided to give numix another chance for icons on my mac. I've made some updates to the gen.py script for osx, which will create icns files with multiple sizes. I also have fixed the filename extensions which are output by the osx script.

**Comment by Foggalong** [comment]
@BKrajancic There looks to be an issue with that commit breaking PEP8. Check and fix it using pycodestyle and then commit again (it looks to be an issue with tabbing)

**Comment by Supernova4422** [comment]
I apologise for the delay, I thought I had pushed my changes however that was not the case. I've also improved this change to save icns to their proper filename, and to save in various sizes. I've been using the pack again, I love it.

**Comment by Supernova4422** [comment]
Hi this has been sitting around for a while, is there anything I can do to help it push through?

**Comment by Supernova4422** [comment]
I've updated my branch so that it is up to date with numix/master, hopefully that can help out.

**Comment by Foggalong** [comment]
@BKrajancic I've moved the dependency installation information to the wiki; we don't go over installation instruction for any platform in the README at the moment but it could be useful to collate them elsewhere.

In terms of changes to the code, this is looking good and it all seems to be working great! The only note is that I'm replacing the lambda function
```python
filenames = list(map(
     lambda x: "{}_{}.png".format(output_png, str(x)), sizes
))
```
with the list comprehension
```python
filenames = [
    "{}_{}.png".format(output_png, str(x)) for x in sizes
]
```
as part of the OSX generation. The latter is more consistent with the code elsewhere in the script and some rough speed testing would indicate it's just as fast, if not slightly faster.

**Pull request merged**
