### PR TITLE
Kicad icons

### PR DESCRIPTION
**Pull request by Jacajack**
Hi!

[**leoheck**](https://github.com/leoheck) and I made some icons for Kicad sub-apps. (https://github.com/numixproject/circle-core/issues/3265)

Those icons include:

| Description | Icon |
| --- | --- |
| `bitmap2component` - an utility for converting images into schematic components | selection_965 |
| `eeschema` - a schematic editor | selection_966 |
| `gerbview` - Gerber file viewer (like `gerbv`) | selection_967 |
| `kicad` - free electronics CAD (existing icon doesn't really tell anything about the application) | selection_968 |
| `pcbcalculator` - an utility for calculating PCB tracks width and stuff... | selection_969 |
| `pcbnew` - PCB editor | selection_970 |

I hope you like them :)

### CODE REVIEW

**Comment by Jacajack** [comment]
By the way, I'm not sure about `gerbview` and `pcbcalculator`, so any ideas are welcome :)

**Comment by leoheck** [comment]
OMG, I never saw this thread. Sorry @Jacajack. I think `pcbcalculator` is good enough and the `gerbview` can have the magnifying glass small and yellow like the tool in `pcbcalculator`. I also think that a blue glass will fit nice there. What do you think?

**Comment by Jacajack** [comment]
@leoheck, I'm glad to hear that. Do you mean magnifying glass like this one?
selection_001

I'm going to try some variations later and post results here.

**Comment by leoheck** [comment]
Yeah! I imagine it will fit nice.

**Comment by Jacajack** [comment]
@leoheck, sorry for not responding for so long. Here you go:

selection_999 023

selection_999 025

I like the first design indeed, but I'm not sure about the second one. How do you like it now?

**Comment by leoheck** [comment]
I like both. We can choose the first one as you also prefer, it will fit nice with pcbcalculator. Well done.

**Comment by Jacajack** [comment]
Alright, I just changed it :)

**Comment by Foggalong** [comment]
@Jacajack Can you also add the lines needed for the `data.json` file?

**Comment by Jacajack** [comment]
@Foggalong, there you go. If you want only the necessary lines, here they are:

```
    "bitmap2component": {
        "linux": {
            "root": "bitmap2component"
        }
    },
    "eeschema": {
        "linux": {
            "root": "eeschema"
        }
    },
    "gerbview": {
        "linux": {
            "root": "gerbview"
        }
    },
    "pcbcalculator": {
        "linux": {
            "root": "pcbcalculator"
        }
    },
    "pcbnew": {
        "linux": {
            "root": "pcbnew"
        }
    },
```

**Comment by Jacajack** [comment]
Did I really forget so many shadows? Sorry for that!

**Comment by Foggalong** [comment]
@Jacajack No worries, I've pushed icons to master before without realising that the shadow was missing. It's easily done :smile:

**Pull request merged**
