### PR TITLE
Icon for Commonist

### LINKED ISSUE #3630: Icon Request : Commonist

### PR DESCRIPTION
**Pull request by theel0ja**

### CODE REVIEW

**Comment by palob** [comment]
Hi, thanks for your pull request.

A few issues with your icon:

+ The baseplate needs a vertical gradient (10L lighter at the top) in lieu of a solid colour. Please take a look at existing icons. You can take an existing icon, delete the symbol, adjust the gradient colours and paste your symbol in.

+ The symbol needs a drop shadow (duplicate of the outer symbol path couloured black with 25% opacity) shifted 1px down relative to the symbol (Square) / 1px down+1px to the right (Circle).

+ If you go with outline strokes, the stroke width probably shouldn't be short of 1px.

+ Please use L249 at the brightest instead of full-blast white.

+ Albeit the symbol is pretty much centered numerically it looks off-centre. It needs to be shifted maybe 1px to the left and up. For reference, see the similarly designed ``openra.svg``.

+ Please save the SVGs as *Optimised SVG*.

**Review by Foggalong — CHANGES_REQUESTED** [review]
[These changes](https://github.com/numixproject/numix-core/pull/3631#issuecomment-291238641) @palob suggested need to be made.

**Comment by theel0ja** [comment]
"drop shadow" is this?:
image
instead of this (current):
image

**Comment by Foggalong** [comment]
@theel0ja Talking about on the symbol, not on the base plate. See any of the other icons as a reference

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
