### PR TITLE
Icon for 6180 the moon (Steam)

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon | Issue |
| --- | :-: | :-: | :-: |
|  original | 6180_the_moon circle | 6180_the_moon square | #3686 |

### CODE REVIEW

**Review by palob — APPROVED** [review]
The icon is fairly nondescript as such (I think of 6180 in pixel art font or a design based on kbounce.svg as alternative) but then again I noticed the game is basically about a white dot so it's all fine I think.

**Comment by mrmeszaros** [comment]
@palob I know - I thought of adding some lunar craters in light-gray. I may try to add some like on this image:

**Review by Foggalong — CHANGES_REQUESTED** [review]
As @palob said, needs to be slightly more distinctive. Possibly add a few background dots: we have another game icon which is similar so you could use that as a template, but make the stars sparser to match those in the game
screenshot_2017-05-17_21-51-24

**Comment by mrmeszaros** [comment]
@Foggalong added some stars (positioned to the `px` grid):

| Circle | Square |
|:-:|:-:|
| 6180_the_moon circle | 6180_the_moon square |

**Comment by palob** [comment]
Can you use the star array of the existing icon shwn above?

Currently the stars somewhat get in the way of the moon visually.

**Comment by mrmeszaros** [comment]
Are they too close to the moon, or are they too sparse?
I used a script to generate them sparse enough (min distance of 9 pixels, 1 pixel off the moon), so I can regenerate them with tweaked parameters.

**Comment by palob** [comment]
Some are too close.

**Comment by mrmeszaros** [comment]
Tweaked a bit - how about these?
6180_the_moon circle new  6180_the_moon square new

**Comment by palob** [comment]
That's nicer :+1:

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
