### PR TITLE
50 square icons - Round 13

### PR DESCRIPTION
**Pull request by W-Floyd**
Name | Icon
--- | ---
ostorybook | iconified_ostorybook
otter-browser | iconified_otter-browser
pac | iconified_pac
paintown | iconified_paintown
palapeli | iconified_palapeli
paper_green | iconified_paper_green
paperwork | iconified_paperwork
parano | iconified_parano
parcellite | iconified_parcellite
parley | iconified_parley
pasaffe | iconified_pasaffe
pcbcalculator | iconified_pcbcalculator
~~pcbnew~~ | iconified_pcbnew
pd-extended | iconified_pd-extended
pdf-xchange | iconified_pdf-xchange
pd | iconified_pd
peazip | iconified_peazip
peerio-client | iconified_peerio-client
peg-e | iconified_peg-e
pentobi | iconified_pentobi
performous | iconified_performous
peruse | iconified_peruse
pharlap | iconified_pharlap
photocollage | iconified_photocollage
photoflow | iconified_photoflow
phototonic | iconified_phototonic
pick-colour-picker | iconified_pick-colour-picker
picmi | iconified_picmi
picsaw | iconified_picsaw
plague | iconified_plague
planeshift | iconified_planeshift
plasmagik | iconified_plasmagik
~~playitslowly~~ | iconified_playitslowly
plume-creator | iconified_plume-creator
podbrowser | iconified_podbrowser
pogo | iconified_pogo
pokerth | iconified_pokerth
polycode | iconified_polycode
polyphone | iconified_polyphone
portecle | iconified_portecle
powder | iconified_powder
power-installer | iconified_power-installer
ppsspp | iconified_ppsspp
prboom-plus | iconified_prboom-plus
preferences-desktop-display-color | iconified_preferences-desktop-display-color
preferences-desktop-screensaver | iconified_preferences-desktop-screensaver
preferences-system-windows-move | iconified_preferences-system-windows-move
projectlibre | iconified_projectlibre
psi-plus | iconified_psi-plus
ptb | iconified_ptb

### CODE REVIEW

**Comment by palob** [comment]
I think those spots should be coloured red.
playitslowly

Other icons using this design, for instance ``meld.svg`` should be fixed accordingly later on, they're in #3482 anyway.

**Comment by W-Floyd** [comment]
Yeah, meld is what I based it off of (minus the clipping, I stripped that). I'll fix it shortly.

**Comment by palob** [comment]
Note that in Square's meld icon the spiral hasn't got a gradient yet (as opposed to Circle).

**Comment by W-Floyd** [comment]
Okay, I might look into that later. I put the gradient into this one correctly though, so it's all good.
iconified_playitslowly

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
That was fast!

**Comment by W-Floyd** [comment]
Heh, I was working on things anyway. I might be gone for a couple hours (movie), then I'll do the final push for the last 50 :D

**Comment by palob** [comment]
You deserve a treat for sure :cinema:

**Comment by W-Floyd** [comment]
Working on the final round now, movie ran longer than I wanted :P

**Review by Foggalong — CHANGES_REQUESTED** [review]
Symbol & shadow for pcbnew in Square need moving to the right 1px

**Comment by W-Floyd** [comment]
Name | Icon
--- | ---
pcbnew | iconified_pcbnew

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
