### PR TITLE
Icons for Formiko

### PR DESCRIPTION
**Pull request by palob**
https://github.com/ondratu/formiko

formiko
formiko-ci
formiko-sq

### CODE REVIEW

**Comment by palob** [comment]
Perhaps Circle symbol needs to go down 1px.

**Comment by palob** [comment]
Simpler variant
formiko-simple

**Review by Foggalong — CHANGES_REQUESTED** [review]
Good to go on the simpler variant :+1:

**Comment by palob** [comment]
Pushed.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
