### PR TITLE
Icons for Slayaway Camp

### PR DESCRIPTION
**Pull request by maxtron95**
For #4854 

slayaway-camp-ci
slayaway-camp-sq

### CODE REVIEW

**Review by palob — COMMENTED** [review]
I think it's OK as is but how about removing that outer rim which seems to be the background in the original icon? Good idea?
alt

**Comment by maxtron95** [comment]
I'm not sure about that seeing the character from the the game icon

skillface

**Comment by palob** [comment]
Ah I see. Is it possible to get the whole character represented or will this make the skull too fine-grained?

**Comment by Foggalong** [comment]
@palob Took the liberty to push the start of a fix for that issue; make the head the colour of the flesh. There's some more to do like playing with adding the straps and merging the flesh-coloured shapes to be one, but I'll leave finishing that to @creepertron95.

**Review by palob — APPROVED** [review]

**Pull request merged**
