### PR TITLE
100 Square icons and some cleanup

### PR DESCRIPTION
**Pull request by W-Floyd**
First off, I know this PR has gotten a bit... large.

To the best of my knowledge, I have cleaned files up appropriately, namely what seem to be remnants of an old standard, and changed symlinks. To be safe, I have mostly split everything into different commits, so it can be reverted easily if I made a mistake.

As for the Square icons, I didn't have internet at the time to check if a PR was already in for some of them, so bear with me there as well. I won't be offended if someone else's version takes priority over this ;)

The generated images below were done automatically, and tend to err on the side of caution, including changes that may not be visible. Nor do they show before/after, though I can do those if anyone wants to see them...

Name | Icon
--- | ---
distributor-logo-android | iconified_distributor-logo-android
distributor-logo-antergos | iconified_distributor-logo-antergos
distributor-logo-backbox | iconified_distributor-logo-backbox
distributor-logo-bodhi | iconified_distributor-logo-bodhi
distributor-logo-centos | iconified_distributor-logo-centos
distributor-logo-connochaetos | iconified_distributor-logo-connochaetos
distributor-logo-cub | iconified_distributor-logo-cub
distributor-logo-dragonflybsd | iconified_distributor-logo-dragonflybsd
distributor-logo-elementaryos | iconified_distributor-logo-elementaryos
distributor-logo-endlessos | iconified_distributor-logo-endlessos
distributor-logo-freebsd | iconified_distributor-logo-freebsd
distributor-logo-ghostbsd | iconified_distributor-logo-ghostbsd
distributor-logo-guixsd | iconified_distributor-logo-guixsd
distributor-logo-handylinux | iconified_distributor-logo-handylinux
distributor-logo-kaos | iconified_distributor-logo-kaos
distributor-logo-kdeneon | iconified_distributor-logo-kdeneon
distributor-logo-mageia | iconified_distributor-logo-mageia
distributor-logo-maui | iconified_distributor-logo-maui
distributor-logo-netbsd | iconified_distributor-logo-netbsd
distributor-logo-netrunner | iconified_distributor-logo-netrunner
distributor-logo-nixos | iconified_distributor-logo-nixos
distributor-logo-openbsd | iconified_distributor-logo-openbsd
distributor-logo-openmandriva | iconified_distributor-logo-openmandriva
distributor-logo-parabola | iconified_distributor-logo-parabola
distributor-logo-parsix | iconified_distributor-logo-parsix
distributor-logo-pcbsd | iconified_distributor-logo-pcbsd
distributor-logo-qubes | iconified_distributor-logo-qubes
distributor-logo-rhel | iconified_distributor-logo-rhel
distributor-logo-rosa | iconified_distributor-logo-rosa
distributor-logo-sabayon | iconified_distributor-logo-sabayon
distributor-logo-salix | iconified_distributor-logo-salix
distributor-logo-scientificlinux | iconified_distributor-logo-scientificlinux
distributor-logo-slackware | iconified_distributor-logo-slackware
distributor-logo-solus | iconified_distributor-logo-solus
distributor-logo-tanglu | iconified_distributor-logo-tanglu
distributor-logo-trisquel | iconified_distributor-logo-trisquel
distributor-logo-ubuntu-gnome | iconified_distributor-logo-ubuntu-gnome
distributor-logo-ubuntu-mate | iconified_distributor-logo-ubuntu-mate
distributor-logo-windows | iconified_distributor-logo-windows
distributor-logo-xubuntu | iconified_distributor-logo-xubuntu
distributor-logo-zenwalk | iconified_distributor-logo-zenwalk
distributor-logo-zorin | iconified_distributor-logo-zorin
gnome-power-manager | iconified_gnome-power-manager
mediainfo | iconified_mediainfo
multimedia-audio-player | iconified_multimedia-audio-player
obs | iconified_obs
openxcom | iconified_openxcom
peek | iconified_peek
processing-pde | iconified_processing-pde
sparkleshare | iconified_sparkleshare
sqlitebrowser | iconified_sqlitebrowser
steam_icon_248570 | iconified_steam_icon_248570
steam_icon_287980 | iconified_steam_icon_287980
telegram | iconified_telegram
userinfo | iconified_userinfo
vmpk | iconified_vmpk
warmux | iconified_warmux
warspear | iconified_warspear
web-9gag | iconified_web-9gag
web-bandcamp | iconified_web-bandcamp
webby | iconified_webby
webcamoid | iconified_webcamoid
web-delicious | iconified_web-delicious
web-duckduckgo | iconified_web-duckduckgo
webissues | iconified_webissues
web-pocketcaster | iconified_web-pocketcaster
web-pushbullet | iconified_web-pushbullet
web-trello | iconified_web-trello
web-whatsapp | iconified_web-whatsapp
whatsie | iconified_whatsie
wifiguard | iconified_wifiguard
wings3d | iconified_wings3d
wolf4sdl | iconified_wolf4sdl
wolfenstein | iconified_wolfenstein
wolfenstein-the-new-order | iconified_wolfenstein-the-new-order
wordpress | iconified_wordpress
worldoftanks | iconified_worldoftanks
wxcas | iconified_wxcas
wxformbuilder | iconified_wxformbuilder
wxglade | iconified_wxglade
wxmaxima | iconified_wxmaxima
wxmedit | iconified_wxmedit
wyrmsun | iconified_wyrmsun
xcaliber | iconified_xcaliber
xcircuit | iconified_xcircuit
xcos | iconified_xcos
xdman | iconified_xdman
xfce4-panel-restart | iconified_xfce4-panel-restart
xfdashboard | iconified_xfdashboard
xilinx-ise | iconified_xilinx-ise
xmlcopyeditor | iconified_xmlcopyeditor
xneur | iconified_xneur
xt7-player-mpv | iconified_xt7-player-mpv
xware-desktop | iconified_xware-desktop
yacreader | iconified_yacreader
yacreader-library | iconified_yacreader-library
yagf | iconified_yagf
yandex-browser-beta | iconified_yandex-browser-beta
yate | iconified_yate
yokadi | iconified_yokadi
youdao-dict | iconified_youdao-dict
zandronum | iconified_zandronum
zanshin | iconified_zanshin
zathura | iconified_zathura
zbstudio | iconified_zbstudio
zegrapher | iconified_zegrapher
zulucrypt | iconified_zulucrypt
zulumount | iconified_zulumount

### CODE REVIEW

**Comment by W-Floyd** [comment]
With that done, I'm going to bed...

**Comment by palob** [comment]
Thanks for your gargantuan effort!

It is going to be hard to review with Square conversions and other stuff mixed up.

What did you do exactly?

**Comment by W-Floyd** [comment]
@palob You're welcome :)

Ah sorry. I can split this up, if it must be done, but later.

There are a few types of commits you'll find

Remove duplicate: Removes a file that will be symlinked, because there's already a file with the correct root name. See commit 558c1c6

Rename: A square icon was using an old name, while the circle icon and data now use a different root name, and symlink instead. See commit 7b16d49

Removes extra file: An old styled icon that used an old name remains, so I removed it. See commit ebeb124.

Adds square icon: Self explanatory, see commit 327344b.

**Comment by W-Floyd** [comment]
Closing this for now, will submit 2 different PRs once able; I've cherry-picked out the square ports and the cleanup work separately, so they should be easier to review :)

**Comment by W-Floyd** [comment]
See PRs #3827 and #3828

**Pull request closed without merging**
