### PR TITLE
Icons for Markets

### PR DESCRIPTION
**Pull request by palob**
https://github.com/bitstower/markets

markets

markets-ci

markets-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
Think the Circle icon is slightly misaligned to the left

**Comment by palob** [comment]
I shifted it 1px to the left because I thought it looked more centered. Maybe it's just my eyes.

Looks like this with the symbol at X11
markets-ci2

**Comment by Foggalong** [comment]
@palob That alignment works for me :+1:

**Comment by palob** [comment]
Pushed.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
