### PR TITLE
Icons for Baldi's Basics

### PR DESCRIPTION
**Pull request by maxtron95**
https://www.basicallygames.com/baldis-basics.html

baldis

bb-sq
bb-ci

Alternative Baseplate Color:
bb-alt

### CODE REVIEW

**Comment by palob** [comment]
Maybe a (fair way) lighter variant of the alternative colour? As is it lacks some contrast.

**Comment by maxtron95** [comment]
I pushed the alternative color baseplate but brighter for the symbol to contrast with it.

**Comment by palob** [comment]
I think it could be a bit brighter and less saturated still.

**Review by palob — CHANGES_REQUESTED** [review]
There's some SVG cruft left which I'd like you to ask to remove.

Baseplate is alright, could be ever so slightly brighter.

**Review by palob — APPROVED** [review]

**Pull request merged**
