### PR TITLE
Clean names chrome apps

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
This PR does:

- Remove a duplicate icon for whatsapp-desktop and replace it with a symlink
- Remove a duplicate icon `chrome-app-list` and `app-launcher` and replace it with a symlink
- Remove an old icon of Slack was used in a chrome app, and replace it with a symlink
- Remove an old icon of Telegram chrome app, and replace it with a symlink, uTouch has that icon too, so I kept it and renamed it to telegram so it can be used with core.

And rename those icons:
- web-bitbucket
- postman
- web-google-flights
- web-google-fit
- airdroid
- adblock
- web-ebay
- web-omg-chrome
- any-do
- web-line
- web-signal
- sunrise-calendar

The next PR will include the rest of chrome apps (37 icons left) and the steam icons (7 icons left).
The latest PR will just rename some icons like 
- vbox to virtualbox
- unity-webapps-instagram to web-instagram
- unity-webapps-linkedin to web-linkedin 
and so on

### CODE REVIEW

**Comment by palob** [comment]
I'm currently reworking the chrome-xxx Square icons. So this shouldn't be merged until I'm done.

**Comment by palob** [comment]
``chrome-gcjbnclfkeffmdfdhflnadahgmajfgcm-Default`` should be a symlink to ``web-whatsapp`` or something.

I've now cleaned up ``chrome-app-list``. Should I rename it?

**Comment by bilelmoussaoui** [comment]
Yep, it's what i have done on this PR. Replaced the duplicated icon with a symlink

**Comment by palob** [comment]
Which one did you delete?

**Comment by bilelmoussaoui** [comment]
The chrome one, and add the symlink to web-whatsapp

**Comment by palob** [comment]
But which chrome one?
``chrome-app-list`` or ``app-launcher``?

**Comment by bilelmoussaoui** [comment]
This one https://github.com/numixproject/numix-core/blob/6acdab1d3a508df8da89a89a642bb7b993b52117/icons/circle/48/chrome-gcjbnclfkeffmdfdhflnadahgmajfgcm-Default.svg

**Comment by bilelmoussaoui** [comment]
Ah you were talking about the app-launcher. I have removed `chrome-app-launcher`

**Comment by palob** [comment]
@Foggalong Please merge this after my Square cleanup PRs. Otherwise I will have to rename a lot of files.

**Comment by Foggalong** [comment]
Dat merge conflict.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Dat merge conflict.

**Comment by Foggalong** [comment]
Because so much has changed since this was pushed it proved easier to just remake these changes on a new branch rather than sorting out the conflicts here. Thanks for you work on this @bilelmoussaoui, it made it a lot easier. Going to be finishing off the work on the [clean-names](https://github.com/numixproject/numix-core/tree/clean-names) branch through #4406.

**Pull request closed without merging**
