### PR TITLE
Icon for OnlyOffice Desktop Editors

### PR DESCRIPTION
**Pull request by palob**
https://github.com/ONLYOFFICE/DesktopEditors
asc-de-256
asc-de-numix

### CODE REVIEW

**Comment by palob** [comment]
@Foggalong Are the old PRs still mergeable?

**Comment by Foggalong** [comment]
@palob Not straight from the off, the directory for the icons needs changing and the JSON info adding. I'm happy to do that though if you'd like?

**Comment by palob** [comment]
I could do all in one PR if they're good to go.

**Comment by Foggalong** [comment]
@palob The place I am right now doesn't have good enough internet to go through and check pull requests so I can't approve that at the moment. Generally though keeping them in separate pulls would be preferable. If you don't fancy that though (I realise it's a bit of a tedious job) I'm happy to do it :)

**Comment by palob** [comment]
I won't be at my icon stuff PC before Monday. So if you feel like doing it in the meantime you can go ahead :)

**Comment by Foggalong** [comment]
Cool, I'll be back with proper internet tomorrow so I'll sort it then :)

**Pull request merged**
