### PR TITLE
Icons for Armello

### PR DESCRIPTION
**Pull request by BlueManCZ**
| Original icon | Circle icon | Square icon |
| --- | --- | --- |
| ![orig][orig] | ![circ][circ] | ![sqr][sqr] |

https://steamdb.info/app/290340/screenshots/

[orig]: https://user-images.githubusercontent.com/17854950/88567889-66395200-d038-11ea-885f-38920a677bde.png "Original"
[circ]: https://user-images.githubusercontent.com/17854950/88567899-69344280-d038-11ea-81f6-20b7520deb53.png "Circle"
[sqr]: https://user-images.githubusercontent.com/17854950/88567904-6b969c80-d038-11ea-8de8-e8db9d82abd9.png "Square"

### CODE REVIEW

**Review by palob — COMMENTED** [review]
This is nice as is but I wonder how this would look without the frame around the lion symbol.

**Comment by BlueManCZ** [comment]
Do you think it looks better @palob?

a

**Comment by palob** [comment]
Yes, definitely. Symbol looks a bit big though (is it in fact?) and could go up 1px.

**Comment by BlueManCZ** [comment]
It is 28x29px. I will commit it so you can check.

**Comment by palob** [comment]
Yeah, that's a bit big indeed.

**Comment by BlueManCZ** [comment]
I wanted to stick with size of circle from template.

a

**Comment by BlueManCZ** [comment]
I'd rather cut those few protrusions if it's a problem than resize it and align all nodes to the grid again.

**Comment by palob** [comment]
Is the baseplate colour from the original icon? It's a bit glaring with 100% saturation, could be slightly darker.

**Comment by BlueManCZ** [comment]
It is not the same colour. I wanted to adjust the contrast between the baseplate and the dark outline of the symbol.

**Comment by BlueManCZ** [comment]
a

**Comment by palob** [comment]
Could still be less saturated, same for the rim about the lion.

**Comment by BlueManCZ** [comment]
a

**Review by palob — APPROVED** [review]

**Review by palob — CHANGES_REQUESTED** [review]
Approving the colours but could you please repair the dark outline (just "parallel" to the lion symbol). Looks glitchy as is. I take it you wanted to replicate the small dents from the original icon but it doesn't work I'm afraid.

Could you please slightly enlargen the eye and improve alignment?

**Comment by BlueManCZ** [comment]
a

**Review by Foggalong — CHANGES_REQUESTED** [review]
Very good icon, and a solid improvement on the original submission. Props @BlueManCZ!

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
