### PR TITLE
Square icon for retroarch.

### PR DESCRIPTION
**Pull request by W-Floyd**
iconified_retroarch

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
This needs to be saved as Optimised SVG.

**Comment by W-Floyd** [comment]
Okay, will do!

**Comment by palob** [comment]
There's a strange gradient on top of the icon. Otherwise OK.
gradient

**Comment by W-Floyd** [comment]
Okay, I'll clean that up.

**Comment by palob** [comment]
While you're at it can you please perform ``Path -> Union`` on both the symbol and symbol shadow paths? This will remove the inner path outlines.

**Comment by W-Floyd** [comment]
Done. I understand the idea about the path union bit, but I'm not sure that it does anything in this case. Won't hurt though.

**Comment by W-Floyd** [comment]
iconified_retroarch

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
I actually think the Circle symbol should be moved up 1px.

**Comment by W-Floyd** [comment]
Sure

**Review by palob — APPROVED** [review]

**Pull request merged**
