### PR TITLE
Dedicated icons for 1Password

### PR DESCRIPTION
**Pull request by maxtron95**
For #5379 

https://discussions.agilebits.com/discussion/114964/1password-for-linux-development-preview

1password-ci
1password-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I've come back to this one a couple of times and it still looks weird to me. Can we get it slightly smaller and on a 30px white circle a la the original so that it's more clear it's a key hole?

**Comment by palob** [comment]
In addition the corners should probably be rounded like in the original.

**Comment by mrmeszaros** [comment]
Hey, I did rework this slightly - what do You think?

Original | Cirlce | Square
-- | -- | --
1password original 192 | 1password circle 192 | 1password square 192

Though I am not totally sure about the drop shadow - maybe it should "indent" like it's a hole?

**Comment by palob** [comment]
I'd say "indent" shadow on the keyhole and standard drop shadow for the white circle.

**Pull request closed without merging**
