### PR TITLE
[Square] Antichamber

### PR DESCRIPTION
**Pull request by mrmeszaros**
Cleaned up the circle icon, and added a Square icon based on the circle (#3732):

| Square icon |
| :-: |
| antichamber square |

### CODE REVIEW

**Review by palob — APPROVED** [review]
Ready to be merged. Thanks for fixing up the buggy icon.

**Comment by mrmeszaros** [comment]
Modified the symbol a bit (fixup of the `C`) - may I add it in this PR?

| Current | New |
|:-:|:-:|
| antichamber circle | antichamber circle |
| antichamber square | antichamber square |

**Comment by palob** [comment]
What exactly is the fixup?

**Comment by mrmeszaros** [comment]
Minor one on the gray circle:
- the positioning and size of the gap (better symmetry, alignment with the inner 'cube')
- also boldened from `2.81px` to `3px` so that it lines up more with the grid

| Old | New |
|-|-|
| antichamber circle old | antichamber circle new |

**Comment by palob** [comment]
Thanks and go ahead :)

**Pull request merged**
