### PR TITLE
Icons for Dradis

### PR DESCRIPTION
**Pull request by maxtron95**
https://github.com/dradis/dradis-ce

dradis

dradis-ci
dradis-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Could you get the symbol a bit smaller without going out of your way?
The inner surface of the bottom leg of the **A** should actually be the brighter one with the Numix source of light positioned above the icons.

The lower end of the bottom leg should look more like a square, you're free to move nodes to .5px osition for that.

**Review by Foggalong — CHANGES_REQUESTED** [review]
I'm a bit wary about making this design 3D, not least because it's going to mean really carefully picking what faces need to be what colour of green to accurately reflect the lighting we use. Is there a way this can be flattened?

**Review by palob — CHANGES_REQUESTED** [review]
Very simplistic but works. Both symbols should sit 1px higher though.

**Review by Foggalong — COMMENTED** [review]
Much happier with this design, will merge once the symbol has been raised :+1:

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
