### PR TITLE
Icons for remote-touchpad

### PR DESCRIPTION
**Pull request by palob**
https://github.com/Unrud/remote-touchpad

remote-touchpad
remote-touchpad-ci
remote-touchpad-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
This design feel s weird to me and I think it might be the mouse. Do you think it would work with just the target square?

**Comment by palob** [comment]
I don't think so. The original icon doesn't really tell what the app is all about.

Maybe something based on the libinput-gestures icon could work.

**Comment by Foggalong** [comment]
@palob Yeah I think that might work better than the cursor

**Comment by palob** [comment]
Hmm, didn't work out yet.
Maybe just symlinks to ``touchpad-indicator`` or ``input-touchpad``?

**Comment by Foggalong** [comment]
@palob Yeah if that's not working a link to input-touchpad will suffice.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
