### PR TITLE
AdVenture Capitalism.

### PR DESCRIPTION
**Pull request by W-Floyd**
iconified_steam_icon_346900

### CODE REVIEW

**Comment by W-Floyd** [comment]
Whoops, a signed commit...

**Comment by W-Floyd** [comment]
There, fixed.

**Comment by palob** [comment]
I haven't looked at it closely yet but it might be a bit detailed/fine-grained compared to existing icnons.

Can you do without the contours?

**Comment by W-Floyd** [comment]
I'll give it a shot later (tomorrow?). If memory serves, it didn't look as
good without those contures.

More to the point, should I try to see if I can make it without an outline
at all?

**Comment by W-Floyd** [comment]
*sigh* Another signed commit...

**Comment by W-Floyd** [comment]
Okay, how's this?
iconified_steam_icon_346900

**Comment by palob** [comment]
It still looks un-Numixy. What sets it apart from existing icons is the contours, the irregular shapes and the non-isometric perspective.

**Comment by W-Floyd** [comment]
Hmm. Any ideas? I might be a while coming up with anything :P

**Comment by palob** [comment]
Just a simpler representation of moneybags.

**Comment by W-Floyd** [comment]
iconified_steam_icon_346900

Alignment should be okay.
image

**Comment by palob** [comment]
It's OK now, recognisable at smaller sizes but maybe the bag could be slightly bigger and the dollar sign could be a bit more prominent?

**Comment by W-Floyd** [comment]
Sure. Hopefully I can have a go at that later today.

**Comment by W-Floyd** [comment]
Now much... wealthier :P
iconified_steam_icon_346900

**Comment by palob** [comment]
Aye! Maybe a bolder dollar sign?

Will be off-centre with a 2px stroke though.

**Comment by W-Floyd** [comment]
Sure.

**Comment by W-Floyd** [comment]
Darker?
iconified_steam_icon_346900

**Comment by palob** [comment]
Yeah, maybe a darker/less saturated bag too for better contrast with the baseplate?

**Comment by W-Floyd** [comment]
iconified_steam_icon_346900

**Pull request merged**
