### PR TITLE
gnome-appfolder-manager square icon

### PR DESCRIPTION
**Pull request by mymindstorm**
Comparison
Converted to square icon

### CODE REVIEW

**Comment by palob** [comment]
Well, maybe the icons on top of the icons should be Square icons too?

**Comment by mymindstorm** [comment]
I think I did the gradient wrong on this one too

**Comment by mymindstorm** [comment]
Shoot I put the commit message wrong too

**Comment by mymindstorm** [comment]
@palob how does that look?

**Comment by mymindstorm** [comment]
image

**Comment by palob** [comment]
That's rad, thanks.

**Review by palob — APPROVED** [review]

**Pull request merged**
