### PR TITLE
Icons for Pioneer

### PR DESCRIPTION
**Pull request by palob**
https://github.com/pioneerspacesim/pioneer

pioneer
pioneer-ci
pioneer-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
Lost the planet on this one I think, doesn't quite gel with the rest of the icons

**Comment by palob** [comment]
Maybe without the stars? Or better even without the planet in the background?

**Comment by Foggalong** [comment]
It's just the planet for me, I think the stars are fine

**Comment by palob** [comment]
pioneer-ci
pioneer-sq

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
