### PR TITLE
Icons for AVI MetaEdit

### PR DESCRIPTION
**Pull request by maxtron95**
https://mediaarea.net/AVIMetaEdit

(Yes, that is literally the original icon.)
net mediaarea AVIMetaEdit

avimetaedit-ci
avimetaedit-sq

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Comment by Foggalong** [comment]
> (Yes, that is literally the original icon.)

This is disgraceful. A prime example both of why the argument "icon themes encroach on developer branding" is invalid; it presupposes that developers always put thought into their icon design which as we've seen time and time again isn't the case.

**Comment by maxtron95** [comment]
@Foggalong I apologize for being rude, I was reckless with that comment. If it was directed at me.

**Comment by Foggalong** [comment]
@creepertron95 No not at all! I meant the original icon was disgraceful, you've done _absolutely_ nothing wrong :smile:

**Comment by maxtron95** [comment]
@Foggalong Oh ok, I see what you mean, On the topic of this icon, as I saw what good icon design looks like, Why would they choose the National Archives logo as their icon? It doesn't even hint at what the app is supposed to do.

**Comment by Foggalong** [comment]
Honestly no idea - it's an app for verifying/editing meta data from the archive footage, but even then it's not a great link

**Pull request merged**
