### PR TITLE
Icons for OSM Scout Server

### PR DESCRIPTION
**Pull request by palob**
https://github.com/rinigus/osmscout-server

Contender for the worst icon in existance
harbour-osmscout-server
harbour-osmscout-server-ci
harbour-osmscout-server-sq

### CODE REVIEW

**Review by Foggalong — COMMENTED** [review]
I'm holding this one until we've come up with a  simplified world map (as part of #5153) to use for icons like this where it makes more sense to have a real globe rather than a fictional one.

**Comment by Foggalong** [comment]
@palob I'm using :label: wontfixto as a proxy for it being "on hold", it's not saying that this won't be merged at some point :slightly_smiling_face:

**Comment by palob** [comment]
The wire globe doesn't seem to work that well here.
osmscout-server

**Comment by palob** [comment]
Might work with lines on a circle or the Epiphany style.

**Comment by palob** [comment]
Since this is about map tiles, why not something with tiles?
I'm not fond of this particular draft though.
osmscout-server-tiles

Didn't come up with a good metaphor yet.

**Comment by Foggalong** [comment]
That's a decent shout yeah! Would increasing the size of each tile work (say a 4x4 grid rather than 5x5)

**Comment by palob** [comment]
That's a good idea but will need more experimenting to get a even distribution of tiles / centered symbol.

**Comment by palob** [comment]
Do you think this is any good, @Foggalong? I'm still not sure.
osmscout-server

**Comment by palob** [comment]
Solid-colour tiles or this one. 
osmscout-server

**Pull request merged**
