### PR TITLE
Added Brave Dev icons (updated) w/ symlink

### PR DESCRIPTION
**Pull request by KBeDevel**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
One small thing: The baseplate should only be 10L lighter at the top. Currently it is 20L.

**Comment by KBeDeveloper** [comment]
Fixed

**Comment by KBeDevel** [comment]
Fixed

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]
Really well done on this! :smiley:

**Pull request merged**
