### PR TITLE
distributor-logo-msdos - MS-DOS icons and entry.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #2183

MS-DOS has no set logo per se, so the branding from the disk cover has been used as inspiration.

iconified_distributor-logo-msdos

I won't tell you how long it took to get the overlap and shadows looking good :laughing:

### CODE REVIEW

**Comment by palob** [comment]
Baseplate could be a tad darker, letters a tad brighter for better contrast.

**Comment by W-Floyd** [comment]
Too much?
iconified_distributor-logo-msdos

**Review by palob — COMMENTED** [review]
It appears the yellow **S** still stands out a bit against the DO which could be even lighter. Or is it just my eyes?

**Comment by W-Floyd** [comment]
I think you're right, especially at smaller sizes. I'm fiddling around, finding it hard to come out with anything I like.

How about 
image
image

**Comment by W-Floyd** [comment]
iconified_distributor-logo-msdos

**Review by palob — APPROVED** [review]

**Comment by W-Floyd** [comment]
Maybe try the old

**Comment by W-Floyd** [comment]
Whoops

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
