### PR TITLE
Icon for Owlboy (Steam)

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon |
| :--: | :--: | :--: |
| original owlboy | owlboy circle | owlboy square |

### CODE REVIEW

**Comment by palob** [comment]
Symbol ic ace but can you try to recreate the eyes the following way for some extra crispness (don't know if it makes that much of a difference).

circles
10x10 circle and 8.5x8.5 circle, both aligned to the grid.

**Comment by mrmeszaros** [comment]
| | Circle | Square |
|-|:-:|:-:|
| New | owlboy circle | owlboy square |
| Old | owlboy circle | owlboy square |

I think I like the new one more.

**Review by palob — CHANGES_REQUESTED** [review]
Just a small thing, can you please merge all shadow paths into a single one?

**Comment by mrmeszaros** [comment]
Yeah, right forgot it :)

**Review by palob — APPROVED** [review]

**Pull request merged**
