### PR TITLE
Icons for Ultratron

### PR DESCRIPTION
**Pull request by maxtron95**
https://store.steampowered.com/app/219190/

ultraatron

ultratron-ci svg
ultratron-sq svg

### CODE REVIEW

**Review by palob — COMMENTED** [review]
That's a nice representation. Could we get the eyes stand out a bit more (brighter like in the original icon)?
Those metal surfaces? could be a bit brighter, too.

**Comment by palob** [comment]
Did you try an even extremer colour for the eyes?

**Comment by maxtron95** [comment]
Well I tried a brigher (more extreme) color as you said but I wasn't sure how bright I should make the eyes.

**Comment by palob** [comment]
I'd say even brighter, more like in the original icon if it doesn't look goofy.

**Comment by maxtron95** [comment]
This is as bright as I can make the eyes without losing the purple (probably pink at this point) coloring as in the original icon

**Review by palob — APPROVED** [review]
Doesn't quite glow like in the original icon due to single colour but I think it's closer.

**Comment by palob** [comment]
Now that I look at the colours side by side the first rendition doesn't appear that non-glowing anymore.
Waiting for the 5th and 6th eye of @Foggalong.

**Review by Foggalong — APPROVED** [review]
I think what's pushed does a good job of showing the eyes are bright without making use of any non-guideline design elements!

**Comment by Foggalong** [comment]
@palob @creepertron95 I'm slightly nervous that Travis didn't pick up on the tab use in this PR :eyes: Once all the open PRs are merged I'll do a quick check that no others have slipped through!

**Pull request merged**
