### PR TITLE
Add icon for Twilight

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon |
| --- | --- | --- |
| twilight | twilight circle 192 | twilight square 192 |

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
The design, especially in square, doesn't feel quite right. Possibly play with lowering the horizon?

**Comment by mrmeszaros** [comment]
| Current (24/23) | A (26) | B (28) |
|---|---|---|
| twilight circle 96 current | twilight circle 96 a | twilight circle 96 b |
| twilight square 96 current | twilight square 96 a | twilight square 96 b |

I think **A** is low enough, but there is **B** for comparison
(B is 2 px lower than A, so there is a step in between)

**Comment by Foggalong** [comment]
Yeah, go with A

**Comment by bilelmoussaoui** [comment]
Can you please replace the android entry with the componentInfo? 
You can get that from here http://activities.tundem.com/

In this case it's `com.urbandroid.lux/com.urbandroid.lux.MainActivity`

**Comment by mrmeszaros** [comment]
@bil-elmoussaoui Should the whole thing go, or just the part before the slash (`com.urbandroid.lux`)?
I saw other entries not having the Activity class part.

**Comment by bilelmoussaoui** [comment]
Everything should go,  I had to prepare this PR first #4063 Which implements everything for the android support except the android app.

**Comment by mrmeszaros** [comment]
@bil-elmoussaoui @Foggalong Done!
Also, I think it affects #3997 (already merged) - I did not include the whole component-info

**Comment by bilelmoussaoui** [comment]
@mrmeszaros Don't worry about the content of the data.json file; I will update it once #4063 got merged :)
As we don't use the core to generate any android themes at the moment, it's not a big problem :) we should definitely talk about the android support somewhere on the wiki and the format of the data.json file.

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
