### PR TITLE
Icons for Steam Link

### LINKED ISSUE #5706: Icon Request: Steam Link
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Steam Link`| `com.valvesoftware.SteamLink` | `com.valvesoftware.SteamLink.desktop` | original |

Description: Steam Link is a solution for extending your Steam games library to any room of the house via your home network.

Website: [About Steam Link](https://store.steampowered.com/steamlink/about/) and [Steam Link Flathub](https://flathub.org/apps/details/com.valvesoftware.SteamLink)

### PR DESCRIPTION
**Pull request by really-need-an-api-key**
Fixes #5706.

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

### CODE REVIEW

**Comment by palob** [comment]
How does this look with the controller stencilled out so that the outlines cast a shadow?

**Review by Foggalong — CHANGES_REQUESTED** [review]
I'd like to take this in the other direction: make the control dark grey and add a shadow from it onto the white circle.

**Comment by really-need-an-api-key** [comment]
@palob
square-com valvesoftware SteamLink-3

@Foggalong
square-com valvesoftware SteamLink-2

**Comment by really-need-an-api-key** [comment]
I see that the gradient range is also too big here.

square-com valvesoftware SteamLink-3
square-com valvesoftware SteamLink-2

Was 22-32, is 28-32 now.

**Comment by palob** [comment]
I agree with @Foggalong , the 2nd version looks better but the grey is too black for my taste.

**Comment by palob** [comment]
@really-need-an-api-key Are you going to finish this or are you OK with me stepping in?

All to be done is a lighter symbol (and maybe a blueish tint in case of a brownish impression).

**Comment by really-need-an-api-key** [comment]
Whew sorry, I completely forgot about this PR. I can push the changes when I get home later today, but feel free if you want to step in!

**Comment by really-need-an-api-key** [comment]
circle-steam-link
square-steam-link

Sorry for taking so long.
Made the symbol colour sit somewhat between the original blue and the dark gray.

**Review by palob — APPROVED** [review]
Thank you, no need to feel sorry!

**Pull request merged**
