### PR TITLE
Icons for Thonny

### PR DESCRIPTION
**Pull request by palob**
http://thonny.org/

thonny
thonny-ci
thonny-sq

### CODE REVIEW

**Comment by Foggalong** [comment]
Why closed? :fearful:

**Comment by palob** [comment]
Oh no, I deleted the branch thinking it was merged. Will reopen tonight.

**Review by Foggalong — CHANGES_REQUESTED** [review]
The symbol looks a touch too far to the right

**Comment by palob** [comment]
Moved it 1px to the left.

thonny-ci
thonny-sq

**Comment by Foggalong** [comment]
Somehow it thought the DB entry was in the right place first time, but not this time :confused:

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
Even weirder, it's objectively in the right place when you look at the actual DB file nor is the entry causing an error even present. Just gonna merge this, I think Travis has done goofed

**Comment by palob** [comment]
Yeah, it is confusing with master.

Some weeks ago I had a commit failing for unknown reason just to magically correct a few hours later.

**Pull request merged**
