### PR TITLE
Added Sublime Merge icons

### PR DESCRIPTION
**Pull request by KBeDevel**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Hi, thanks for contributing.

There are a few things which need to be changed.
+ Please remove the blur which isn't in line with our design guidelines and makes the icon look blurry whereas we want it to be as crisp as possible.

+ Please start with our icon templates. There you can change the baseplate gradients and add the symbol. Right now the baseplates are bigger than they should and the bezels are messed up.

+ Please save the icon as *Optimised SVG* with options as shown here https://github.com/numixproject/numix-core/wiki/Optimise-Options

+ Please make sure that all horizontal/vertical lines are aligned with the pixel grid

+ Please change the order of the symlinks in the DB file

**Comment by Foggalong** [comment]
Since @KBeDeveloper didn't seem to want to finish I took the liberty of reopening and making the adjustments. I realise it can be intimidating when a PR gets a big list of changes to make, but we're more than happy to work through them with you and help with any issues :smiley:

**Review by Foggalong — APPROVED** [review]

**Comment by KBeDevel** [comment]
Thank you @Foggalong, I'm too busy right now :man_office_worker:

**Comment by Foggalong** [comment]
@KBeDeveloper No problem, thanks for starting off this icon regardless :)

**Pull request merged**
