### PR TITLE
Icons for feathernotes

### PR DESCRIPTION
**Pull request by palob**
https://github.com/tsujan/FeatherNotes

feathernotes
feathernotes-ci
feathernotes-sq

### CODE REVIEW

**Comment by maxtron95** [comment]
@palob Perhaps we can also include an icon for Featherpad as well. (https://github.com/tsujan/FeatherPad)

**Comment by palob** [comment]
Right now it is implemented as symlink, so maybe just this icon recoloured, or the feather on top of a sheet. It is not easy to distinguish between featherpad and feathernotes.

**Review by Foggalong — APPROVED** [review]

**Comment by palob** [comment]
@creepertron95 I'll try something for featherpad next week unless you plan to do so.

**Comment by palob** [comment]
Two drafts for featherpad which I don't exuberantly like:

featherpad
feathernotes1
feathernotes2

Maybe it needs the original feather which then should be pushed to feathernotes as well.

**Pull request merged**
