### PR TITLE
Icons for 3DCoat

### PR DESCRIPTION
**Pull request by maxtron95**
https://3dcoat.com/

3dcoat

3dcoat-ci
3dcoat-sq

### CODE REVIEW

**Comment by palob** [comment]
What do you think about this simplified version (shadow of the original path for comparison)

simple

**Comment by maxtron95** [comment]
@palob Looks good. It is much better in terms of pixel alignment and uses less nodes.

**Comment by palob** [comment]
OK, I'll push it.

**Review by palob — APPROVED** [review]

**Comment by Foggalong** [comment]
Added a v. light blue background circle to round out the icon a little more but very much like the aligning of the drips, lovely touch :+1:

**Pull request merged**
