### PR TITLE
Update the Slack icon

### LINKED ISSUE #4714: Icon Request: Slack (update)
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Slack`| `slack` | `slack.desktop` | original |

Description: `Slack is a collaboration hub for work`

Website: `https://slack.com/`

Slack recently updated their Logo

### PR DESCRIPTION
**Pull request by mrmeszaros**
Here is the second draft:
updated circle slack iconupdated square slack icon

Fixes #4714

### CODE REVIEW

**Comment by mrmeszaros** [comment]
Okay a few notes:
* I used the colors from the original icon, as suggested
* However, these colors look a bit off to me - comments are welcome:
  - is it the saturation?
  - maybe a lighter baseplate?
* Also, the size looks better in my opinion, than in the first draft.

**Comment by palob** [comment]
Yeah the baseplate might indeed look better when toned down like in draft 1.
Could you try something between the original icon and draft 1 for the colours?

**Comment by mrmeszaros** [comment]
| v1 | v2 | v3 | v4 | v5 |
|---|---|---|---|---|
| `Draft 1` | `Draft 2` | `Draft 2 (+4L)` | `Draft 2 (+8L)` | `(Draft1 + Draft 2)/2` |
| slack circle-v1 | slack circle-v2 | slack circle-v3 | slack circle-v4 | slack circle-v5 |

**Comment by palob** [comment]
Seeing all alongside each other  I think v2 provides the best contrast but I like v1 and v5 as well.

**Comment by palob** [comment]
Is the current size 30x30? If you've got the time, how does it look in 28x28?

**Comment by mrmeszaros** [comment]
Yes this is 30x30.
Although I aggree that the symbol looks a bit too big this time, I am not sure if I can scale it down 2pixels and keep the proportions.

I will try nevertheless, however it may take some time, as I have a few urgent university appointments.

**Review by Foggalong — CHANGES_REQUESTED** [review]
No worries, take the time you need with it!

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
@mrmeszaros Took the liberty of finishing this; went with 26px which managed to keep the proportions and the colours from draft 1.

**Pull request merged**
