### PR TITLE
Add Turquoise Calendar

### PR DESCRIPTION
**Pull request by mueller-ma**
Add a black and a turquoise calender icon set

### CODE REVIEW

**Comment by palob** [comment]
Hi, thanks for contributing.

Alas we can't merge the icons though. I think both colour combination don't work at all. The turquoise doesn't provide enough contrast and actually looks like there was something wrong with the icon.

Can you try a darker and less saturated shade?

As for the black icons, we don't use pure black in any of our icons. Something like L40 grey is the darkest we use. Any greyish colour however won't sufficiently contrast with the small holes.

Moreover there is some strange nodes in the shadow part which need to be removed.
It's probably a buggy leftover already present in the original icons.
strange-nodes

**Comment by mueller-ma** [comment]
Hi,
Basically I want to provide an icon for https://github.com/Etar-Group/Etar-Calendar. There icon uses a grey shaddow.

**Comment by mueller-ma** [comment]
Can you give me the hex code for a suitable grey to replace the black?

**Comment by palob** [comment]
Maybe ``868686ff`` (the colour of the numbers) which however isn't that much blackish or ``505050ff`` with the holes darkened to ``2d2d2dff``. Both options don't exactly thrill me, it's grey after all.

**Comment by mueller-ma** [comment]
I have removed the black ones. If someone needs them, he/she can open an issue.
Should I squash my commits?

**Review by Foggalong — CHANGES_REQUESTED** [review]
The turquoise you've used `#00FFFF` is way too bright, even compared to the one used in the app you linked `#4FC7B7`. If we merge it as is it'll look massively out of place with the other Numix icons :confused:

**Comment by mueller-ma** [comment]
@Foggalong I changed it to 4FC7B7

**Comment by mueller-ma** [comment]
@Foggalong ping

**Review by Foggalong — CHANGES_REQUESTED** [review]
This also needs adding for Square before it can be merged.

**Comment by W-Floyd** [comment]
I can do that if you like.

**Comment by W-Floyd** [comment]
Signed commits are still bad, yeah?

**Comment by W-Floyd** [comment]
Not sure what the protocol is here, but I've PR'ed it over at https://github.com/mueller-ma/numix-core/pull/1

**Comment by Foggalong** [comment]
In this repo not great, but not the end of the world because there are already signed commits in the history. In any other repo yeah wouldn't be merged

**Comment by palob** [comment]
Because the PPA  now builds from the ``numix-icon-theme-circle`` repo now?

**Comment by mueller-ma** [comment]
Square icons are now included.

**Comment by palob** [comment]
@mueller-ma Did you do anything else than recolouring with the new icons?

**Comment by mueller-ma** [comment]
I only recolored

**Review by palob — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
The icons must be saved as optimized. There's a lot of empty/unneeded groups

**Comment by palob** [comment]
Ohh yes, how did that escape me?

**Comment by W-Floyd** [comment]
@bil-elmoussaoui @palob If that's the case, that needs to be resolved in all other recolours of the calendar set. Should I PR that first?

**Comment by palob** [comment]
That would be welcome for sure. A fix for https://github.com/numixproject/numix-core/pull/3708#issuecomment-299584324 as well :-)

**Comment by W-Floyd** [comment]
I feel like it would be easiest for me to whip all the calendar icons into shape, including turquoise and black, then PR them separately.

**Comment by W-Floyd** [comment]
Alrighty, after far too much fiddling, I've got a script that rebuilds the calendar icons, and I have verified that there is no visual change. All I need to do now is plug in the goal colours, and we're good to go.

**Comment by W-Floyd** [comment]
If #4046 goes through, this PR can be closed.

**Comment by mueller-ma** [comment]
I'll close mine. Thanks for your PR.

**Pull request closed without merging**
