### PR TITLE
Add missing Celluloid symlink

### PR DESCRIPTION
**Pull request by palob**

### CODE REVIEW

**Comment by Foggalong** [comment]
why would they do this :cry:

**Comment by bilelmoussaoui** [comment]
The first icon name is wrong, it's not a valid app-id and was probably changed before the release is out and can safely be removed

**Comment by Foggalong** [comment]
Curious, why is `io.github.Celluloid` not valid?

**Comment by palob** [comment]
It might as well have been a typo introduced by me but there are probably a lot of invalid app ids out there with Flatpaks distributed outside of Flathub.

**Comment by Foggalong** [comment]
Eh, we'll leave it in then just in case. No sense in spending time hunting down whether every icon line in the JSON is something that could still occur in the wild.

**Pull request merged**
