### PR TITLE
Icons for KawAnime

### PR DESCRIPTION
**Pull request by maxtron95**
https://github.com/Kylart/KawAnime

kawanime

kawanime-ci
kawanime-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Symbol should be shortened a bit and the person looks a bit much gothic/zombie-like/past their prime.

Much of this impression is due to the eyes.

**Comment by maxtron95** [comment]
@palob Any advice for the eyes?

**Comment by palob** [comment]
Well, they shouldn't be black(ish), have pupils/irises and more manga-like proportions.

**Comment by palob** [comment]
In general view the pen looks like a weapon, so maybe the pointy end should be on the left.
The left arm looks a bit long because the tablet thing is a bit tall.

**Comment by palob** [comment]
The zipper gap looks like a pointy chin or a beard.

**Comment by maxtron95** [comment]
Modified Icon:

kawanime-new-ci

**Review by palob — COMMENTED** [review]
Thanks, that helped a lot! Does she look sulky (->mouth) on purpose?
Could you try a baseplate with more contrast to the face?

**Comment by maxtron95** [comment]
@palob Should I try a more dark-grayish baseplate?

**Comment by palob** [comment]
If you find a shade with good contrast to the jacket. Maybe something sky blueish if that doesn't work.

**Comment by palob** [comment]
Eyes are too complicated as is.

**Pull request merged**
