### PR TITLE
Icons for aa (Android)

### PR DESCRIPTION
**Pull request by maxtron95**
https://play.google.com/store/apps/details?id=com.aa.generaladaptiveapps

aa

aa-ci
aa-sq

### CODE REVIEW

**Review by palob — DISMISSED** [review]
The **a**s look a bit askew and nedd some smoothing.
I mucked around a bit, not 100% spot-on yet.
a

**Comment by palob** [comment]
I could push this if you wish.

**Comment by maxtron95** [comment]
@palob You can go ahead and push it.

**Comment by palob** [comment]
Pushed these
aa-ci
aa-sq

**Comment by maxtron95** [comment]
@palob Thanks! Looks much nicer than what I initially designed.

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
@creepertron95 Getting fonts to look nice on icons is a tricky business, I've never been much good at it either

**Pull request merged**
