### PR TITLE
Icons for Sid Meier's Civilization VI

### PR DESCRIPTION
**Pull request by BlueManCZ**
| Original icon | Circle icon | Square icon |
| --- | --- | --- |
| ![orig][orig] | ![circ][circ] | ![sqr][sqr] |

https://steamdb.info/app/289070/

[orig]: https://user-images.githubusercontent.com/17854950/86492457-7c702d00-bd6e-11ea-89ac-7e94fcf6f885.png "Original"
[circ]: https://user-images.githubusercontent.com/17854950/86492473-85f99500-bd6e-11ea-8f1b-acece9f76240.png "Circle"
[sqr]: https://user-images.githubusercontent.com/17854950/86492598-ef79a380-bd6e-11ea-89c9-a5bd3293f5c8.png "Square"

### CODE REVIEW

**Review by palob — COMMENTED** [review]
This is technically good to go but given the games' theme the letters could use serifs.

**Comment by BlueManCZ** [comment]
Should I rework it? I wanted to make it similar to [civ5](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/sid-meiers-civilization-v.svg).

**Comment by palob** [comment]
It looks a bit bland but there's the civ5 icon. @Foggalong, what's your stance?

**Review by Foggalong — CHANGES_REQUESTED** [review]
The Civ V icons is based on the original for that version (cf #2994), so I think it'd be more appropriate to have serifs here for Civ VI. There's probably an argument to be made for adding an extra layer to the Civ V symbol too.

**Comment by BlueManCZ** [comment]
And what about this little detail? Shoud I implement it as well?

civ

**Comment by BlueManCZ** [comment]
civ2

**Comment by palob** [comment]
Serifs looking nice, I think both letters should be of the same height, looks like a mistake if not.

**Comment by BlueManCZ** [comment]
I'm also confused, why they did it like this, but it is not a mistake. They have smaller "I" on every logo or banner. :confused:

**Comment by palob** [comment]
It would make sense if the pointy end of the **V** sticked out but it is in line with the other letters...

**Comment by BlueManCZ** [comment]
According to this, it seems like this enlargement is applied to letters C, V, O and N.

civ

Should I align it?

**Comment by palob** [comment]
Yes, with only V and I. Unless it'd turn out to look goofy.

**Comment by BlueManCZ** [comment]
civ

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
