### PR TITLE
Add --theme and --platform args

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
This will allow me to build git versions for AUR package users 
capture du 2016-11-18 21-49-35
capture du 2016-11-18 21-50-38

### CODE REVIEW

**Comment by Foggalong** [comment]
If we're gonna do flags, I'd like to do flags only if no one has any objections.

**Comment by bilelmoussaoui** [comment]
You still can run the script without any flags

**Comment by Foggalong** [comment]
@bil-elmoussaoui Yeah, that's what I mean - ditch the in script prompts so that the way to build is using tags.

**Comment by bilelmoussaoui** [comment]
@Foggalong Well, i thought that keeping the prompts is good for beginners :) but i can do that if you want so :+1:

**Comment by Foggalong** [comment]
@bil-elmoussaoui I see your point, but ideally we don't want beginners building from this repo. They should be using the packaging repo

**Comment by bilelmoussaoui** [comment]
@Foggalong Done, i've also added a condition when the data.json file can not be found

**Comment by bilelmoussaoui** [comment]
I've also removed the GitPython depend form the README as we don't use it anymore, and updated the instructions, it might not be clear enough..

**Comment by Foggalong** [comment]
I get this error regardless of whether flags are used

screenshot_2016-11-23_22-44-54

**Comment by bilelmoussaoui** [comment]
I've already fixed this issue but i forgot to commit the modifications :/ Done

**Comment by Foggalong** [comment]
@bil-elmoussaoui Made some changes to fix a few small issues and then neaten things up. Any more changes to make / alterations to mine?

**Comment by bilelmoussaoui** [comment]
It seems all good for me :+1:

**Pull request merged**
