### PR TITLE
Icons for Barony

### LINKED ISSUE #5426: Icon for Barony
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Barony`| `steam_icon_371970` | `Barony.desktop` | steam_icon_371970 |

Description: `First person roguelike`

Website: http://www.baronygame.com/

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| barony original | barony circle 192 | barony square 192 |

The bottom part of the B looks off, but whatever I tried, I could not tweak it to look good.
Also not sure about the shades of color.
Help is appreciated.

Fixes #5426

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
All elements could be a tad brighter (baseplate, shield, B). Looks a bit underexposed right now.

**Comment by palob** [comment]
Is this any better for the lower B?
B
If you didn't do this already you can open the original icon in Inkscape, resize it to the desired symbol size. Then you can build the symbol using transparent paths.

**Comment by mrmeszaros** [comment]
| barony circle 192 | barony square 192 |
|:---:|:---:|
| barony circle 48 | barony square 48 |

**Comment by palob** [comment]
Do you think it looks better with a little curviness added to the center path?
inner

**Comment by mrmeszaros** [comment]
@palob good idea!
I will give it a look in the evening.

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
