### PR TITLE
Icons for subtivals

### PR DESCRIPTION
**Pull request by palob**
https://github.com/Subtivals/subtivals

subtivals
subtivals-ci
subtivals-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
That lighter outline looks a bit off for me. Maybe replacing the fingers/knuckles with separate darker or lighter overlaid shapes might work better?

**Comment by palob** [comment]
Not sure if this works well.
subtivals-2

**Review by Foggalong — CHANGES_REQUESTED** [review]
Oh god no you're right it doesn't. Maybe something involving a projector metaphor instead?

**Comment by palob** [comment]
No way....
subtivals2
Definitely needs a fresh metaphor.

**Pull request closed without merging**
