### PR TITLE
Icons for LyricsX

### LINKED ISSUE #4003: Icon Request : LyricsX
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| LyricsX | `lyricsx` | `lyricsx.desktop` | LyricsX| Numix-Square |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).
LyricsX is an editor for (LRC) lyrics. https://github.com/timxx/lyricsx

### PR DESCRIPTION
**Pull request by maxtron95**
Fixes #4003

lyricsx-ci
lyricsx-sq

(Mimetype PR here: https://github.com/numixproject/numix-icon-theme/pull/1367)

### CODE REVIEW

**Review by palob — COMMENTED** [review]
I think it looks like an icon for an educational app, there is no connection to music with this metaphor.

**Comment by maxtron95** [comment]
Thanks for the suggestion. I will make the current icon, `applications-education` instead while making an entirely new icon. @palob What do you think would be a good metaphor for this type of program?

**Comment by palob** [comment]
One which is often used is note+lines / clef+lines or a bubble with notes / a clef in it.
I'll let you know if I come up with something better.

**Comment by maxtron95** [comment]
@palob I created a new design for LyricsX.

lyricsx-new-ci

**Review by palob — CHANGES_REQUESTED** [review]
Thank you. I think the symbol on Circle can go down 1px.

**Pull request merged**
