### PR TITLE
Add android entry for Duet

### PR DESCRIPTION
**Pull request by mrmeszaros**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
@Foggalong Please don't merge this before merging my latest PR, this will cause again a merge conflicts and I don't want redo that all over again :p

**Review by palob — APPROVED** [review]

**Comment by Foggalong** [comment]
@mrmeszaros Conflicts on this need resolving

**Review by Foggalong — CHANGES_REQUESTED** [review]
@mrmeszaros Conflicts on this need resolving

**Comment by mrmeszaros** [comment]
@Foggalong I think the conflicts have been resolved

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
@bil-elmoussaoui Given that your PR still has conflicts and this one doesn't I'm going to merge this one in so that the conflicts it causes can be addressed at the same time as the others.

**Pull request merged**
