### PR TITLE
50 square icons - Round 7

### PR DESCRIPTION
**Pull request by W-Floyd**
Name | Icon
--- | ---
 | 
galois | iconified_galois
~~gambas~~ | iconified_gambas
gammaray | iconified_gammaray
ganttproject | iconified_ganttproject
gcad3d | iconified_gcad3d
gchem3d | iconified_gchem3d
gchemcalc | iconified_gchemcalc
gchempaint | iconified_gchempaint
gchemtable | iconified_gchemtable
gcleaner | iconified_gcleaner
gcrystal | iconified_gcrystal
~~gda-browser-5 0~~ | iconified_gda-browser-5 0
gda-control-center | iconified_gda-control-center
gdevelop | iconified_gdevelop
geda-gattrib | iconified_geda-gattrib
geda-gschem | iconified_geda-gschem
geda-xgsch2pcb | iconified_geda-xgsch2pcb
gemrb | iconified_gemrb
genymotion-player | iconified_genymotion-player
geppetto | iconified_geppetto
gerbv | iconified_gerbv
gerbview | iconified_gerbview
gftp | iconified_gftp
ghostwriter | iconified_ghostwriter
giada | iconified_giada
gimagereader | iconified_gimagereader
girl | iconified_girl
git-cola | iconified_git-cola
github | iconified_github
gitlab | iconified_gitlab
glabels-3 0 | iconified_glabels-3 0
glc_player | iconified_glc_player
glom | iconified_glom
gmtpicon | iconified_gmtpicon
gnash | iconified_gnash
gnome-multi-writer | iconified_gnome-multi-writer
gnome-news | iconified_gnome-news
gnome-pie | iconified_gnome-pie
gnome-taquin | iconified_gnome-taquin
gnome-twitch | iconified_gnome-twitch
gnome-twofactorauth | iconified_gnome-twofactorauth
gnome-video-arcade | iconified_gnome-video-arcade
gnormalize | iconified_gnormalize
gnujump | iconified_gnujump
gobby | iconified_gobby
godot | iconified_godot
go-for-it | iconified_go-for-it
gonvert | iconified_gonvert
goobox | iconified_goobox
google2ubuntu | iconified_google2ubuntu

### CODE REVIEW

**Comment by palob** [comment]
Maybe for Square the Gambas symbol can go 1px up.

**Comment by W-Floyd** [comment]
Looks better, yeah.
iconified_gambas

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
The shadow around the cog in the Circle version of `gda-browser-5.0.svg` has been botched

**Comment by W-Floyd** [comment]
iconified_gda-browser-5 0

**Pull request merged**
