### PR TITLE
Icons for Raven Reader

### PR DESCRIPTION
**Pull request by palob**
https://github.com/hello-efficiency-inc/raven-reader

raven-reader
raven-reader-ci
raven-reader-sq

### CODE REVIEW

**Comment by Foggalong** [comment]
This symbol reminds me a lot of the rabbit-duck illusion, but I don't think it quite works here. Is there a way to incorporate in the swoosh at the bottom like in the original?
 
250px-Kaninchen_und_Ente svg

**Review by Foggalong — CHANGES_REQUESTED** [review]
This symbol reminds me a lot of the rabbit-duck illusion, but I don't think it quite works here. Is there a way to incorporate in the swoosh at the bottom like in the original?
 
250px-Kaninchen_und_Ente svg

**Comment by palob** [comment]
Or  maybe simply the RSS icon recoloured?

**Comment by Foggalong** [comment]
@palob Yeah I'd be good with a recolour in this instance :)

**Comment by palob** [comment]
Pushed these
rss-c
rss-ci

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
