### PR TITLE
Symlinks

### PR DESCRIPTION
**Pull request by palob**

### CODE REVIEW

**Comment by palob** [comment]
While working on this KDE symlinks I noticed a few new KDE apps. It's high time I run a KDE distro again, Numix coverage is probably lacking a lot, especially in the action icons department.

**Comment by palob** [comment]
C'mon Travis, catch up!

**Comment by maxtron95** [comment]
@palob Wait, you had your own KDE Linux distro before?

**Comment by palob** [comment]
No, no, I wanted to say is that I need to go for a KDE spin again :) I haven't booted into a KDE session for like 3 years.

**Comment by palob** [comment]
Travis asleep again.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
