### PR TITLE
meshlab - Icons and entry for Meshlab.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #3971

I tried doing an eye thing too, but it really wasn't looking much chop, nor does it signify the nature of the software. As such, I think something to do with a mesh (in this case, triangulation) is more appropriate, and easier to pull off in this theme.

iconified_meshlab

### CODE REVIEW

**Comment by palob** [comment]
Does this work with this crosshair/grid background used on some icons?

**Comment by W-Floyd** [comment]
Say, that's an idea... I'll try that later.

**Comment by W-Floyd** [comment]
iconified_meshlab

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Comment by bkanuka** [comment]
Thanks for your work on this @W-Floyd ! 
I really like the icon you drew (and the idea of not using the eye), but I don't think the grid improves the design. I think it just adds noise to a theme that's otherwise pretty minimal. Plus a grid isn't even a common tool in Meshlab.

Anyway, really just glad to get this icon covered by numix - so thanks again

**Comment by W-Floyd** [comment]
Hmm, I see what you mean... @palob you still think grid, or no?

**Comment by palob** [comment]
I think it's a bit bland with just a white background. Maybe a light green background looks OK.

**Comment by Foggalong** [comment]
Yeah it definitely needs something just beyond the plain white baseplate.

**Pull request merged**
