### PR TITLE
Update README with Contributions section

### PR DESCRIPTION
**Pull request by ismaelgv**
Many people feel lost when they want to start contributing, this section could be helpful to newcomers.

This is just a draft. Feel free to make any change or correction. (I'm not a native English speaker).

### CODE REVIEW

**Comment by ChuckDaniels87** [comment]
Related to #2647

**Comment by Foggalong** [comment]
For reasons that will be made public soon we're gonna have to do a fairly big redesign of the Numix website, and when that happens weren't gonna add a dev section on the site [like elementary](https://elementary.io/developer). When that's done it'll address #2647

**Comment by mymindstorm** [comment]
Since it's been over a year since @Foggalong said this I'd like to either re-open this or make a new pull request with similar changes. I didn't even know the guidelines existed until I dug through tons of issues and pull requests in an attempt to find rules and best practices for contributing that took way longer than it should have. Even if the guidelines are horribly outdated (last edited in 2015!), a section like this would have saved me hours of research. Even if the website is still going under a redesign, a section like this should still be added until the new website is complete and be subsequently changed to direct contributors to it.

**Comment by palob** [comment]
I might have some time by the end of next week to give this a go.

**Comment by Foggalong** [comment]
Something like this should probably go in the repo wiki rather than the README since it has the potential to get quite long (accounting for different themes, exceptions to rules, etc)

**Comment by mymindstorm** [comment]
That's something different entirely, but it probably would be a good idea to move numix-wiki's wiki into the core repository. I'm mainly talking about adding a small contribution section to the readme referring people to the guidelines and possibly updating the guidelines.

**Comment by mymindstorm** [comment]
The repo that this pull request was in got deleted, so I'll open a new one later today.

**Comment by Foggalong** [comment]
Ahh, I see what you're saying now! Yeah you're right will sort that out :)

**Comment by ismaelgv** [comment]
I'm glad this is useful. 😄

**Comment by Foggalong** [comment]
I've [started the wiki](https://github.com/numixproject/numix-core/wiki) and just chucked in all the pages from the old wiki and @ChuckDaniels87's page. Things to do:
* Make sure all the information on the pages is up to date
* Consolidate duplicate information
* Bring the design guidelines up to date
* Add Square info for design guidelines

**Pull request closed without merging**
