### PR TITLE
Icon for Dibuja

### PR DESCRIPTION
**Pull request by palob**
https://launchpad.net/dibuja

dibuja
dibuja-numix

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
You don't need the lines on the pencil: try using the design below which we use elsewhere

screenshot_2017-04-12_09-09-42

You will need a background though which better contrasts with the yellow part of the pencil tip. Possibly try a light blue or purple?

**Comment by palob** [comment]
How about this?
dibuja

**Comment by Foggalong** [comment]
@palob In terms of symbol yes, but the colours don't really go together very well (specifically the muddy yellow and pink)

**Comment by palob** [comment]
2 more variants

dibuja2

**Comment by Foggalong** [comment]
Ver 0 looks good :+1:

**Comment by palob** [comment]
Pushed :+1:

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
