### PR TITLE
Icons for Synthesia (Wine application).

### PR DESCRIPTION
**Pull request by W-Floyd**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

First time pull request here, hope this is the right formatting...

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
The symlinks are created automatically using our script, so you shouldn't add them by yourself. Just add the symlinks on the data.json file and the script will handle that :+1:

**Comment by W-Floyd** [comment]
Ahh, cool. I'll fix that shortly.

**Comment by W-Floyd** [comment]
Ahh, cool. I'll fix that shortly.

On 25 May 2017 5:03 a.m., "Bilal Elmoussaoui" <notifications@github.com>
wrote:

The symlinks are created automatically using our script, so you shouldn't
add them by yourself. Just add the symlinks on the data.json file and the
script will handle that 👍

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/numixproject/numix-core/pull/3729#issuecomment-303820658>,
or mute the thread

**Comment by palob** [comment]
This has got a few things which are not in line with our guidelines. A full-baseplate design (a rule to which there are exceptions) and lots of gradients on symbol parts.
We've got an icon for Linthesia, a clone of Synthesia.

Maybe we can bend your icon into the theme anyway. Can you please get rid of all gradient on symbol parts and let the keabord begin 2px or more higher? How does it look if you just remove the grey keys such that they merge with the black background?

**Comment by W-Floyd** [comment]
lol I didn't even know there *was* a clone, so that's something :)

Yeah, I did gradients, but you're right. I'll try without, and see if I can make the keys a bit less overbearing (bump up the height), then make sure it's an optimised export from inkscape.

**Comment by W-Floyd** [comment]
This is the idea?
image

**Comment by palob** [comment]
It was but is it any recognisable?

**Comment by W-Floyd** [comment]
I think it's better than it was, but not quite right still. Not sure what I might do. I'll be busy for a week though, so this (and any other PRs) will need to wait for any changes on my end. Feel free to do what you like though :)

**Review by Foggalong — CHANGES_REQUESTED** [review]
As @palob says, this needs some design love before it can be merged.

**Comment by W-Floyd** [comment]
I'm closing this for now, will open another at some point that symlinks from vmpk.

**Pull request closed without merging**
