### PR TITLE
Add icon for Leap Day

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|leap-day original|leap-day circle 192|leap-day square 192|

* the game features a new level every day with trophies
* based on the numix calendar icons

### CODE REVIEW

**Comment by palob** [comment]
I'm not sure the calendar metaphor tells. Maybe just the cup on a blue background or something which represents "leap"?

**Review by Foggalong — CHANGES_REQUESTED** [review]
Agreed, the design on this doesn't really work.

**Comment by mrmeszaros** [comment]
Changed to a blue background, added a _fruit crown_ on top:
leap-day circle 192 dleap-day square 192 d

**Comment by palob** [comment]
Love this, maybe a slightly darker blue + slightly lighter yellow for enhanced contrast?

**Comment by mrmeszaros** [comment]
Could not decide myself, so here are some viable options:

| Current (D) | Darker blue + lighter yellow (E) | Darker blue (F) | Even darker (G) | Darkest (H) |
| :--: | :--: | :--: | :--: | :--: |
| leap-day circle 192 d | leap-day circle 192 e | leap-day circle 192 f | leap-day circle 192 g | leap-day circle 192 h |

I'll be honest - I do not really like the lighter yellow symbol - I would go **G**.

**Comment by palob** [comment]
OK, go with G.

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
