### PR TITLE
[Square] FeedReader

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Another one from #3481 
feedreader
I feel like the logo must be shifted 1px to the left (or more?)

### CODE REVIEW

**Comment by palob** [comment]
Definitely. It probably wasn't centered in Circle in order to counter an off-centre illusion.

**Comment by palob** [comment]
Needs a gradient. You can simply take the baseplate of an existing Square icon and edit the gradient stop colours such that it's in line with the relative Circle icon and slap icon+shadow on it.

Here's how to get the gradient stop colours from an Circle icon you want to port over to Square:
stop2
stop1

**Comment by bilelmoussaoui** [comment]
@palob Thank you ! honestly i didn't knew how to do that; and was looking on other icons how to copy the linear gradient! thanks for the tutorial

**Comment by bilelmoussaoui** [comment]
@palob I've added the linear gradient :) I will do the same for the rest of the icons

**Review by palob — CHANGES_REQUESTED** [review]
gradient needs to be reversed as well.

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
