### PR TITLE
Square icon CS:GO

### PR DESCRIPTION
**Pull request by W-Floyd**
iconified_steam_icon_730

### CODE REVIEW

**Comment by palob** [comment]
Will review later. You don't need to put the original icon in the description for Circle -> Square ports :)

**Comment by W-Floyd** [comment]
Okay, I'll exclude that from now on. Was a quick script I knocked together, so that was my default :)

Edit: Got it in my script now so I can exclude any combination of icons, so I'll be okay now.

**Comment by palob** [comment]
I think symbol+shadow might go 1px down here.

**Comment by W-Floyd** [comment]
Sure.

**Comment by W-Floyd** [comment]
iconified_steam_icon_730

**Review by palob — APPROVED** [review]

**Pull request merged**
