### PR TITLE
Icons for Avorion

### PR DESCRIPTION
**Pull request by maxtron95**
https://store.steampowered.com/app/445220/

avorion

avorion-ci svg
avorion-sq svg

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Symbol looks a bit tall. Could we get it down to a height of 22px by reducing the 2 5px high yellowish things down to 4px (in the original artwork the spotlight seem to be of uniforme height)?

Could we get the A body abit more brownish (brutalist concrete with patina) like in the original artwork?

**Comment by maxtron95** [comment]
What does `brutalist concrete with patina` look like?

**Comment by palob** [comment]
The original icon does look like it but it's probably no concrete given it is a starship.

**Comment by palob** [comment]
This was which came into my mind
https://sovietmodernism.com/
https://gdb.rferl.org/663B677E-CD9E-4AF2-985D-3716527526F0_w1200_r1.jpg
https://live.staticflickr.com/883/42958613471_a7552504ea_b.jpg
https://media1.faz.net/ppmedia/2507909806/1.6491659/media_in_article_large_original/der-genex-tower-in-belgrad.jpg

**Comment by palob** [comment]
Maybe it's supposed to be Titanium which isn't perfectly silver/grey but has a slight orange-brownish tint to it.

**Review by palob — APPROVED** [review]
Thank you.

**Pull request merged**
