### PR TITLE
Update Firefox icon

### PR DESCRIPTION
**Pull request by pieterdd**
The last iteration of this Numix icon dates from 2016, so given the design changes to Firefox' branding over the last few years I thought I'd tweak this one a bit.

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| firefox |  firefox-new8 | _I will make this one when the circle version requires no further changes_ |

Here's a first iteration. I'm not sure why I'm seeing some downsampling artifacts in my PNG render. GitHub's rich diff of the modified SVG looks normal to me.

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I'd wager the artefacts are because you've overly optimized the source down to a single line, rather than just as an optimized SVG file. See the wiki page on SVG optimization for the appropriate settings to use.

Design wise, I think we're gonna take the logo redesign opportunity to change this to a symbol design (i.e. have the fox and globe centred on the baseplate) rather than a full baseplate design as it is currently. This will keep the design more consistent with how it looks elsewhere in Numix but also will let us add some more details (e.g. smaller globe, tufts of hair sticking out, etc). You're welcome to make a move toward doing that in this PR if you'd like, but also no pressure to - across the multiple designs in Circle, Square I realise it's a bigger job than you might originally have thought.

**Comment by pieterdd** [comment]
Something among [these lines](https://github.com/numixproject/numix-core/pull/5597/files?short_path=24283ae#diff-24283ae03a2ccfebb121e90176e6921f)?

test4-optimized

**Comment by maxtron95** [comment]
Issue #4998

**Comment by pieterdd** [comment]
Okay. So should it be https://github.com/numixproject/numix-core/issues/4998#issuecomment-604796398 except with a shadow of the fox onto the marble?

**Comment by palob** [comment]
Yes, you can start from the latest state in that issue.

**Comment by pieterdd** [comment]
Alright, here we go:

firefox-ci-inkscaperender firefox-sq-inkscaperender

**Comment by pieterdd** [comment]
Just noticed that the export left some unnecessary metadata in the SVGs (like the original filename) for the circle file. I probably hit Save again after already having written the Optimized SVG version, nothing big.

**Comment by pieterdd** [comment]
Fixed.

**Review by palob — CHANGES_REQUESTED** [review]
Thank you for your effort.

The outer shape should be exactly like a 30px X 30px circle located at.
Here you can see such circle as transparent overlay, there is a slight difference in the right bottom part.
outershape

In the right tail part the shape could be a bit more true to the original icon, right now it looks a bit askew.
You can use the original icon as a stencil. Open it in Inkscape, resize it to the size of the symbol and try to replicate it with transparent vector path on top of it.

shape

Generally speaking, the symbol colours are significantly too saturated and dark and I'd love to see that purplish bottom colour from the original icon incorporated.

The icon baseplate could be a bit less saturated and darker.

In the snout area alignment to the pixel grid isn't optimal. Could you please change it to something like this
snout
and retract the path below it (made the snout path transparent for illustration purposes) in order to avoid outlines?

**Comment by pieterdd** [comment]
Would you perhaps be willing to amend these changes to the commit yourself? I think you're the most qualified person to get it to look exactly the way you want, and it's probably faster than coaching me to execute your vision. I have enabled the 'Allow edits by maintainers' option.

Regardless, thanks for the insight into your creative process.

**Comment by palob** [comment]
Alright, I can take care of this, I'm a bit pressed for time at the moment though.

**Comment by pieterdd** [comment]
No worries, it's not urgent. When you do, feel free to add yourself as a co-author to the commit if you'd like to be credited.

**Comment by palob** [comment]
I'm working on this, might be ready this week.

**Comment by palob** [comment]
This is the current state. Inserted two extra path so the colour clashes aren't that hard without gradients. Colours and one or two curvatures might need tweaking, maybe the extra tail path isn't needed.

firefox-ci

**Comment by palob** [comment]
Here's what it looks like with a gradient on the globe.
firefox-gradient

**Comment by maxtron95** [comment]
Wow, the new icon is way better than what I had proposed before.

**Comment by palob** [comment]
Pushed these (w/o globe gradient)
firefox-ci
firefox-sq

**Comment by palob** [comment]
If this is approved of I will redo the others (aurora, beta,...) as well.

**Comment by pieterdd** [comment]
Well, you certainly have my vote 😉 If you guys have a strong opinion about keeping the commit history clean, I suppose we could squash both commits into one now. Let me know if you'd like me to step in for that.

Either way, I'm happy to see that an updated Firefox icon is bound to arrive on my computer sometime soon!

**Comment by pieterdd** [comment]
What's the next step towards shipping a nice new Firefox icon? Are there still any changes needed?

**Comment by palob** [comment]
Waiting for a review from @Foggalong, merging a few more PRs and tagging new releases for Circle/Square.

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
Great work both! Updated the four non-branded accounts to use this style too, but if anyone wants to weak them further go for it; I just riffed on the colour scheme each was using before.

**Comment by palob** [comment]
Hats off for the recolours! I can look into this again, the upstream colour schemes might have changed.

**Comment by dvorapa** [comment]
Oh my god, this was merged one hour after the last release of numix-icon-theme-circle was published. What a miss!

**Comment by Foggalong** [comment]
@dvorapa If you means the PPA/AUR/other community repo then don't worry, the next release (shortly!) will contain this!

**Comment by msevilla00** [comment]
@dvorapa I've just upgraded my system (Ubuntu 20.04) and I got the new icon. Cheers!

**Comment by Foggalong** [comment]
No problem at all!

**Comment by dvorapa** [comment]
I know, I just noticed how unlucky coincidence it was, as I'm waiting for a design update of this particular icon for a while now :D Anyway I really don't mind waiting for good stuff and have to say this icon pack is my all time favourite since I first installed Apricity Linux in 2015 I think!

**Pull request merged**
