### PR TITLE
add icon entry existence verification

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
This test adds a verification to whether the icon has an entry in the database file

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
The test fails because of those missing icons entry in the database
```
 The icon highlight doesn't have any entry in the database 
 The icon cs-desktop doesn't have any entry in the database 
 The icon monogame doesn't have any entry in the database 
 The icon distributor-logo-void doesn't have any entry in the database 
 The icon rcps3 doesn't have any entry in the database 
```

**Comment by Foggalong** [comment]
@bil-elmoussaoui Can you make a pr to fix these?

**Comment by bilelmoussaoui** [comment]
In the same PR or a new one?

**Comment by Foggalong** [comment]
In the same PR is fine since it directly relates to this issue

**Comment by bilelmoussaoui** [comment]
@Foggalong I have fixed both tests on the same, are they're somehow related :)

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
