### PR TITLE
Second Part of Android

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
This PR will be merged with `android` branch.
The PR includes:
- Renaming a lot of files to better names
- Remove few duplicated icons
- Add few entries to data.json
- Optimize few icons using Inkscape (no design changed!!)

### CODE REVIEW

**Comment by W-Floyd** [comment]
As a heads up, I'm currently basing my work for the Android circle cleanup and square port on this branch, since it seems to have the most up to date icon names and some cleanup work already done. Once this is merged, I'll clean up my history (most likely re-commit) and PR on the main android branch.

**Comment by bilelmoussaoui** [comment]
Perfect 👍

**Comment by mrmeszaros** [comment]
@W-Floyd @bil-elmoussaoui  @Foggalong 
I would also gladly allocate some of my time, to make the android pack up-to-date.

I think we could have a common repo / branch, on which we all can collaborate (to avoid duplicate work).

**Comment by bilelmoussaoui** [comment]
I think the best is to work on a fork and avoid creating huge PR; with max 2 icons so we can verify and merge them easily; to avoid a huge conflicting files list

**Comment by W-Floyd** [comment]
That sounds okay, we'll just need to claim blocks of icons beforehand, so we don't redo each other's work.

**Comment by mrmeszaros** [comment]
@W-Floyd do we have a list (eg. in a GitHub issue) from which we choose?

@bil-elmoussaoui Where should the PR go? `master`? `android`? `android-2`?

**Comment by bilelmoussaoui** [comment]
You can push to master directly ;) with just one icon and the icon entry in the data.json

**Comment by W-Floyd** [comment]
I'll be honest, I'm working my way through these icons, and I'm not liking the idea of making 80+ PRs just to get these in. How about max 10 per PR? That sets us around 17 different batches.

Also, to double check, aren't all the data entries for these already entered?

**Comment by bilelmoussaoui** [comment]
I think that you can make it to 10 icons per PR if you have a lot of icons ready :)
The data entries are not yet in the data.json file; they must be added too

**Comment by W-Floyd** [comment]
I've got 25 or so done, but I need to go back and double check all the data
entries.

**Pull request closed without merging**
