### PR TITLE
Add icon for Budapest Public Transit

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon |
| --- | --- | --- |
| hu_donmade_menetrend_budapest_hu_donmade_menetrend_gui_bootstrapactivity | menetrend circle 192 | menetrend square 192 |

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Can you use a better root icon name? something like budapest-public-transit? this will allow us to find the icon easily :)
Thanks!

**Comment by mrmeszaros** [comment]
@bil-elmoussaoui The travis CI build is failing, because this is an android only icon - how could we fix it?

**Comment by bilelmoussaoui** [comment]
@mrmeszaros it's not a problem, i have to fix the tests later as it's our android only icon

**Comment by Foggalong** [comment]
@bil-elmoussaoui Any update on fixing the tests?

**Comment by bilelmoussaoui** [comment]
I will provide a PR as soon as possible! but if the icon is okay, it can be already merged :)

**Comment by bilelmoussaoui** [comment]
Provided a fix on a new PR

**Comment by mrmeszaros** [comment]
@Foggalong any changes needed for the symbol?

**Review by Foggalong — APPROVED** [review]

**Comment by palob** [comment]
So is this the first Android icon in core?
By the way, has anybody used Anbox so far? Does it set up launchers for Android apps?

**Comment by bilelmoussaoui** [comment]
@palob Yeah it's first Android-only icon. And i tried to use anbox on Archlinux, but never managed to run it :'(

**Comment by mrmeszaros** [comment]
I am putting Anbox on my todo list.
@bil-elmoussaoui am I able to build the android theme (to test it on my device)?

**Comment by bilelmoussaoui** [comment]
@mrmeszaros you can build the theme, but we still need to update the android application so it can use the icons generated by numix-core. We will definitely work on that once there's a bit more android icons

**Pull request merged**
