### PR TITLE
Icons for This War of Mine

### LINKED ISSUE #2345: Icon for "This War of Mine" (Steam)
Game: This War of Mine
AppID: 282070
Icon: http://www.loadthegame.com/wp-content/uploads/2014/11/This_war_of_mine_header-620x330.jpg

Though the text might be to boring for a designer to work with. There was no icon in the steam folder, so I just found a picture with the text and a bit of enviorment on.

Notes: It's a game about surviving in the war. You control a few charracters in a abandoned and ruined house and you have to make sure to keep them alive by gathering and crafting.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/22818026-icon-for-this-war-of-mine-steam?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by maxtron95**
Fixes #2345

This_war_of_mine_header-620x330

this-war-of-mine-ci svg
this-war-of-mine-sq svg

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Icons are fine as is (well, actually the baseplate gradients should span 10L instead of 11L)
but the db entry should come after ``themonospot``.

**Comment by palob** [comment]
Sorry for not catching it earlier. How does the Square icon look with the symbol moved 1 px to the left?

**Review by palob — COMMENTED** [review]
Yeah, looks more centered. Now would that even help the Circle icon?

**Comment by maxtron95** [comment]
They both look centered when looking at them side to side.

**Comment by palob** [comment]
Right now or with the symbol on Circle moved?

**Comment by maxtron95** [comment]
I meant right now.

**Review by palob — APPROVED** [review]
Alright, so be it.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
