### PR TITLE
Icon for Semaphor

### PR DESCRIPTION
**Pull request by gregorydk**
Icon for Semaphor

https://spideroak.com/solutions/semaphor

### CODE REVIEW

**Comment by palob** [comment]
Is that triangle thing the icon?

**Comment by palob** [comment]
It looks a bit bland/hard to distinguish on smaller sizes with those light colours on a white background.
How about darker symbol colours and something like this as background colour (found it follwing your link):
semaphor

**Comment by gregorydk** [comment]
Current icon
semaphor

Collection of icons
nzanf42

I also want to change the Encryptr and ONE icon to be consistent with the Semaphor one.

**Comment by palob** [comment]
Yeah, maybe here could work a two-colour gradient for the baseplate.

**Comment by palob** [comment]
Can you please add the ``data.json`` entry for the new icon as well as the square icon?

On the Square icon symbol+shadow need to go 1px up and the shadow one more px to the left.

**Comment by bilelmoussaoui** [comment]
@gregorydk can you rebase this on master? As i see your latest commits includes some old commits that we've already merged to master :)

**Comment by palob** [comment]
Symbol design is fine but you've put the square icon into a wrong place. In contrast to how it looks in the GitHub preview the icon looks like this for me locally which is lacking in contrast:

semaphor

I'm not sure on the colours. We could go with the following schemes for the entire "app suite":

+ 2-colour gradient (colours from logos [here](https://github.com/numixproject/numix-core/pull/3530#issuecomment-268962039)) + white or black symbol

+ baseplate using major colour from screenshot linked above + bigger symbol part white or black and smaller symbol part using the minor colour from above

+ adopting symbol colours from screenshot + baseplate using the same H, higher L / lower S

**Comment by gregorydk** [comment]
Preview is wrong, you have to open it in Inkscape to see the correct colour. Don't know why this happens.

**Comment by palob** [comment]
Well, that's the way it will show up for users. It's the long-standing Inkscape/librsvg/QtSVG gradient bugs again I think. All you can do is taking a fresh baseplate from another icon an pasting the symbol.

**Comment by gregorydk** [comment]
Well, when I took baseplate from another icon the bug didn't disappear. But saving it as an optimized svg instead of an Inkscape svg fixed it. I hope everything is okay now.

**Comment by palob** [comment]
Yep, looks like the preview now. 

The colours are somewhat along the lines of the second scheme I posted above. Could you change the grey part into something cyanish/blueish?

Does this colouring scheme translate to the other icons of the "suite" (which I'll gladly merge if you do them - even though I really like your current Encryptr icon)?

**Comment by palob** [comment]
Another thing, it's better to merge the triangular paths, otherwise the edges can be visible (bug or feature?):
merge

**Review by palob — COMMENTED** [review]
Yes, it's more lively now and you can apply the design to the other icons. Do you still plan on making them?

**Comment by gregorydk** [comment]
@palob Of course I plan to make them.

**Comment by palob** [comment]
@Foggalong If you're OK with the colour scheme chosen I think the icon is OK.

**Comment by Foggalong** [comment]
Yeah, the colours are fine with me. :+1:

**Comment by palob** [comment]
@gregorydk The diff of ``data.json`` still shows changes it shouldn't. Can you pull again from Numix master?

**Comment by palob** [comment]
Thanks!

**Pull request merged**
