### PR TITLE
Add square icon for Avocode

### PR DESCRIPTION
**Pull request by heyhippari**
Part of numixproject/numix-core#3481

Edit: I saved it as Optimized SVG in Inkscape, but it seems that it left some. Should I fix it ?

### CODE REVIEW

**Comment by palob** [comment]
Thanks for contrubuting again :+1: 
The icon is all fine however I am not sure we can merge verified commits due to a launchpad bug.

@Foggalong @wa4557 @bil-elmoussaoui Didn't Numix base run into PPA issues because of verified commits?

**Comment by heyhippari** [comment]
Oh, if that's an issue, then I can refork and commit again, signing them is just a habit that I took :)

**Comment by palob** [comment]
It's probably best to do this prophylactically, fixing it was a real pain. Thanks again.

**Comment by andia89** [comment]
Yes no commits that are signed, launchpad can't import signed commits from git. 

On a sidenote: I hope to be around more often soon, work (mainly) is keeping me a busy atm

**Pull request closed without merging**
