### PR TITLE
Add icons and entry for preferences-desktop-filetype-association

### PR DESCRIPTION
**Pull request by W-Floyd**
#2294

iconified_preferences-desktop-filetype-association

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Quite fine-grained but I think it works out.

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
Those individual components feel to small to me. Maybe the two files side by side with the arrow between them?

**Comment by palob** [comment]
Or the cog on top of the sheet?

**Comment by W-Floyd** [comment]
Cog on sheet looks pretty good imo.

iconified_preferences-desktop-filetype-association

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
