### PR TITLE
Icon for Radium (Steam)

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon | Issue |
| --- | :-: | :-: | :-: |
|  original |  radium circle | radium square | #3705 |

Created from the `WormsReloaded.svg` icon.

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Why did you opt for a smaller symbol size on the Square icon? It's misaligned and needs to be changed.

The colours are true to the original but I think a variant with more vibrant colours is worth a try.

**Comment by palob** [comment]
Ah, I see what's the deal. I've fixed the Worms Circle icon some time ago. The Square icon still has got the old design

**Comment by mrmeszaros** [comment]
How about these colours?

| Circle icon | Square icon |
| :-: | :-: |
| radium circle | radium square |

**Review by palob — APPROVED** [review]
Thanks for the fixes. Colours play nicely here but generally S255 is to be taken with a grain of salt.

**Comment by mrmeszaros** [comment]
@palob Should I lower the saturation level a bit then?

| Current | Option A | Option B |
| --: | --: | --: |
| `#008811` | `#118804` | `#088008` |
| `hsl(128, 100%, 27%)` | `hsl(114, 94%, 27%)` | `hsl(120, 88%, 27%)` |

(I think B is slightly better)

**Comment by palob** [comment]
No need to worry :) As I said I think it's fine here. If you lower the S I'd say crank up the L a bit.
But I can't really judge without seeing it in the icon.

**Comment by mrmeszaros** [comment]
Cranked L a bit, made some png-s for comparison:

| Current | Tweaked |
| :-: | :-: |
| `hsl(128, 100%, 27%)` | `hsl(120, 88%, 30%)` |
| radium circle 008811 | radium circle 099009 |

**Comment by palob** [comment]
Yeah, tweaked one is even better :+1:

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
screenshot_2017-05-17_21-44-36
 Move the symbol and shadow in Square down 1px. It's only a small change but makes it look more aligned I think?

**Comment by mrmeszaros** [comment]
Hi @Foggalong!
I created a comparison in different sizes. B looks slightly better, but it would violate the paradigm (yet slightly again) of the square icons being `1px` up.

I do not know how common it (violating the style) is, so please decide instead of me :slightly_smiling_face:

| Size | A | B |
|:-:|:-:|:-:|
| 16 | radium square 16 a | radium square 16 b |
| 24 | radium square 24 a | radium square 24 b |
| 48 | radium square 48 a | radium square 48 b |

**Comment by palob** [comment]
B :+1:

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
