### PR TITLE
Icon for Variety Slideshow

### PR DESCRIPTION
**Pull request by gregorydk**
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2892

### CODE REVIEW

**Comment by palob** [comment]
Maybe without the mountain silhouette for better scalability?

**Comment by gregorydk** [comment]
It's probably better to not change the main icon `variety.svg` for consistency.

**Comment by palob** [comment]
Can you strip a 1px outline around the arrow from the mountain path?

I think the arrow could be set apart a bit more.

**Comment by Foggalong** [comment]
I think it's more the colour that's the problem than the mountain being around the arrow. Try experimenting with some different colours and having the arrows shadow above the mountain.

Also, it needs moving a pixel or two to the right to counteract the triangle illusion.

**Comment by Foggalong** [comment]
I'm still not sold on the design. It just looks a bit off.

**Comment by Foggalong** [comment]
Merging this, but will probably change the design at some point.

**Pull request merged**
