### PR TITLE
Xfce symlinks

### LINKED ISSUE #5623: New xfce4-screensaver icon name.
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `xfce4-screensaver`| `org.xfce.ScreenSaver` | `xfce4-screensaver-preferences.desktop` | original |

Description: `Screensaver application for Xfce Desktop`

Website: `https://xfce.org`

Version 0.1.11 uses new icons with rDNS icon name: org.xfce.ScreenSaver

### PR DESCRIPTION
**Pull request by palob**
Fixes #5623

### CODE REVIEW

**Comment by palob** [comment]
There are a few more ``org.xfce.panel.[something]`` icon names but I'm not sure yet whether or not those are supposed to be app icons.
```
org.xfce.panel.actions
org.xfce.panel.applicationsmenu
org.xfce.panel.clock
org.xfce.panel.directorymenu
org.xfce.panel.launcher
org.xfce.panel.pager
org.xfce.panel.separator
org.xfce.panel.showdesktop
org.xfce.panel.statustray
org.xfce.panel.tasklist
org.xfce.panel.windowmenu
```

**Comment by meganukebmp** [comment]
Very much needed commit. Here's some of the icons that appear in the icon picker under the org.xfce namespace. 
image

**Comment by palob** [comment]
Could you please tell me where the ``org.xfce.panel.*`` icons are shown? Are those app icons or panel icons?

**Comment by meganukebmp** [comment]
> Could you please tell me where the `org.xfce.panel.*` icons are shown? Are those app icons or panel icons?

Those seem to be panel/applet icons, yes.

**Comment by palob** [comment]
Thank you, this means they should not be added here but in Numix base.

**Comment by fish47** [comment]
https://github.com/vinceliuice/Qogir-icon-theme/issues/46
------------
some icon theme repos have adapted to xfce4 icons renaming.

https://wiki.xfce.org/releng/4.16/icons_rdns_naming_for_icons
------------
maybe the full list of renaming?

**Comment by palob** [comment]
Thank you for the hint to the Xfce wiki, will check this.

**Comment by meganukebmp** [comment]
> Could you please tell me where the `org.xfce.panel.*` icons are shown? Are those app icons or panel icons?

I'm very sorry, seems I have misinformed you. The icons appear in the panel applet list (tho some also seem to appear in the panel itself). Examples attached

image

Here's the "show desktop" icon also being repeated in the panel itself.
image

**Comment by palob** [comment]
I think if the icons are shown inside the panel they should not be designed as app (Circle/Square) icons. Hopefully this won't lead to a mix of styles (Numix base icons and Circle/Square icons) in the panel applet list.

**Comment by meganukebmp** [comment]
> I think if the icons are shown inside the panel they should not be designed as app (Circle/Square) icons. Hopefully this won't lead to a mix of styles (Numix base icons and Circle/Square icons) in the panel applet list.

Ultimately this is something to discuss with the applet and xfce panel developers. Not much we can do here other than make a decision. Some applets share an icon with their configuration utility (which has a styled icon) and display that icon in the panel also. Some of the icons in the applet list screenshot above are also used inside the application in some "header" type element, so styling it would make sense.

In my opinion having those be styled is fine, as developers are discouraged to be using app icons in the panel unless it's a launcher or something else. We cant solve for every bad implementation.


@fish47 linked an official list of renamed icons:
> some icon theme repos have adapted to xfce4 icons renaming.
> 
> ## https://wiki.xfce.org/releng/4.16/icons_rdns_naming_for_icons

I think this should be the first (and possibly immediate) course of action for the time being as it's guaranteed to return us back to the same functionality as prior to the rename. Any other fixes and changes should be their own unrelated changes.

**Comment by palob** [comment]
I'd say let's just merge this and compare with https://wiki.xfce.org/releng/4.16/icons_rdns_naming_for_icons afterwards.
There's probably going to be duplicate allocations, need to boot into a Xfce session with this merged first.

**Review by ghost — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Comment by palob** [comment]
Papirus added some more symlinks https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/99dd1cb3e0411b09e4e72a5d5d0395519584b803?short_path=f25d47c#diff-c230992aebc23f8ba79d75ac5dd0b5e8b6d9b4bf2f62b2fcfb361fef51437a40

I'm not sure if those are app icons. 
I'm taking the liberty of pinging you, @meganukebmp @marcosins @fish47 @bgstack15.

If you are still Numix and Xfce users can you please help me out as to where those icons are shown?

**Comment by bgstack15** [comment]
[Gigolo](https://docs.xfce.org/apps/gigolo/start) is some sort of app in Xfce. I must not be on the newest version of Gigolo or don't have that app installed.

CPUGraph is the panel plugin icon and same for the weather. I haven't found specifically how to view the [Xfce4 fsguard plugin](http://goodies.xfce.org/projects/panel-plugins/xfce4-fsguard-plugin) icon, but it's some plugin that checks mount points disk space.

**Comment by palob** [comment]
Thanks. Panel plugin means it's not something you start like an app via launcher and the icon is only shown in the panel?
fsguard for instance has no ``.desktop`` file it appears.

**Comment by bgstack15** [comment]
A panel plugin is for displaying an icon/menu/item in the panel. A plugin usually does some small function of Xfce but can be its own separate binary. There's definitely no specific need for a separate .desktop file that would use the icon. The icon could be used only internally in xfce for the panel.

**Pull request merged**
