### PR TITLE
Icon for Enter the Gungeon (Steam)

### LINKED ISSUE #3712: Icon for Enter the Gungeon (Steam)
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-: | :-: | :-: |
| `Enter the Gungeon`| `steam_icon_311690` | `Enter the Gungeon.desktop` | original |

Description: "Enter the Gungeon is a bullet hell dungeon crawler" - featuring bullets as enemies shooting bullets.

Website: http://store.steampowered.com/app/311690/Enter_the_Gungeon/

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon |
| :--: | :--: | :--: |
| original enter_the_gungeon |  enter_the_gungeon circle | enter_the_gungeon square |

fixes #3712

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Can you please change the eyes/mouse colour to something above L36 instead of pure black?

The baseplate gradients are slightly misplaced.

**Comment by palob** [comment]
gradient is stil slightly misplaced.
misplaced

**Comment by mrmeszaros** [comment]
Yeah right, my `linearGradient`  element does not specify x coordinates:

```svg
<linearGradient id="bg" gradientUnits="userSpaceOnUse" y1="1" y2="47">
	<stop offset="0" stop-color="#f9a41b"/>
	<stop offset="1" stop-color="#f89c08"/>
</linearGradient>
```

Although the [specs](https://www.w3.org/TR/SVG/pservers.html#LinearGradientElementX1Attribute) say that in this case `x1="0%"` and  `x2="100%"` should assumed (it seems Inkscape interprets it strangely).

In other **PR**-s I did the same - I will review and fix them.

**Comment by palob** [comment]
It's not that big of a deal, just makes the gradient ever so slightly tilted.

**Review by palob — APPROVED** [review]

**Pull request merged**
