### PR TITLE
Icons for uTorrent

### PR DESCRIPTION
**Pull request by maxtron95**
For #5379 

https://www.utorrent.com/

utorrent-ci
utorrent-sq

### CODE REVIEW

**Comment by palob** [comment]
db entry needs a comma before ``utorrent``.

**Comment by palob** [comment]
Not sure if this can be considered a full-baseplate design but I think the symbol should be a bit smaller and the upper nodes should be corners, I mean it probably should be a sharp **μ**.

**Comment by palob** [comment]
If this turns out to be too full-baseplatish the most simplistic solution would be a recolouring of one of our ``μ``-icons.

**Comment by maxtron95** [comment]
Note: This icon is from the Numix Android Theme

**Comment by palob** [comment]
Ah, I see, the Circle icon has the baseplate shining through.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Yeeeeeah this might be from Circle's Android version but it definitely wouldn't make it into the theme today as is. Maybe some adjustment to make it a centre symbol [like this](https://idroot.us/wp-content/uploads/2015/03/uTorrent-logo.jpg)?

**Comment by Foggalong** [comment]
@creepertron95 When making a new PR and updating the JSON file I'd encourage you to copy an entry from another app rather than writing one out from scratch. That makes it much less likely schema errors will creep into your submissions.

**Comment by maxtron95** [comment]
On top of that, should I make the icon less full baseplatey and more of a symbol? and should I modify the bittorrent icon as well? (Both uTorrent and BitTorrent are related)

**Comment by Foggalong** [comment]
@creepertron95 Aye modify both :+1:

**Review by Foggalong — COMMENTED** [review]
As an alternative to [that](https://idroot.us/wp-content/uploads/2015/03/uTorrent-logo.jpg), using micropad as a straight an simple icon might work?

**Comment by palob** [comment]
Yeah, micropad or this one #5604

**Pull request merged**
