### PR TITLE
Calligra icons for Square + alignment fixes

### PR DESCRIPTION
**Pull request by palob**
For #3481

calligra

Alignment fixes for existing icons.

### CODE REVIEW

**Comment by andia89** [comment]
A question regarding Square Icons: could this be scripted? (A tleast for Icons that involve Symbols) it should be poasible to extract the syMbols and put them on a Square canvas with the Same color as for the Circle icons

**Comment by palob** [comment]
I'm not sure if finding the symbol is such a trivial task. What's grouped differs from symbol to symbol. 

It's probably still helpful even if the script yields a few broken icons.

**Comment by andia89** [comment]
Ah that's easy I guess just keep everyrhing that's not the baseplate. Do we
need to change Symbol sizes/Position etc? I guess i could put something
together.

Vincent Bermel notifications@github.com schrieb am Fr., 18. Nov. 2016,
23:20:

**Comment by palob** [comment]
Symbols need to go 1px up.
Symbol shadows (except for exceptions) need to be shifted 1px to the left.

**Comment by andia89** [comment]
Damn that makes the whole thing a lot harder...

**Comment by palob** [comment]
Isn't replacing the baseplate in Circle icons or working with templates a more elegant way of doing this?

This is what these scripts do:
https://github.com/numixproject/numix-labs/tree/master/Satya/script-o-hacky
https://github.com/numixproject/numix-labs/blob/master/Satya/script-o-mighty/numix-kit

**Comment by andia89** [comment]
Sure but where to we get the symbols from, Position it and move the Shadow?

**Comment by palob** [comment]
If it hasn't been cleaned away the easiest way is to look for the `id` each SVG object has.

The symbol is everything but the baseplate objects.

It's probably best to run `inkscape --vacuum-defs` on all icons first to get a uniformly formatted code base.

**Comment by Foggalong** [comment]
Please move this discussion to #3481 otherwise it's just going to get lost.

**Pull request merged**
