### PR TITLE
Icons for Conky Logomark Violet

### PR DESCRIPTION
**Pull request by maxtron95**
https://github.com/brndnmtthws/conky

conky-logomark-violet-2

conky-sq
conky-ci

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Only relevant for Circle: The inner blue rectangle doesn't cast a shadow on the baseplate.
The white baseplate looks a bit harsh here. Could we please get a slight bright blueish colouration?

**Comment by maxtron95** [comment]
I modified the baseplate, I was going with a white baseplate to match the other conky icons.

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
Looking at the repo this application _is_ conky, so this PR should be set as a proposed update to the existing conky icon with `conky-logomark-violet` as a symlink.

**Comment by palob** [comment]
I'll adjust this one as the new ``conky`` one while the existing one will be the new ``conky-manager`` one.

**Pull request merged**
