### PR TITLE
Icons for Delir

### PR DESCRIPTION
**Pull request by maxtron95**
https://github.com/delirvfx/Delir

delitr

delir-ci
delir-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Could we please have the main symbol enlarged to a height of 28px?
The white stripes look lost, like a holdover from another icon, I think it's better without.

**Comment by maxtron95** [comment]
Is it just me or is Travis stuck on yellow?

**Comment by palob** [comment]
Happens from time to time.

**Comment by Foggalong** [comment]
@creepertron95 If you click through to the actual check it passed fine, GitHub just hasn't updated.

**Pull request merged**
