### PR TITLE
Icons for NieR:Automata

### PR DESCRIPTION
**Pull request by maxtron95**
https://store.steampowered.com/app/524220/

nier-automata

nier-automata-ci
nier-automata-sq

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Spectacular design, is there an at least halfway decent looking way of reducing the tooth number for the sake of grid alignment?

**Comment by Foggalong** [comment]
@palob Thoughts?

Rounded middle line
automata-192
Straight middle line
automata-192striahgt
No middle line
automata

**Comment by Foggalong** [comment]
Comparing it to @creepertron95's design, the aligned-teeth versions definitely loses out on the creepiness that comes from having so many teeth in the mouth. I'm undecided, what do you reckon?

**Comment by palob** [comment]
I think they all look rather mischievous than creepy. How about jagged teeth, approximating the original teeth with triangles?

**Comment by Foggalong** [comment]
Triangles might be worth a shot, but I'll likely not have time to delve into trying that until the weekend so if anyone else fancies a bash go for it :+1:

**Comment by palob** [comment]
Triangular or half-ellipse teeth of 1px width (like in the original icon) with 1px black space in between might be OK.
Can look into this next week.

**Pull request merged**
