### PR TITLE
Icons for Cats are Liquid 

### PR DESCRIPTION
**Pull request by maxtron95**
For #4854 

cats-are-liquid-ci
cats-are-liquid-sq

### CODE REVIEW

**Comment by palob** [comment]
SVG preview broken again :-( but not as intense as last time.

**Review by palob — APPROVED** [review]

**Comment by maxtron95** [comment]
@palob Well the entire website was down at the moment.

**Comment by Foggalong** [comment]
@palob @creepertron95 The SVG preview was never properly fixed :confused:

**Review by Foggalong — CHANGES_REQUESTED** [review]
I'd like to see this face on a blob with ears (a la the cats in the game) on maybe a purple background? Keeps it a bit more interesting

**Comment by palob** [comment]
Merging it because it is somewhat OKish.

**Pull request merged**
