### PR TITLE
Few symlinks from #3423

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
I wasn't sure if those symlinks are alright.

### CODE REVIEW

**Comment by palob** [comment]
You mean you aren't sure this will work because of potential hardcoding?

**Comment by bilelmoussaoui** [comment]
I wasn't sure if we should provide those icons here on Core(Circle/Square) or in Numix base

**Comment by palob** [comment]
So far we did them here because they appear outside of Nuvola Player as usual app lauchers.
I think you can merge this here.

**Comment by bilelmoussaoui** [comment]
Alright :+1:

**Pull request merged**
