### PR TITLE
add linear gradient vscode

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Fixes the missing linear gradient of #3682

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
gradient bottom up again.

**Review by palob — CHANGES_REQUESTED** [review]
There's something wrong with positions.
Baseplate should be at Y1 (instead of Y0,695), symbol shadow should be at Y12 (instead of Y11,741).

**Comment by bilelmoussaoui** [comment]
Should be fixed now =)

**Comment by Foggalong** [comment]
Where possible I'm gonna start pushing for icons which have a coloured gradient background instead of just white or black. It makes the theme a bit more varied and is just generally nicer to look at. Thoughts on which of these works better for vscode?

screenshot_2017-05-18_08-52-27

**Review by Foggalong — CHANGES_REQUESTED** [review]
Add a non-white background (either me or @bil-elmoussaoui)

**Comment by palob** [comment]
I prefer the left one.

**Comment by bilelmoussaoui** [comment]
@Foggalong i prefer the left one too, but we still can add the right one as "-alternative"

**Comment by bilelmoussaoui** [comment]
@Foggalong This PR can be closed now?

**Comment by Foggalong** [comment]
I had this saved locally and tried to work out where it'd come from. I clearly didn't look hard enough before pushing, sorry @bil-elmoussaoui :(

**Pull request closed without merging**
