### PR TITLE
Icons for Obfuscate

### PR DESCRIPTION
**Pull request by palob**
https://gitlab.gnome.org/World/obfuscate

Based on an older iteration of the original icon

obfuscate
obfuscate-ci
obfuscate-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
This is actually a nicely designed icon, but I'd like us to get something in which is based on the current icon given they're so different. Want to minimise any possible confusion there

**Comment by palob** [comment]
The current official design is hard to get recognisable at smaller sizes.

How about a face with a censor bar across? Might suggest this was for photo editing though.

So basically something which shows letters/numbers on one side turning into blocks on the other side.

**Comment by Foggalong** [comment]
@palob Yeah, doesn't necessarily have to be exactly the same design. Could just be 4 numbers with two as is and 2 blocked?

@bilelmoussaoui Do you have any input on this? Realised looking at the Gitlab that it's actually your app!

**Comment by bilelmoussaoui** [comment]
This was the very first iteration of the icon and it doesn't really represent what I want to achieve with the app, especially in the future. Probably either using the 2nd iteration if you want something that could be recognizable at smaller sizes.

@Foggalong Yes it's my app :P

**Comment by Foggalong** [comment]
Is the second iteration different from the current icon? I've not come across that when looking online

**Comment by bilelmoussaoui** [comment]
@Foggalong https://gitlab.gnome.org/World/obfuscate/blob/cade72b5d62c7e2275ea0d63ba0e34b5035b4450/data/icons/com.belmoussaoui.Obfuscate.svg

**Comment by Foggalong** [comment]
@bilelmoussaoui Oooh brilliant, that design will lend itself much better to scaling! Thanks :grin:

**Comment by palob** [comment]
Pushed this direct representation of the new upstream design
obfuscate
obfuscate-ci
obfuscate-sq

**Comment by palob** [comment]
alternative idea

obfuscate-alt

**Comment by Foggalong** [comment]
I love the pushed design _but_ also that censorship icon is a really cool idea. Keep that around somewhere (even if it's just pushing it to Numix Labs) because it'd be a shame to let it go to waste

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
