### PR TITLE
qphotorec

### PR DESCRIPTION
**Pull request by W-Floyd**
iconified_qphotorec

### CODE REVIEW

**Comment by palob** [comment]
How would it look with stripes of solid colours instead of a gradient?

**Comment by W-Floyd** [comment]
I thought about it. I'll do that after I eat.

**Comment by W-Floyd** [comment]
Like this? Loosely based the colours off some similar icons.
iconified_qphotorec
I tried a radial design, but it isn't really suited to this in the end.

**Comment by palob** [comment]
Can you make the stripes overlap?
This will avoid the buggy outlines.
overlap

**Comment by W-Floyd** [comment]
Ah ha, yup

**Comment by W-Floyd** [comment]
I used straight lines, hopefully that will avoid any overhead that comes with curves :)
Still looks the same, so that's fine.
image

**Comment by palob** [comment]
Curves are better in general because overlapping objects sharing the same outline like it is now also can shine through and cause those infamous jagged outlines. The overhead is definitely negligible.

In this case it's all fine anyway though.

**Review by palob — CHANGES_REQUESTED** [review]
The Square symbol should go 1px down such that it is only 1px higher in comparison with Circle.

**Comment by W-Floyd** [comment]
It already is 1px higher than the circle. Ordinarily, I would have done 2px higher than the circle, but 1px seemed to look best.

**Comment by palob** [comment]
No, it is 2px higher currently.

**Comment by W-Floyd** [comment]
Nevermind, I'm dumb. I fixed it, then forgot I fixed it :P
iconified_qphotorec

**Review by palob — APPROVED** [review]

**Pull request merged**
