### PR TITLE
Icons for Grow Home

### LINKED ISSUE #3519: Icon for Grow Home (Steam)
Game: Grow Home
AppID: 323320
Icon: 
unityplayer

### PR DESCRIPTION
**Pull request by maxtron95**
Fixes #3519

grow-home-ci svg
grow-home-sq svg

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
I think the eyes could be moved 1px to the left inside the symbol. Then there's space to implement the edges present in the original icon. The jaw could be made 1px less "deep" (see below).
Both symbols can be moved 1px to the left because of the horizontal unbalance.
edges


Maybe a slightly brighter colour for the symbol?

**Comment by maxtron95** [comment]
@palob I pushed in some new changes for the icons you reviewed.

**Review by palob — APPROVED** [review]
Thank you :)

**Review by Foggalong — CHANGES_REQUESTED** [review]
Can we add the colouring from the characters appearance, makes it more vibrant and eye catching but would still be in line with the original design.

Grow_home_box_art,_Feb_2015

**Comment by maxtron95** [comment]
Pushed in this design:

grow-home-ci
grow-home-sq

**Review by palob — CHANGES_REQUESTED** [review]
Thanks for the change. Now you gave the eyes this 3Dish feature I think they should cast a shadow.

**Review by Foggalong — COMMENTED** [review]
Agreed about the eyes, but also yes this is such a great update :heart:

**Comment by palob** [comment]
Hmm, looks a bit strange on the Circle icon.

I'd say either without shadows or without the dark red feature above.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Yeah I think ditch the read inset above :+1:

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
