### PR TITLE
Icons for Space Engineers 

### PR DESCRIPTION
**Pull request by maxtron95**
https://store.steampowered.com/app/244850/

space-engineers-ci
space-engineers-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Wondering if we could get something more spectacular here.
Anyway, the guy should be 1 or 2px wider such that the gap between the legs can be 2px and aligned.

**Comment by maxtron95** [comment]
@palob Maybe we could look at the game's screenshots for some ideas on something more spectacular?

(https://steamdb.info/app/244850/screenshots)

**Comment by BlueManCZ** [comment]
I don't like the green color. I would go with something from their designs. What do you think?

a 
b

**Comment by maxtron95** [comment]
@BlueManCZ That looks better. I think I might pick the second one with the blue symbol.

**Comment by maxtron95** [comment]
What do you think of this design? (I had to make a 2px gap between legs) (I already pushed the design as well)

se-2

**Comment by BlueManCZ** [comment]
It's an astronaut. 2px gap between legs doesn't look right here. I think 1px aligned should be fine, what do you think @palob?

Snímek z 2020-07-21 18-44-37

**Comment by BlueManCZ** [comment]
circle15

**Comment by BlueManCZ** [comment]
http://colidocs.webly3d.net:5000/images/space-engineers-edit.svg

**Comment by palob** [comment]
Yeah, 1px + alignment is alright. I wonder if this would work with an actual spacesuit instead of just the silhouette.

**Comment by BlueManCZ** [comment]
> I wonder if this would work with an actual spacesuit instead of just the silhouette.

What do you mean?

**Comment by palob** [comment]
A detailed spacesuit design instead of a solid colour.

**Pull request merged**
