### PR TITLE
Few fixes

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Use path.join instead of hardcoding the paths. This allow the script to be executable in other platforms without any issue 👍 
For now the script should be quite stable and works as expected. I was thinking of implementing the creation of the desktop files within the source code, the same as HiDPI support

### CODE REVIEW

**Comment by Foggalong** [comment]
The one time I tried making this work on Windows all sort of things went wrong: file permissions were issued incorrectly, symlinks were botched, etc. Is there another situation where something other than `/` would be used in the file locations?

**Comment by bilelmoussaoui** [comment]
All i can think of for now is the path separator :( It has been more than 7 years since i last used Windows as my main OS so i can't really test this correctly or debug it. If anyone willing to report issues about that, i will fix all of them :)

**Comment by Foggalong** [comment]
Tbh, I'd vote just to not open it up to platforms that don't use `/`. It looks like a lot more trouble than it's worth for something that doesn't currently work, likely will never be used, and complicates the code.

**Comment by bilelmoussaoui** [comment]
Anyway, my PR is more of a cleaning of the code than having a fully working windows version :)

**Comment by Foggalong** [comment]
@bil-elmoussaoui There is some code cleaning, but most of it is switching over to `path.join` which is what I'm talking about

**Comment by bilelmoussaoui** [comment]
@Foggalong Well, it's doesn't harm the code as it's works the same as before :) I can revert the changes to path.join if you wish =)

**Comment by Foggalong** [comment]
@bil-elmoussaoui That's what I mean by what I said before: imo it does complicate the code for something that isn't needed. Reverting the change to `path.join` would be ideal.

**Review by Foggalong — CHANGES_REQUESTED** [review]
@bil-elmoussaoui That's what I mean by what I said before: imo it does complicate the code for something that isn't needed. Reverting the change to `path.join` would be ideal.

**Comment by bilelmoussaoui** [comment]
@Foggalong Instead of using path.join which i have removed in the latest commit, i have used .format, so the path is clear enough for us to see and debug in the future ;)

**Comment by Foggalong** [comment]
@bil-elmoussaoui Now that's a change I can get behind! Will have a looksy asap :)

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
Sorry for the delay, had a bit of a rough week with uni. Looks good to me though :+1:

**Comment by bilelmoussaoui** [comment]
Not a problem :) i will get the travis PR by the next weekend !

**Pull request merged**
