### PR TITLE
Icons for Skullgirls

### PR DESCRIPTION
**Pull request by maxtron95**
https://store.steampowered.com/app/245170/

skulg

skullgirls-ci svg
skullgirls-sq

I based the icons off of the game's logo.

### CODE REVIEW

**Review by palob — APPROVED** [review]
Hell yeah!
Skull and crown could get an on-symbol shadow though, the crown looks a bit lost, what's your opinion, @Foggalong

**Review by Foggalong — CHANGES_REQUESTED** [review]
I agree regarding the symbol-on-symbol shadow! Also @creepertron95 please replace the tabs in the JSON with 4 spaces, not sure why Travis hasn't been picking it up but that's standard for this project

**Comment by maxtron95** [comment]
@Foggalong Well then, All I have been using in my text editor is tabs, as I am used to tabs in programming, so it might be a bit of a problem. I would say about all of my PRs.

**Comment by Foggalong** [comment]
@creepertron95 Hot damn okay. Use spaces in any new and if you update any existing PRs with design tweaks then try and change them then, and otherwise I'll catch the stragglers which still have them

**Review by palob — APPROVED** [review]

**Comment by maxtron95** [comment]
@Foggalong I have added the symbol-on-symbol shadows to the icons

**Review by palob — COMMENTED** [review]
This looks definitely better but I still think the heart seems to be too far up especially looking at the Circle icon.
Is there a way you could reduce the heart portion above / to the sides of the skull, achieving a heart/skull composition closer to the original icon?

Maybe shrinking the heart and moving it down will do it.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Agreed, much better but needs moving 1px down for sure

**Review by palob — CHANGES_REQUESTED** [review]
For Circle I think the symbol can go down 1px still.
Revisiting the original icon, maybe it would look more true with the colours (baseplate, heart, crown) towned down?

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
Thanks for getting the PRs ready!

**Pull request merged**
