### PR TITLE
Icons for FFADO Mixer

### PR DESCRIPTION
**Pull request by palob**
http://ffado.org/

hi64-apps-ffado
hi64-apps-ffado-ci
hi64-apps-ffado-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I'm not familiar with the app, but looking at the icon I think the shape of the prongs might be to do with clipping to the border rather than the shape of the symbol. Is there an example of the icon on another base for comparison?

**Comment by palob** [comment]
Couldn't find anything. Logo and original icon look the same.

**Comment by palob** [comment]
Ah, you think I should go for pointed prongs all the way?

**Comment by palob** [comment]
Like this or squares/rectangles in all directions?

ffado-mixer svg

**Comment by Foggalong** [comment]
@palob I'd be alright with that, looks more fitting :)

**Comment by palob** [comment]
Pushed these

ffado-mixer svg
ffado-mixer svg sq

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
