### PR TITLE
Icons for linuxdeployqt

### PR DESCRIPTION
**Pull request by palob**
https://github.com/probonopd/linuxdeployqt

linuxdeployqt
linuxdeployqt-ci
linuxdeployqt-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I'm not sure on this, it leave the symbol looking very tall and thin. Is there a way to group them differently or box them in another (perhaps context relevant) shape?

**Comment by palob** [comment]
Here's a bigger cog.
linuxdeployqt2

**Comment by palob** [comment]
If this doesn't help I'll need to find a new "deploy" metaphor.

**Comment by Foggalong** [comment]
Good to go on operation big cog :+1:

**Comment by palob** [comment]
Pushed.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
