### PR TITLE
Use Docker with Travis

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
See #4047 
This is not ready yet.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
@Foggalong What do you think about this? It's almost ready, i just need to upgrade docker on Travis. Or maybe even switch to something else like circle.ci but I have to know first if you think that this deserve it :)

**Review by Foggalong — CHANGES_REQUESTED** [review]
I'm not merging this at the moment just because it depends on a private docker instance which could land us in a pickle if you ever left.

Ideally we need to set something up which works generally with the Numix organisation.

**Comment by bilelmoussaoui** [comment]
@Foggalong We should definitely set up a docker organization account

**Comment by bilelmoussaoui** [comment]
@Foggalong Can you setup the Docker account and send me an invitation?

**Comment by Foggalong** [comment]
@bilelmoussaoui You're going to have to talk me through this; I've never actually used Docker and I'm only vaguely aware of what it's actually for. Even in trying to find a signup page I'm drawing a blank

**Comment by bilelmoussaoui** [comment]
The signup page is here https://hub.docker.com/

**Comment by Foggalong** [comment]
@bilelmoussaoui I couldn't find that through searching :cry: Anyways, sent you an invite!

**Comment by Foggalong** [comment]
@bilelmoussaoui Is there any update on this? :relaxed:

**Comment by Foggalong** [comment]
Switched the base branch over to `python-clean` since it makes more sense to merge it into there first rather than straight into master. Also resolved the merge conflict (added test since this was proposed).

**Comment by Foggalong** [comment]
@bilelmoussaoui Sat down and tried to work out how to set this up and just got very confused. Is there any chance of you being able to set this up on the organisation account?

**Comment by bilelmoussaoui** [comment]
@Foggalong Definitely. Do we have an organization account set up already? Can you send me an invite so I can push to it? Thanks!

**Comment by Foggalong** [comment]
@bilelmoussaoui [We do, and you're already a member!](https://cloud.docker.com/u/numix/repository/docker/numix/core)

**Comment by Foggalong** [comment]
@bilelmoussaoui Any joy looking into this? :smiley:

**Comment by Foggalong** [comment]
@bilelmoussaoui Any joy looking at this? Realise you might have been busier than expected over the last few weeks :)

**Comment by Foggalong** [comment]
@bilelmoussaoui Any update with this? Travis also seems to be complaining now that our Python version is out of date :disappointed:

**Comment by Foggalong** [comment]
Made redundant by #5753

**Pull request closed without merging**
