### PR TITLE
remove calendar.svg and add few square icons

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
This PR removes the non-square icon `calendar.svg` which was removed on Circle too. Forgot to remove it in my latest PR.
And add a few square icons
screenshot from 2017-06-04 18-05-52
There was already a genymotion icon, i just tweaked it a bit and saved it as an optimized SVG

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
The genymotion icons have the gradients misplaced.

In the Peek icon the symbol shadow is ever so slightly misplaced (should be 9/9) while the basplate bevel shadow is significantly misplaced.

The rambox icon needs manual recreation needs manual recreation of the goat/ape (is it one?) shadow. In order to do that delete the old one, duplicate the goat path, move it one px down, duplicate the circle and do an intersection of the circle and the 1px moved down goat thing. Finally adjust the colour to full black with 10% opacity.

The steam_322330 icon should have symbol+symbol shadow 1px higher.

**Comment by bilelmoussaoui** [comment]
Thanks for your great reviews :) I've pushed a fix for Genymotion, Peek & The steam game (don't starve together)
I will try to figure out how to fix the Rambox icon (i'm not sure that i have the skills yet)

**Review by palob — CHANGES_REQUESTED** [review]
genymotion icons still have a horizontal shadow.

The symbols in those icons should probably sit at Y17 (1px upwards).

**Comment by palob** [comment]
By the way, duplicate is ``Ctrl``+``D`` :)

**Comment by bilelmoussaoui** [comment]
I tweaked the shadows a bit, even if i don't see any horizontal one :) And moved both symbols 1px up which looks much better indeed

**Comment by bilelmoussaoui** [comment]
I've fixed the Rambox icon too :+1: Thanks for the tips!

**Comment by palob** [comment]
Cool!

genymotion's gradient is still askew.
gradient

In the Rambox icon the Circle shadow is slightly misplaced.

**Comment by palob** [comment]
Was it that slightly wrong in the Circle icon as well?

**Comment by bilelmoussaoui** [comment]
The genymotion icon is just broken :( wherever i place the gradient, save the file re open it with inkscape and the gradient appears somewhere else :(

**Comment by palob** [comment]
OK, that's what I meant when I was talking about broken Inkscape editability.

You need to take another (non-broken) icon, remove the symbol, recolour the baseplate gradient and paste the genymotion symbol in then.

**Comment by bilelmoussaoui** [comment]
Fixed that :+1:

**Comment by bilelmoussaoui** [comment]
I thought i did :p but i doesn't work, i will recreate those icons to make sure this is fixed

**Comment by palob** [comment]
The Square Rambox icon is still left with the slightly misplaced circle shadow.

**Comment by bilelmoussaoui** [comment]
I've modified the Rambox shadow, didn't commit yet. What do you think about this?
screenshot from 2017-06-05 02-06-24
And i've also fixed genymotion gradients :)

**Comment by palob** [comment]
Now there's a few things wrong with the Square rambox. The circle (as well as its shadow) isn't exactly 30x30 and slightly misplaced. Maybe because of this the goat/ape thing shadow slightly exceeds the circle.
exceed

**Comment by bilelmoussaoui** [comment]
I will try to take care of that tomorrow :+1:

**Comment by bilelmoussaoui** [comment]
All those icons are already on master thanks to the great work of @W-Floyd :+1:

**Pull request closed without merging**
