### PR TITLE
50 square icons - Round 10

### PR DESCRIPTION
**Pull request by W-Floyd**
I opted not to shift `leagueoflegends` up 1px on the square icon, it feels better as is, IMO. It has also been pointed out to me that [the icon has changed](http://i.imgur.com/xNLs83T.png), and that, at the very least, the gradient is ugly. I don't play League, but I might revisit it after I finish the square port, if that's okay.

Name | Icon
--- | ---
kitematic | iconified_kitematic
kkedit | iconified_kkedit
kkeditroot | iconified_kkeditroot
klatexformula | iconified_klatexformula
klayout | iconified_klayout
klettres | iconified_klettres
klickety | iconified_klickety
klines | iconified_klines
kmag | iconified_kmag
kmahjongg | iconified_kmahjongg
kmplot | iconified_kmplot
knavalbattle | iconified_knavalbattle
knetattach | iconified_knetattach
knetwalk | iconified_knetwalk
knights | iconified_knights
knowthelist | iconified_knowthelist
koala | iconified_koala
kolf | iconified_kolf
kollision | iconified_kollision
kompare | iconified_kompare
kongdash | iconified_kongdash
konquest | iconified_konquest
korora-welcome | iconified_korora-welcome
kreversi | iconified_kreversi
kronometer | iconified_kronometer
kshisen | iconified_kshisen
kshutdown | iconified_kshutdown
ksirk | iconified_ksirk
ksnakeduel | iconified_ksnakeduel
kspaceduel | iconified_kspaceduel
ksquares | iconified_ksquares
kstars | iconified_kstars
kst | iconified_kst
ktip | iconified_ktip
ktuberling | iconified_ktuberling
kturtle | iconified_kturtle
kvirc | iconified_kvirc
kwave | iconified_kwave
kwordquiz | iconified_kwordquiz
laby | iconified_laby
labyrinth | iconified_labyrinth
lantern | iconified_lantern
lash_panel | iconified_lash_panel
latexdraw | iconified_latexdraw
layout | iconified_layout
leagueoflegends | iconified_leagueoflegends
lenmus | iconified_lenmus
librevault | iconified_librevault
lifeograph | iconified_lifeograph
lime | iconified_lime

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Totally agree about the League of legends icon. The icon needs some :heart:. The game runs smoothly on Linux using Wine.

**Comment by bilelmoussaoui** [comment]
And really awesome work on this huge issue! still 210 more to go :+1:

**Comment by W-Floyd** [comment]
210? I thought it was 200... I'll check after I finish an episode...
Edit: I have 200 left by my count. Plan is to finish them tomorrow, I'll be home all day.

**Review by palob — APPROVED** [review]

**Review by Foggalong — COMMENTED** [review]
I've only just noticed, but @palob what was the reasoning behind the shadow in klines?

**Comment by palob** [comment]
I suppose I thought of that checkerboard thing as background.
Maybe it would be fine with shadow as well?

**Comment by W-Floyd** [comment]
I'd go for the second, personally.

Before | After
--- | ---
iconified_klines | iconified_klines

**Comment by Foggalong** [comment]
Aye, push the second. If it's not covering the entire diameter of the baseplate it should probably be treated as a symbol.

**Comment by W-Floyd** [comment]
Sorry for the delay, I managed to bork my local copy of the repo and it took me a while to re-clone properly XD

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
