### PR TITLE
50 square icons - Round 6

### PR DESCRIPTION
**Pull request by W-Floyd**
Note that some fixes to all the square firefox icons were also made, hope they're okay.

Name | Icon
--- | ---
efax-gtk | iconified_efax-gtk
eid-viewer | iconified_eid-viewer
eintopf | iconified_eintopf
eiskaltdcpp | iconified_eiskaltdcpp
eko | iconified_eko
electric | iconified_electric
electrum | iconified_electrum
elektra | iconified_elektra
elki-icon | iconified_elki-icon
engauge-digitizer | iconified_engauge-digitizer
enigma | iconified_enigma
entangle | iconified_entangle
epsxe | iconified_epsxe
eric | iconified_eric
ericweb | iconified_ericweb
etcher | iconified_etcher
eureka | iconified_eureka
factorio | iconified_factorio
falling_time | iconified_falling_time
fcitx-sogoupinyin | iconified_fcitx-sogoupinyin
fgmk | iconified_fgmk
fillets-ng | iconified_fillets-ng
firefox-aurora | iconified_firefox-aurora
firefox-beta | iconified_firefox-beta
firefox-developer-icon | iconified_firefox-developer-icon
firefox | iconified_firefox
firefox-trunk | iconified_firefox-trunk
flamerobin | iconified_flamerobin
flaw | iconified_flaw
flowblade | iconified_flowblade
fontmatrix | iconified_fontmatrix
foobnix | iconified_foobnix
forgedallianceforever | iconified_forgedallianceforever
fotoprint | iconified_fotoprint
fotowall | iconified_fotowall
foxit-reader | iconified_foxit-reader
frama-c | iconified_frama-c
franz | iconified_franz
fraqtive | iconified_fraqtive
freecad | iconified_freecad
freechartgeany | iconified_freechartgeany
freecol | iconified_freecol
freedoom | iconified_freedoom
freeminer | iconified_freeminer
freenet | iconified_freenet
freeorion | iconified_freeorion
frescobaldi | iconified_frescobaldi
fritzing_icon | iconified_fritzing_icon
frogr | iconified_frogr
fromscratch | iconified_fromscratch
frozen-bubble | iconified_frozen-bubble
fruho | iconified_fruho
fs-uae | iconified_fs-uae
fuse-emulator | iconified_fuse-emulator

### CODE REVIEW

**Comment by W-Floyd** [comment]
Okay, that's it for... I guess it's morning now. 400 to go. Fingers crossed, I finish them this weekend. Sorry for all the PRs to review :stuck_out_tongue_closed_eyes: 

Coincidentally, it was 222 I did today...

**Comment by palob** [comment]
:1st_place_medal: 

Have some peaceful rest and report back in case you dreamt of Numix icons.

**Review by palob — APPROVED** [review]

**Comment by Foggalong** [comment]
Merging this, but gonna make a new issue for a better Fritzing design. The Cricle one just about works but because of the shadow placement in Square it looks off.

**Comment by W-Floyd** [comment]
Yeah, I thought that at the time.

**Pull request merged**
