### PR TITLE
Icon for Eolie

### LINKED ISSUE #3746: Icon Request : Eolie
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Eolie`| `org.gnome.Eolie` | `org.gnome.Eolie.desktop` | original

Eolie is a new GNOME web browser.

Website: [https://github.com/gnumdk/eolie](https://github.com/gnumdk/eolie)

### PR DESCRIPTION
**Pull request by palob**
Fixes #3746

eolie-numix

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
The icon name for Eolie is `org.gnome.Eolie` instead of `eolie` as specified in #3746

**Comment by bilelmoussaoui** [comment]
@rafaelmardojai Fixed https://github.com/numixproject/numix-core/commit/8e15f206a0e38323c9f906a5eaeca4fa9fe21f09

**Comment by palob** [comment]
@rafaelmardojai We always implement those nasty dotted icon names assymlinks so as to keep the core repo tidy.

**Comment by palob** [comment]
Ah OK, I forgot it indeed :)

**Pull request merged**
