### PR TITLE
Update Atom designs

### PR DESCRIPTION
**Pull request by palob**
atom-nightly
atom-nightly-ci
atom-nightly-sq

### CODE REVIEW

**Comment by maxtron95** [comment]
@palob Should we redo the colors of the other 2 atom icons as well?

**Comment by palob** [comment]
Were the colours changed upstream?
If so we should redo the symbol alongside, it isn't executed very well.

**Comment by maxtron95** [comment]
@palob The Atom icons were always those colors but the color in Numix's Atom icons is white and the stable Atom icon is purple for some reason.

Atom -


Atom Beta -


Atom Dev (We should add an icon called "atom-dev") - 


Atom Nightly -

**Comment by maxtron95** [comment]
@palob Should we modify the colors of the other atom icons?

**Comment by palob** [comment]
Yep, I'd say so.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Agreed, let's take the opportunity to recolour them all! You up for doing that @palob? No worries if not, I'd be fine to handle it :slightly_smiling_face:

**Comment by palob** [comment]
Generally speaking yes, might take some time until I can get to this as this is something I envision to take extra time.

**Pull request merged**
