### PR TITLE
Icons for 7 Kingdoms: Ancient Adversaries

### PR DESCRIPTION
**Pull request by maxtron95**
https://7kfans.com/

7kaa

7kaa-ci
7kaa-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
I think the bezel colour should me much brighter, like below or even more so. Right now it looks like a miscoloured shadow.

bezel

**Review by palob — CHANGES_REQUESTED** [review]
Symbol on circle should sit 1px higher, maybe same for Square. Let's do it for now.

You got your icons misnamed with a ``-ci`` prefix at the end. This is why the build fails.

**Review by palob — CHANGES_REQUESTED** [review]
Square icon is still misnamed.

**Review by Foggalong — APPROVED** [review]
I'm good with this now! @palob?

**Review by palob — APPROVED** [review]

**Pull request merged**
