### PR TITLE
Add circle icon for the Escapist (Steam)

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| original escapist | the-escapist circle 128 | the-escapist square 128 |

The game is about breaking out of prisons, therefore the change in the icon.

### CODE REVIEW

**Comment by mrmeszaros** [comment]
The game is also available for [android](https://play.google.com/store/apps/details?id=com.team17.escapists).
Where do you usually put the android icon names?

**Comment by palob** [comment]
That's a cool design idea. :+1: 
Can you please reshape the baseplate like this such that baseplate and outer symbol parts do not overlap? This will keep the baseplate from shining through.
shinethrough

Maybe the outer bars aren't needed at all.
The symbol isn't really recognisable rendered at 16px. Can you please try a lighter background?
Or only straight and jagged bars?.

**Comment by mrmeszaros** [comment]
Hey,
* reshaped and recolored the baseplate
* created a version without the sidebars, but it does not look so good (in my opinion):

| | |
|-|-|
| the-escapist 128 b-c | the-escapist square 128 b-c |

**Review by Foggalong — APPROVED** [review]
Yeah looks better to me with the sidebars than without. @palob?

**Comment by palob** [comment]
Depends on how it looks in 16px I think, otherwise good to go.

**Comment by mrmeszaros** [comment]
Here it is rendered for some the common sizes:

| 16 | 24 | 48 |
|:-:|:-:|:-:|
| the-escapist circle 16 | the-escapist circle 24 | the-escapist circle 48 |
| the-escapist square 16 | the-escapist square 24 | the-escapist square 48 |

**Review by palob — APPROVED** [review]

**Pull request merged**
