### PR TITLE
2gis - Icons and entry for 2GIS.

### LINKED ISSUE #2523: Icon for 2GIS
Name=2GIS
Name[ru]=2ГИС
Icon=2gis
2gis
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26399241-icon-for-2gis?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by W-Floyd**
Fixes #2523

Happy belated Christmas, internet was out for a while, or I'd have been working on more icons :laughing: 

iconified_2gis

### CODE REVIEW

**Review by palob — APPROVED** [review]
Source has this cruft again. Do you remember how we got rid of it?

**Comment by W-Floyd** [comment]
Manually... It only happens if you ever save as a regular Inkscape SVG, which I must have accidentally done.

**Review by palob — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
The tests fails because of this 
```
Database entry 2gis not correctly ordred
Should be placed at 2 instead of 1
Database entry 2048 not correctly ordred
Should be placed at 1 instead of 2
```
the database is not correctly ordered

**Comment by W-Floyd** [comment]
Guess I don't know my alphabet :laughing: 

As an aside, **ordred** -> **ordered**

**Comment by bilelmoussaoui** [comment]
Ah thanks for the correction, I have always thought it was the correct word!

**Pull request merged**
