### PR TITLE
Icons for Patchwork

### PR DESCRIPTION
**Pull request by palob**
https://github.com/ssbc/patchwork

ssb-patchwork
ssb-patchwork-ci
ssb-patchwork-sq

There is something which feels a bit un-Numixy but I couldn't get it working without the lines.

### CODE REVIEW

**Comment by maxtron95** [comment]
@palob It seems that the Papirus Icon theme managed to make an icon for this without strokes. (https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/64x64/apps/nz.scuttlebutt.Patchwork.svg) 

There should also be a symlink for the icon name, `nz.scuttlebutt.Patchwork`.

**Comment by palob** [comment]
Ah, thanks for the hint. Might try this but we can't have those small in-between shadows.

**Comment by palob** [comment]
This would be my interpretation of this style
ssb-patchwork-ci2

Simplistic approach
ssb-patchwork3

**Comment by Foggalong** [comment]
@palob I love that! Could we have one which uses only 2 or three colours in each section? I think you're right that the detailed interpretation is too detailed but the simplistic one looks a little bare.

**Review by Foggalong — CHANGES_REQUESTED** [review]
@palob I love that! Could we have one which uses only 2 or three colours in each section? I think you're right that the detailed interpretation is too detailed but the simplistic one looks a little bare.

**Comment by palob** [comment]
Pushed
ssb-patchwork-NEW
ssb-patchwork-NEW-sq

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
Amazing work here :heart:

**Pull request merged**
