### PR TITLE
Square icon for Easystroke, and fixes to circle icon.

### PR DESCRIPTION
**Pull request by W-Floyd**
Circle icon didn't have a gradient, so I added that.
iconified_easystroke

### CODE REVIEW

**Comment by palob** [comment]
While you're at it symbol+shadow in the Circle icon definitely need to go up 1px.

**Comment by palob** [comment]
Actually all your files aren't as optimised as possible. There's always this metadata cruft at the beginning.

**Comment by W-Floyd** [comment]
Sure, that would be better.

**Comment by W-Floyd** [comment]
Ah, and right you are again. I keep missing some of them :P

**Comment by W-Floyd** [comment]
iconified_easystroke

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
I took the liberty to clean up the original symbol a bit.

**Comment by W-Floyd** [comment]
Oh cool! How'd you do that? Or was it manually?

**Comment by W-Floyd** [comment]
iconified_easystroke

**Comment by palob** [comment]
Recreated it as stroke, used the original one which was comprised of something like 1000 nodes as stencil.
It's not perfect however. Maybe I'll come to it later.

**Comment by W-Floyd** [comment]
Ah, okay. Out of curiosity, shouldn't the stroke be converted to a path now? I tried quickly, but Inkscape is being weird and drops the smoothing of the curve :/

**Comment by palob** [comment]
Exactly, this is why I didn't do it.

**Comment by W-Floyd** [comment]
lol, fair enough! I like the idea of simplifying it though.

**Comment by W-Floyd** [comment]
I went ahead and redrew the symbol using a CAD package. It correctly bakes into a path now, and is symmetrical, so it should be good.
iconified_easystroke

**Comment by palob** [comment]
Haha thanks, was about to give it the next shot myself.

Can you please change the symbol dimensions to 24x22 and place it at integer coordinates?

**Comment by W-Floyd** [comment]
Done :)
iconified_easystroke
screenshot from 2017-06-25 20-13-06

**Review by palob — APPROVED** [review]

**Pull request merged**
