### PR TITLE
Icons for Happy Wheels

### PR DESCRIPTION
**Pull request by maxtron95**
https://play.google.com/store/apps/details?id=com.fancyforce.happywheels

com fancyforce happywheels

happy-wheels-ci
happy-wheels-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Symbol is very nice but two-colour-baseplates is another design feature set to be retired, cf. #3706 for instance.
Again some style cruft and Circle icon isn't saved as optimised.

**Comment by maxtron95** [comment]
@palob Should I go ahead and average the colors for the baseplate?

**Comment by palob** [comment]
average, one out of the 2 or a new colour, whatever will cut a good figure and/or have some relation to the app.

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
This is just too detailed unfortunately and doesn't end up fitting in the Numix style. A bicycle or the white helmet (without a head) viewed side on might give some more joy designwise

**Review by palob — CHANGES_REQUESTED** [review]
Could we please have the alignment fixed like this



and the helmet colours set to ``f9f9f9ff`` (white) and ``333333ff`` (black)?

**Review by palob — APPROVED** [review]

**Pull request merged**
