### PR TITLE
Icon and entry for BSD.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #2183

The colour scheme made me think of the [hammer and sickle](https://upload.wikimedia.org/wikipedia/commons/7/7e/Hammer_and_sickle.svg), but whatcha gonna do?

iconified_distributor-logo-bsd

### CODE REVIEW

**Review by palob — COMMENTED** [review]
It's a cool design, is it any good with a wider stick?

**Comment by W-Floyd** [comment]
iconified_distributor-logo-bsd

I think this scales better, thanks :)

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
Rejecting design this not because it's badly done or anything, but when I see it I don't immediately make the connection to BSD. Just a simplified daemon (like the penguin with Linux) would do

**Comment by W-Floyd** [comment]
kk, I'll do that soonish.

**Comment by W-Floyd** [comment]
Thoughts? I would want to try just the head, but I'll need to make it different from the FreeBSD logo...

iconified_distributor-logo-bsd

**Comment by palob** [comment]
Looks ace, is it discernible at smaller sizes?

**Comment by W-Floyd** [comment]
Eh, not too bad I guess. 
image

**Comment by palob** [comment]
I mean at very :) small sizes, like scaled down to 16px.

**Comment by W-Floyd** [comment]
Sorry for the delay, I've gotten lazy with all my free time :stuck_out_tongue_closed_eyes:

At 16px it's... not really much of anything. Mind you, I'm not sure many icons are.
image

Personally, I don't think it matters too much in this case.

**Comment by palob** [comment]
You're right, distro icons are not likely to be rendered this small 👍

**Comment by Foggalong** [comment]
@W-Floyd My only thing is that the choice of gray and red don't contrast very well; maybe try going for a lighter gray?

**Comment by palob** [comment]
Maybe black?

**Comment by W-Floyd** [comment]
image

image

image

**Comment by palob** [comment]
Could be a tad darker still. How about a slight blueish tint?

**Comment by W-Floyd** [comment]
image

image

**Comment by W-Floyd** [comment]
Ugh, another commit I forgot to push...

iconified_distributor-logo-bsd

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
