### PR TITLE
Icons for Clipped

### LINKED ISSUE #4083: Icon Request: Clipped
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Clipped | `com.github.davidmhewitt.clipped` | `com.github.davidmhewitt.clipped.desktop` | Clipped| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

### PR DESCRIPTION
**Pull request by really-need-an-api-key**
Fixes #4083 

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| original | circle | square |

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
The baseplate gradients are bottom up.
Can you please remove the unneeded ``;paint-order:stroke fill markers`` stuff from the SVG source?

**Comment by really-need-an-api-key** [comment]
Sorry, probably reversed the gradients when messing with the svg and the paint-order style must have been added by inkscape (can never get it to export exactly as i want).
Fixed now.

| Circle icon | Square icon |
| :-- | :-- |
| circle | square |

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
Very minor change, but can you extend the clip up the top by 1px. It make it feel a little more natural. 2019-01-28-161444_229x109_scrot

**Comment by really-need-an-api-key** [comment]
| Circle | Square |
| :--- | :--- |
| circle | square |

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
