### PR TITLE
Icons for Stremio

### LINKED ISSUE #2674: Icon for Stremio
Stremio is the new PopcornTime
The application does not have a desktop file, you can name the icon as `stremio`
The default icon is 
stremio-white-small
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28251214-icon-for-stremio?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by maxtron95**
Fixes #2674

stremio

stremio-ci
stremio-sq

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
There seems to be a second icon name, ``smartcode-stremio`` https://github.com/Stremio/stremio-shell/blob/master/smartcode-stremio.desktop
Could you please add a symlink?

**Review by palob — APPROVED** [review]
Thanks.

**Comment by maxtron95** [comment]
There is an Android port for this program as I could add a symlink onto the entry.

**Comment by palob** [comment]
Aye, go for it please.

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
@creepertron95 Sorry for not catching it earlier but there's an unused arrow below the symbol causing a visible glitch (you can see it in the Square preview above left from the arrow symbol).

Could we please get a fix for it?

**Comment by maxtron95** [comment]
@palob I'm not sure if I can fix it since the PR is already merged. Unless I can figure out how to pull in the latest changes in the branch.

**Comment by Foggalong** [comment]
@creepertron95 Yeah because it's merged a new PR will be needed, not possible to add extra commits after a merge point without doing fancy git work

**Comment by maxtron95** [comment]
@Foggalong I don't know how to sync the upstream master branch with my forks master branch. I was wondering how you synced upstream with my branches.

**Comment by Foggalong** [comment]
@creepertron95 It is possible to sort it on your end locally using git if you want to try it, but it's easier for me to sort on my end using the repo management tools so you've no obligation to :smile:

**Comment by bilelmoussaoui** [comment]
> @Foggalong I don't know how to sync the upstream master branch with my forks master branch. I was wondering how you synced upstream with my branches.

Simple:
```
git remote add upstream https://github.com/numixproject/numix-core.git
git pull upstream master --rebase
git push origin master -f 
```

**Comment by Foggalong** [comment]
@creepertron95 I've just reread this and I misread that you were asking about conflict resolutions, entirely my bad :facepalm: Thanks @bilelmoussaoui for _actually_ answering the question asked!

**Pull request merged**
