### PR TITLE
Icons for Popsicle

### PR DESCRIPTION
**Pull request by palob**
https://github.com/pop-os/popsicle

com system76 Popsicle
com system76 Popsicle-ci
com system76 Popsicle-sq

### CODE REVIEW

**Comment by maxtron95** [comment]
@palob How does it look on a pink baseplate?

**Comment by palob** [comment]
Probably worth a try, will do when I find time.

**Comment by palob** [comment]
popsicle1
popsicle2
popsicle3
popsicle4

**Comment by palob** [comment]
I think I prefer the purplish no 3. Could be a tad brighter though.

**Comment by maxtron95** [comment]
I'd say either No. 3 or No. 4 (I like the color of No. 4 in my opinion.)

**Review by Foggalong — APPROVED** [review]
Quite like the original blue so running with it! Nice suggestion though @creepertron95, the pinks were still nice :)

**Pull request merged**
