### PR TITLE
New Zotero circle icon - closer to official logo

### PR DESCRIPTION
**Pull request by R-Broadley**
Changed background from Burgundy to Grey and Z from white to red.
Z also made bolder.

Official Zotero logo can be found here: https://www.zotero.org/support/_media/logo/zotero_512x512x32.png

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
You can change the colours to match the original icon, but please retain the shadow. That's part of the Numix guidelines.

Also, would you mind adding a square icon in this pr too?

**Comment by R-Broadley** [comment]
Square icon and shadows are no problem, will add them.
Where are the Numix guidelines, can't seem to find them?

**Comment by Foggalong** [comment]
@R-Broadley They're [officially here](https://github.com/numixproject/numix-wiki/wiki/Guidelines), but are also very out of date. I keep meaning to write new ones but then other stuff comes up. In the mean time I'd recommend just looking at other Numix icons and taking the key features of them (shadows, gradients, etc) into yours. We're also more than happy to help address any problems that come up :)

**Comment by palob** [comment]
Hi, what needs fixing above all is that vertical and horizontal lines need to be aligned with the pixel grid (``#`` key to toggle it in Inkscape). Otherwise the icon will look blurry.

zotero

**Comment by R-Broadley** [comment]
I think I've addressed all the comments, shadow re-added, aligned to pixel grid, square version updated.

**Comment by bilelmoussaoui** [comment]
@R-Broadley The shadow of the square icon must be moved to 1px on the left

**Comment by R-Broadley** [comment]
Shadows should be identical on both (the Z translated (1, 1) with black color, 0.1 opacity).
What are you viewing them with?

**Review by palob — CHANGES_REQUESTED** [review]
Symbol is still misaligned

**Comment by R-Broadley** [comment]
@palob some specifics would be nice, misaligned in which direction and which icon, circle, square or both.

**Comment by bilelmoussaoui** [comment]
@R-Broadley I can't visualize the icon on Inkscape :/ 
screenshot from 2017-05-18 22 21 05

**Comment by palob** [comment]
Relative to the pixel grid like for instance in the current icon.
zotero

Any pixel which is filled up with more than one single colour will be shown with an interpolated colour.
If a boundary between a red rectangle and a yellow rectangle isn't congruent with the pixel grid a orange line will be shown between the two on screen. This is where the blurriness originates from.

**Comment by R-Broadley** [comment]
@bil-elmoussaoui it appears inkscape does not have support for svg's lineto commands (https://www.w3.org/TR/SVG/paths.html#PathDataLinetoCommands)
The file renders everywhere else just fine.

**Comment by R-Broadley** [comment]
@palob I'm not following, the most recent version should line up with the pixel grid (e.g. the top of the z is 5px wide from 14, 14 to 32, 14). Not that it makes any difference when it is inevitably scaled.

**Comment by palob** [comment]
No, the 48px preview is still blurry and just like @bil-elmoussaoui in Inkscape I can't see anything of the symbol at all.

**Comment by R-Broadley** [comment]
Should all be fixed now, I don't normally use inkscape but have checked the latest version of the icons and they now display correctly as far as I can see.

**Review by palob — CHANGES_REQUESTED** [review]
You implemented the symbol (as well as the shadow) as stroke. Can you please turn it into a path?

**Comment by Foggalong** [comment]
@R-Broadley Can you give us permissions to push to the branch these changes were made on so we can finish the work and get it merged in?

**Pull request closed without merging**
