### PR TITLE
Icons for TikTok

### PR DESCRIPTION
**Pull request by maxtron95**
https://www.tiktok.com/en/

tiktok

tiktok-ci
tiktok-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
I'm afraid this doesn't work. The baseplate needs to be brighter as the symbol shadow will be hard to recognise this way.
A gradient of 51L --> 61L is the darkest we normally use for blacl/grey baseplates.

The symbol shadow ought to be black with 10% opacity, sorry and we cant have this on-symbol outline.

**Comment by maxtron95** [comment]
@palob How do you think I should go about the symbol then? Many people recognize the tiktok icon from the blue and red outlines present on the original icon.

**Comment by palob** [comment]
I think it's a bad design even with the original icon. Looks glitched at small sizes. Maybe blue for the symbol and the red for the baseplate?

**Comment by maxtron95** [comment]
@palob I will see if I can come up with some alternative designs after I work.

**Comment by maxtron95** [comment]
@palob I created some alternative icons. You can pick which one is the best and I will go from there.

1.
tiktok-alt1

2.
tiktok-alt12

3.
tiktok-alt3

**Comment by palob** [comment]
I say no 1.

**Comment by palob** [comment]
Does the symbol on the Circle icon more centered when shifted 1px to the left and/or 1px up?

**Review by Foggalong — COMMENTED** [review]
Staring at these I think maybe up 1px but not left?

Screenshot from 2020-06-28 17-36-06

**Review by palob — APPROVED** [review]

**Pull request merged**
