### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by palob**
+ alignment fix + gradient/stroke removal for frescobaldi
+ alignment fix for rosegarden
+ outline fix for strife
+ bezel fix for vega

### CODE REVIEW

**Review by Foggalong — APPROVED** [review]
Oh jees I hate that vega icon so much. One to address at a later date

**Comment by maxtron95** [comment]
@Foggalong Could we get a symbol like from the original logo?

vega

**Comment by palob** [comment]
Like that thing as a 30px diameter circle symbol?

**Comment by maxtron95** [comment]
Yes

**Comment by palob** [comment]
That's the way to go I think.

**Pull request merged**
