### PR TITLE
Bunch of square icons

### PR DESCRIPTION
**Pull request by andia89**
Yeah with the templates it is still tedious but doable in a finite amount of time...
I moved the symbols up 1px in a few icons where it seemed reasonable to me

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
The icons should be saved as optimized SVG

**Comment by palob** [comment]
Yeah but without the CSS to XML conversion option.

**Comment by andia89** [comment]
Ran svgcleaner instead

**Comment by palob** [comment]
The latest git version with the option ``--join-style-attributes=all``?

Otherwise the icons will suffer from the gradient bug.

**Comment by palob** [comment]
Icons as such are fine. I wonder if all icons would look better with the symbol 1px up.

**Comment by andia89** [comment]
Do you think?
screenshot from 2017-06-11 13-23-35

For me some of them are already too far up...
But we should figure that out, before I'll add more.

**Comment by palob** [comment]
For the Square icons I think the bottom bezel isn't part of the baseplate. It's basically the side if you look at it 3Dish.

**Comment by Foggalong** [comment]
@wa4557 This seems to have ran into a conflict because some icons were covered by another commit which is missed. My bad :disappointed: :

**Review by Foggalong — CHANGES_REQUESTED** [review]
This seems to have ran into a conflict because some icons were covered by another commit which is missed. My bad :disappointed:

**Comment by andia89** [comment]
Closing since @W-Floyd did this amazing job with the square icons

**Comment by W-Floyd** [comment]
lol Now I can stop going from reverse alphabetical order :3

**Pull request closed without merging**
