### PR TITLE
Icons for Smash Hit (Android)

### PR DESCRIPTION
**Pull request by maxtron95**
https://play.google.com/store/apps/details?id=com.mediocre.smashhit

smash-hit

smash-hit-ci svg
smash-hit-sq svg

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Wow, that's a rad one (even if the shadow for the cracks is illogical).
Some small nitpicking, this looks like a glitch somewhat.

**Comment by maxtron95** [comment]
I think I intentionally did that as part of the cracks.

**Comment by palob** [comment]
The square angle looks a bit unnatural though.

**Comment by maxtron95** [comment]
Should I get rid of the square angle or modify it a bit.

**Comment by palob** [comment]
Either straightening it there or moving the tip out for a longer crack.

**Comment by maxtron95** [comment]
@palob I modified the angle to be more like a crack.

**Review by palob — APPROVED** [review]
That's it, thank you!

**Comment by maxtron95** [comment]
@palob One more question, Will the android icon themes ever be worked on and updated again in the future?

**Comment by palob** [comment]
If somebody steps in, why not?
Personally I haven't got the slightest notion of how Android theming works and frankly I'm not very interested in devoting time to it.

That said there are many icons in the repo which could be used for the Android theme and are just waiting for symlinks (or the respective db entries).

**Review by Foggalong — COMMENTED** [review]
Screenshot from 2020-06-06 17-45-49

I've made a small modification to the Circle version of the design, rotating the highlight so that it matches with where the baseplate shadow is falling. A small change but yay for realistic lighting :bulb:

**Comment by maxtron95** [comment]
@Foggalong A slightly off topic question but, What icon theme are you using in Inkscape.

**Comment by Foggalong** [comment]
@creepertron95 Just normal Numix! It includes icons for almost every toolbar icon in Inkscape :)

**Pull request merged**
