### PR TITLE
Icons and entry for renpy.

### LINKED ISSUE #2075: Icon for Ren'Py
Icon=renpy

renpy

This is the full-sized image from their website:

renpy
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/12935835-icon-for-ren-py?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by W-Floyd**
Fixes #2075
iconified_renpy

### CODE REVIEW

**Comment by palob** [comment]
I like the design but I think you can make it a bit bigger for better recognisability. It is smaller than 20x20 right now. The upper snake loops should have a width of 18/19/20px (or whatever it is going to be) so they can be aligned with the grid.

There is some strange stacking going on with those two paths buried in the "hole".
stacking

Actually you can have the upper snake part as just one path with the hole and the head shadow on top of it.

**Comment by W-Floyd** [comment]
I see what you mean, just not sure how I can get my loop and shadow to play well if I merge the paths.

**Comment by palob** [comment]
You need to do some path intersections/differences/exclusions but it is doable.

**Comment by W-Floyd** [comment]
Yeah, it's doable, I'll just need to bake the shadow on last thing.

**Review by Foggalong — CHANGES_REQUESTED** [review]
What @palob said :yum:

**Comment by W-Floyd** [comment]
lol Sorry for the delay, my tenancy to get distracted on different projects has kept me elsewhere.

**Comment by Foggalong** [comment]
No worries about it, there's not a rush on this. I was just checking though pull requests :)

**Comment by W-Floyd** [comment]
Just an FYI, I finish all my exams this coming Friday, fingers crossed I will be blocking out some time for icon work, since I'll have heaps of free time.

**Comment by W-Floyd** [comment]
Exams are done, going to finish this off :)

**Comment by W-Floyd** [comment]
Alrighty, I think this should be okay now.

iconified_renpy

**Comment by W-Floyd** [comment]
Alrighty, I think this should be okay now.

iconified_renpy

**Comment by palob** [comment]
The symbol is still a bit small though. I know this entails a lot of redesigning but do you think you can get it bigger?

**Comment by W-Floyd** [comment]
Sure, I'll do that tomorrow.

**Comment by W-Floyd** [comment]
image

Thoughts?

**Comment by palob** [comment]
What's the dimensions?

**Comment by W-Floyd** [comment]
25x20

**Comment by palob** [comment]
Maybe even bigger? 28x24 or something?

**Comment by W-Floyd** [comment]
Yeah, I think taller mostly. 

image

**Comment by W-Floyd** [comment]
This icon slipped under my radar, got around to redoing it.

How's this?

iconified_renpy

**Comment by palob** [comment]
Looks right now, have to check in detail later.

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
This looks good to me. @palob?

**Comment by bilelmoussaoui** [comment]
@W-Floyd The PR wasn't merged yet :p

**Comment by W-Floyd** [comment]
My bad, thought this was merged :P

**Comment by palob** [comment]
I have only access to my mobile so I can't have a deep look.
Looks big enough, if it's aligned nicely and the path stacking jumble is cleared I'd love to have it merged.

**Pull request merged**
