### PR TITLE
Add icon for 140 (game)

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon |
| --- | --- | --- |
|  original | 140-game circle 192 | 140-game square 192 |

I am not sure about the vertical alignment - independent opinions are much appreciated :)

Link to the steam store page: https://store.steampowered.com/app/242820/140/

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
Think the symbol looks more central if it's moved 1px right and 1px up

**Comment by mrmeszaros** [comment]
This looks better, although, in 24x24 the change makes the symbol blurry / not aligned.

140-game 192-96-48-24

**Comment by palob** [comment]
Is it the left/right or the up/down shift which causes the blurriness?

**Comment by mrmeszaros** [comment]
So for 24x24 the symbol boundaries should be on _even_ pixels of the 48x48 grid.
This means that because of the base 1px up square offset:
* on the circle both hurt
* on the square, the up helps, but the right hurts

I would suggest only doing 1px up on square (to increase to 2px up offset) - if we care about 24x24 alignment.

| Base | 1px up-right | Suggestion for 24x24 alignment |
|---|---|---|
|48 140-game circle 24 orig|48 140-game circle 24 upright|48 140-game circle 24 suggest|
|48 140-game square 24 orig|48 140-game square 24 upright|48 140-game square 24 suggest|

PS.: square baseplate is blurry in 24x24 - so this might not be worth changing.
PPS.: 16x16 cannot work with this symbol - something will misalign anyhow - this is a good example why _One Size Doesn't Fit All_ (#2545)

**Comment by Foggalong** [comment]
Yeah this is just another case of one size doesn't fit all. It sucks but unless there's some way we can easily tweak the symbol to make it work we shouldn't fine tune the icon to smaller sizes.

**Comment by mrmeszaros** [comment]
@Foggalong I did the changes You requested - is this ok?

| Base | 1px up-right |
|---|---|
| 140-game circle 48 base | 140-game circle 48 upright |
| 140-game square 48 base | 140-game square 48 upright |

**Comment by Foggalong** [comment]
@mrmeszaros Yeah those are good with me :+1:

**Comment by palob** [comment]
@Foggalong It's pushed already :)

**Review by palob — APPROVED** [review]

**Comment by mrmeszaros** [comment]
@Foggalong I just noticed that the symbol is simple enough to implement in `shine` and `utouch`.

- could You wait with the merge, or should I rather create a separate PR for those?
- do we have some guidelines for those themes?
- I did not find any templates - do we have plans on creating them?

**Comment by Foggalong** [comment]
@mrmeszaros Sure thing!

1. I won't wait on this PR because I'm not gonna hold back Circle & Square (maintained) for uTouch & Shine (unmaintained). We do welcome PRs from the community for those though so if you make one it'd be accepted :)
2. There are no guidelines for those icon themes which are still relevant, it's mostly just extrapolating from the existing icons.
3. No templates and no plans for us to officially create them. If at some point we do fix #2545 (which is what the templates were created for) it won't be fixed for uTouch or Shine without being driven primarily by the community.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
