### PR TITLE
Icons for Kitty

### LINKED ISSUE #4241: Icon Request: Kitty
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| Kitty| `kitty` | `kitty.desktop` | original |

Description: `Kitty is a Terminal Emulator that uses OpenGL for rendering`

Website: https://github.com/kovidgoyal/kitty

### PR DESCRIPTION
**Pull request by palob**
Fixes #4241

kitty-ci
kitty-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I'd sooner see a full colour icon for this. Maybe something ala [raccoon](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/raccoon.svg) but with a tiny terminal in front

**Comment by palob** [comment]
Somehow came up with this which however isn't your cute kitty but rather a wildcat.

kitty-test

**Comment by Foggalong** [comment]
That's amazing :joy: if we are going with that rough design, the terminal needs adjusting. Looks super awkward as a long rectangle

**Comment by palob** [comment]
So just a bit less wide?

**Comment by Foggalong** [comment]
Yeah :)

**Comment by palob** [comment]
Gonna push this in a second
kitty-ci
kitty-sq

**Comment by palob** [comment]
Fighting with some weird git problem.

**Comment by palob** [comment]
Ah, missed you merged master. Now it makes sense.

**Pull request closed without merging**
