### PR TITLE
Icons for PureRef

### PR DESCRIPTION
**Pull request by sprocketc**
https://www.pureref.com/

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

### CODE REVIEW

**Comment by sprocketc** [comment]
I added a symlink for .pur files.
Is there a template or a different project for file types? Should I remove the symlink?

**Comment by palob** [comment]
I suspect what you are looking for with the file icon is a mimetype icon. Those are implemented in the base theme https://github.com/numixproject/numix-icon-theme

**Comment by sprocketc** [comment]
Yes, that's what I mean. I removed the symlink.
Thank you.

**Review by palob — CHANGES_REQUESTED** [review]
Thanks for coming back.
Just 2 small things:

+ the white parts should be ``f9f9f9ff`` instead of full white
+ the symbol shadows should be full black (0L) with 10% opacity

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
