### PR TITLE
Icons for Life is Strange

### PR DESCRIPTION
**Pull request by BlueManCZ**
| Original icon | Circle icon | Square icon |
| --- | --- | --- |
| ![orig][orig] | ![circ][circ] | ![sqr][sqr] |

https://steamdb.info/app/319630/screenshots/

[orig]: https://user-images.githubusercontent.com/17854950/88675599-5f1f4c00-d0eb-11ea-81fd-f90b2c5c106b.png "Original"
[circ]: https://user-images.githubusercontent.com/17854950/88675613-62b2d300-d0eb-11ea-84f2-27857a9a515a.png "Circle"
[sqr]: https://user-images.githubusercontent.com/17854950/88675624-65152d00-d0eb-11ea-8393-c9affcc90be2.png "Square"

Snímek z 2020-07-28 16-00-39

### CODE REVIEW

**Comment by BlueManCZ** [comment]
I also made these drafts:

b a

Snímek z 2020-07-28 16-06-12

**Comment by maxtron95** [comment]
@BlueManCZ I like the icons with the photo framed around it. I was wondering about how to do the icons for Life is Strange 2 and Life is Strange: Before the Storm? The Steam ID for the game demo of this game is `329030`.

**Comment by BlueManCZ** [comment]
For [Before the Storm](https://steamdb.info/app/554620/screenshots/) icon we can use this `A` symbol:

Snímek z 2020-07-28 18-05-16
Snímek z 2020-07-28 18-07-10

For [Captain Spirit](https://steamdb.info/app/845070/screenshots/) we can make a symbol of what this guy wears on his face (#5746).



or remake logo: 

But with [Life is Strange 2](https://steamdb.info/app/532210/) I'm kinda lost. The only symbolic thing here is that `IS` in the banner.

obrazek


They use this logo:

**Comment by palob** [comment]
I'm leaning towards the icon without frame. If we opt for the frame it should be simplistic without the fringes.

**Comment by BlueManCZ** [comment]
I would go with what's currently pushed, for now. Does it need any edits @palob?

**Comment by palob** [comment]
Is there a way to turn lines very close to being horizontal into 1px wide aligned straight/bent lines without defacing the symbol too much?

**Review by Foggalong — CHANGES_REQUESTED** [review]
@BlueManCZ Would you like to sort the sequels here or in another PR?

**Comment by BlueManCZ** [comment]
I would prefer another PR if it isn't a problem for you.

**Review by Foggalong — APPROVED** [review]
Good with me then :+1: @palob?

**Comment by palob** [comment]
@BlueManCZ Is it possible to do something for the alignment of horizontal lines without deforming the symbol too much?

**Pull request merged**
