### PR TITLE
Add icon for Google Authenticator

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon |
| --- | --- | --- |
| google-authenticator | google-authenticator circle 192 | google-authenticator square 192 |

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
Again, the Square design for this really doesn't feel right. Maybe play with using an emblem for that rather than full baseplate

**Review by palob — COMMENTED** [review]
How about a shadow for the outer ring on the baseplate for Circle in order to keep the stacking impression of the original icon?

**Review by palob — COMMENTED** [review]
I think it works out well.

**Comment by mrmeszaros** [comment]
@Foggalong Added the drop shadows.
The square will probably need some more love (maybe some rounding?)

**Comment by palob** [comment]
How does a plain transfer of the Circle design to Square look like? With the square edges filled light grey.

**Comment by mrmeszaros** [comment]
* The versions A-G are with different inner radia
* The version H is the one with the inner circle
* I did not changed the _screws_ - that may affect how good they look

| A (1) | B (2) | C (3) |
|---|---|---|
| google-authenticator square 192 a | google-authenticator square 192 b | google-authenticator square 192 c |

| D (4) | E (5) | F (6) |
|---|---|---|
| google-authenticator square 192 d | google-authenticator square 192 e | google-authenticator square 192 f |

| G (7) | H (circle) |
|---|---|
| google-authenticator square 192 g | google-authenticator square 192 h |

**Comment by Foggalong** [comment]
I'm not gonna lie, I still hate this design. Maybe try some kind of symbol design?

**Comment by mrmeszaros** [comment]
@Foggalong totally agree with you.
After fiddling with it this much, I must say, none of these look good enough for numix.

I will try a symbol.

**Comment by mrmeszaros** [comment]
Created a symbol version with some background options:

| 01-04 | 05-08 | 09-12 |
|---|---|---|
| google-authenticator square 01-04 | google-authenticator square 05-08 | google-authenticator 09-12 |

I like 04-05 and 10-11-12.

**Comment by palob** [comment]
Symbol works well. I think the Circle icon should adapt the new design as well. I'm unsure about the baseplate colour. Maybe red?

**Comment by mrmeszaros** [comment]
@Foggalong totally agree with you.
After fiddling with it this much, I must say, none of these look good enough for numix.

I will try a symbol.

**Comment by mrmeszaros** [comment]
@palob So how about this red:

| Color | Circle | Square |
|---|---|---|
| `#cc5233` | google-authenticator circle 192 | google-authenticator square 192 |

**Comment by Foggalong** [comment]
Yup, go with the red!

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
