### PR TITLE
utilities-desktop-extra - Icon and entry for KDE Desktop Extra.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #2294

iconified_utilities-desktop-extra

### CODE REVIEW

**Comment by palob** [comment]
What made you opt out of just the circles?

**Comment by W-Floyd** [comment]
No reason really, I guess I can try it that way.

**Comment by W-Floyd** [comment]
iconified_utilities-desktop-extra

**Review by Foggalong — CHANGES_REQUESTED** [review]
Can you find a way to add some more colour to this? Possibly use a dark blue for the circles?

**Comment by W-Floyd** [comment]
Dark blue circles felt wrong, how about this?

iconified_utilities-desktop-extra

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
