### PR TITLE
Teamsql Icon

### LINKED ISSUE #4547: Icon Request: TeamSQL
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `TeamSQL`| `TeamSQL` | `TeamSQL.desktop` | original |

Description: `Cross-platform SQL Client
Simple, Effortless, Extensible and Completely FREE`

Website: https://teamsql.io/

### PR DESCRIPTION
**Pull request by Gabb1995**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

Closes #4547

### CODE REVIEW

**Comment by Gabb1995** [comment]
Will look at the guidelines again, as I have not used the correct shadow pixel and alignment.

**Review by palob — CHANGES_REQUESTED** [review]
Thanks for your contribution.
Please remove all filters. No filters are needed for Numix icons and it makes reviewing.
In order to get the baseplate right it is best to start with a template icomn and recolour the baseplate gradient.

**Comment by Gabb1995** [comment]
I did not change the baseplate, I used one of the other icons and changed the gradient color. I will change the color in next commit to follow the guidelines.

And I will also remove the filter and copy the symbol instead.

**Comment by Gabb1995** [comment]
filters have been removed, please recheck at your convenience :)

**Review by palob — CHANGES_REQUESTED** [review]
Here comes the next review.

+ Any horizontal/vertical lines need to be aligned with the pixel grid (``#`` key to show it in Inkscape). Otherwise the icon will be blurry.
notaligned

You can achieve an aligned symbol by rotating an aligned rectangle multiple times similar to this transparent stuff.
aligned

+ Please save the SVGs as Optimised SVGs with the following options.
optimised-svg-1
optimised-svg-2
optimised-svg-3

**Comment by Foggalong** [comment]
@palob There's a wiki page with the settings listed too :)

**Comment by Gabb1995** [comment]
I'm encountering a bug with inkscape and when I try to save as optimized svg it says I dont have scour installed even though I do.

Would it be fine if I send you guys the inkscape svg, then you save it optimized and send it back to me?

**Comment by palob** [comment]
Well, there's scour for Python 3 and scour for Python 2, maybe that's the issue.

Here on Arch Linux Inkscape ``0.92.x`` has ``python2-scour`` as optional dependency.

**Comment by Gabb1995** [comment]
I installed it on Windows at it worked fine.

**Comment by Gabb1995** [comment]
Both icons have been redone I redid the whole symbol from scratch, as before I was just tracing the original. Let me know if there are anymore changes to be done.

**Review by palob — CHANGES_REQUESTED** [review]
symbol + shadow on the Square icon should be moved up by 0.16 px otherwise things are fine now.

**Comment by Gabb1995** [comment]
Updated

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
Thanks for taking the time!

**Pull request merged**
