### PR TITLE
Icons for gaphor

### PR DESCRIPTION
**Pull request by palob**
https://github.com/gaphor/gaphor

gaphor
gaphor-ci
gaphor-sq

### CODE REVIEW

**Review by Foggalong — COMMENTED** [review]
Curious, why the change from quadrilaterals to triangles?

**Comment by palob** [comment]
Due to the fading gradient when looking from far enough back it looks like triangles.

**Comment by Foggalong** [comment]
@palob Ahh see it now. I like your thinking, but I feel like the three squares will be more recognisable

**Review by Foggalong — CHANGES_REQUESTED** [review]
@palob Ahh see it now. I like your thinking, but I feel like the three squares will be more recognisable

**Comment by palob** [comment]
gaphor-ci
gaphor-sq

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
