### PR TITLE
Icons for WeChat

### PR DESCRIPTION
**Pull request by maxtron95**
https://www.wechat.com/en/

For #5379 

wechat-ci
wechat-sq

### CODE REVIEW

**Review by palob — APPROVED** [review]
Thank you for your productivity. I'm snowed under at the moment so my reviewing might take some time.

**Comment by maxtron95** [comment]
@palob I wanted to let you know I might not be able to make icons for a week due to an outage.

**Comment by palob** [comment]
That sounds like a hefty outage. Or is it due to maintenance?

**Comment by maxtron95** [comment]
@palob A hurricane came through our area and downed power lines, causing outage and I had to stay somewhere else for a while. The electricity however, is starting to get restored but, our power line was unfortunately down, So I might not be making icons for a bit until that gets fixed.

**Comment by Foggalong** [comment]
@creepertron95 Hot damn, that's intense! No worries on not being able to make, we all just do this in our free time so there's no rush :slightly_smiling_face: 

@palob Similarly no sweat on being snowed under! I'm actually a bit more free this week so going to get as many PRs reviewed / edited and released as possible, hopefully clear through my backlog :grin:

**Pull request merged**
