### PR TITLE
Icons for Waterfox

### PR DESCRIPTION
**Pull request by really-need-an-api-key**
Icon for [Waterfox](https://www.waterfoxproject.org/), a fork of Firefox.
rcahc6ag
screenshot from 2016-12-10 19-24-16

I don't know what the filename should be, honestly. It has only recently been released in binary form for Linux, and my distro uses the Nightly icon for it. I'm fairly certain other distros don't have it in their PMs.

### CODE REVIEW

**Comment by palob** [comment]
The symbol on the Circle icon is definitely too big. The circlular part without the ear shouldn't exceed 30px X 30px. Furthermore all shapes should be aligned with the grid.

waterfox

How does the icon look like with colours reversed, i.e. dark on light blue?

**Review by Foggalong — CHANGES_REQUESTED** [review]
As @palob said, symbol size needs reducing

**Comment by really-need-an-api-key** [comment]
When I said I wanted to do it soon I didn't mean to leave it for so long. Sorry.
Going to start with aligning the square version. Can the ear stay outside the 30px circle? I figure it's a small element and it wouldn't violate the guidelines too much, but better to ask.
wf-sq
wf-sq-smaller

**Comment by palob** [comment]
The ear can exceed the 30x30 circle :)

**Comment by f1reflyyyylmao** [comment]
What is missing for this to get merged?

**Comment by Foggalong** [comment]
@f1reflyyyylmao Read the comments above, we detailed them there.

**Comment by mrmeszaros** [comment]
Hey @really-need-an-api-key , this is getting a year old soon.
May I take and finish it?

**Comment by f1reflyyyylmao** [comment]
I changed it and added a pull request for @really-need-an-api-key , but i think hes gone for good. Didn't answer me either.

**Comment by really-need-an-api-key** [comment]
Sorry. I completely dropped the ball on this one :( Looking around I see @mrmeszaros and @f1reflyyyylmao commited fixes to this icon in #3977. Shall i close this PR?

**Comment by palob** [comment]
No problem @really-need-an-api-key. You're welcome to contribute again.

**Pull request closed without merging**
