### PR TITLE
Refreshed Godot design

### LINKED ISSUE #4584: Update Godot Engine icon
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Godot Engine`| `godot` | `godot` | original |

Description: `Multi-platform 2D and 3D game engine.`

Website: `https://godotengine.org`

The current icon is outdated, using the old Godot Engine logo.

### PR DESCRIPTION
**Pull request by Foggalong**
Upstream branding update, but also switched from cutouts to symbols on symbols. Fixes #4584

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Works well but the symbol is a bit small imo. Did you try a bigger size?

**Comment by Foggalong** [comment]
I tried but it's difficult to keep the teeth proportions looking okay at 24-26 px. I can have another bash and report back with some examples

**Comment by Foggalong** [comment]
I've had a play with this but haven't yet found a 24px+ version which doesn't end up with an oddly warped mouth. Will keep trying but won't be offended if anyone else swoops in to have a bash.

**Comment by palob** [comment]
Is it the decision between a 1px or a 2px wide mouth stroke where something in between would be ideal?

**Comment by palob** [comment]
Currently in this PR:
godot0

I had a bash at it, 2 variants:
godot1
godot2

**Comment by palob** [comment]
The last one is the closest to the original icon but I like it the least. Maybe it could be bigger still?

**Comment by Foggalong** [comment]
The chin of the middle looks a bit fat but otherwise okay. The last is better, but those eyes make it look very off. It's an odd one to get working right with the proportions of the face

**Comment by palob** [comment]
This is variant 3 with asquint eyes similar to the original icon.
godot3

**Comment by palob** [comment]
Here's a bigger variant with the original icon on the left. Mouthline shouldn't be that close to the original probably for the sake of crispness.

godot4

**Comment by Foggalong** [comment]
[This one](https://github.com/numixproject/numix-core/pull/4892#issuecomment-505599353) is starting to look too large I think, though the mouth did come out really well. The eyes on that and [this one](https://github.com/numixproject/numix-core/pull/4892#issuecomment-504065963) also look better but make it look a little cross eyed because the pupil is so much smaller than the whites. Maybe [this](https://github.com/numixproject/numix-core/pull/4892#issuecomment-504065963) symbol size and shape but with the eyes from [variant 1 here](https://github.com/numixproject/numix-core/pull/4892#issuecomment-503983553)?

**Comment by palob** [comment]
Looks like this
godot-final

**Comment by Foggalong** [comment]
@palob That's the one, great work! What an unexpectedly difficult icon this turned out to be

**Comment by palob** [comment]
Pushed!

**Pull request merged**
