### PR TITLE
Icons for preferences-web-browser-identification

### PR DESCRIPTION
**Pull request by maxtron95**
For #2294 

128px-Oxygen480-apps-preferences-web-browser-identification svg

browser-id-ci
browser-id-sq

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Now that we may want to get rid of the full-baseplate globe web browser icons the globe could become a misrepresentation in future.
So perhaps just without it or a rectangle representing a photo?

**Review by palob — COMMENTED** [review]
Thank you for the changes.
I think it'll look cleaner with a consistent 2px margin.
margin

**Review by Foggalong — CHANGES_REQUESTED** [review]
Agreed; looks good now but will be better with that nice margin :+1:

**Comment by maxtron95** [comment]
@palob Do you mean margins as in the black bars on the bottom of the card?

**Comment by palob** [comment]
There should be a 2px padding, meaning any element should keep it 2px distance. Black & blue bars, globe. (For the what is shown above I reduced the globe size)

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
