### PR TITLE
Few android entries

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Few android icons entries from #3704
This PR adds entries for 
- VLC
- Wikipedia
- Steam
- Signal
- Amazon 
- File manager

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
@Foggalong Sadly we can't add a [ ] to a table on github markdown :(

**Comment by bilelmoussaoui** [comment]
@Foggalong We can keep using `_` instead of `.` for the android icon names and replace it later by the gen.py script. Few applications has `_` in their app id. Like firefox beta

**Comment by Foggalong** [comment]
@bil-elmoussaoui Let me know when you're finished adding to this :smile:

**Comment by bilelmoussaoui** [comment]
@Foggalong I will stop for now :p there's 50 entries just with this PR, i will add more once I have cleaned the icons names so it's easier to find the chrome apps icon names

**Review by Foggalong — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
Ready to merge

**Pull request merged**
