### PR TITLE
Add icon for Stellaris (Steam ID 281990)

### PR DESCRIPTION
**Pull request by heyhippari**
Fixes numixproject/numix-core#3202

### Original
original

### Proposal
stellaris_circle stellaris_square

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Hi, I'll have a look at the icons later. Can you please add a DB entry to the data.json file?

**Comment by palob** [comment]
Regarding the icons, can you please move the exhaust tip to X12 Y12 (Circle) and X12 Y13 (Square) and adjust the shadows respectively?

**Review by palob — APPROVED** [review]

**Comment by Foggalong** [comment]
@MrTimscampi This is a really nice looking icon, kudos!

**Comment by heyhippari** [comment]
@Foggalong Thanks :) I'm slowly getting better at working with Inkscape and coming up with designs. Still a lot to learn, though :p

**Pull request merged**
