### PR TITLE
Icons for HakuNeko

### PR DESCRIPTION
**Pull request by maxtron95**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

https://github.com/manga-download/hakuneko

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Hi, thanks for contributing. pixel-grid alignment is well done.
The following small issues need to be addressed:

+ The baseplate shouldn't have a solid colour but rather a linear gradient 10L lighter at the top. You can edit the template files to achieve this ans see how it's done.

+ There is some leftover stuff left to the Circle icon which needs to be removed
leftovers

+ There iris should expand further below the black path so that there is no outline in between. (transparancy for illustration)
iris

+ The following node of the black path should be straightened out and the on-symbol shadow should look like this (same for the right edge on the Square icon symbol)
straighten
+ The white path should expand a bit further below the black path such that the background doesn't shine through.
+ The symbol shadow should be merged into one path (or as few ones as possible)
+ Please save the file as Optimised SVG with options as shown here https://github.com/numixproject/numix-core/wiki/Optimise-Options

**Comment by maxtron95** [comment]
@palob I corrected all of the problems you mentioned for the icon.

**Review by palob — CHANGES_REQUESTED** [review]
Thank you, icons are fine now but there's still some cruft left to the Circle icon.

**Comment by maxtron95** [comment]
I guess I will see what @Foggalong says about this.

**Review by Foggalong — CHANGES_REQUESTED** [review]
@creepertron95 I say the same :P You've left some erroneous square shadows in the Circle icon and there's a few shapes which should probably be converted into paths instead (I assume in both).

**Comment by maxtron95** [comment]
OK, I (think I) fixed the Circle icon. But, I was wondering what shapes should be converted to paths?

**Review by palob — APPROVED** [review]
Thank you.

**Comment by palob** [comment]
@Foggalong ellipses to paths? I don't think that's needed for correct rendering, regardless of the engine (we've got ellipses in many icons, take up less memory compared to paths).

**Comment by palob** [comment]
@creepertron95 Could you please add the flatpak symlink for your flathab submission https://github.com/flathub/flathub/pull/1357?

**Comment by maxtron95** [comment]
It seems that the Travis CI build failed on my latest commit.

**Comment by palob** [comment]
Yeah, there needs to be a ``,``at the end of the ``root:...`` line before the symlink part kicks off.

**Review by palob — APPROVED** [review]

**Comment by maxtron95** [comment]
@palob Do you think I can close this and make a new pull request for this icon so I can make this icon in a separate branch to free my fork to start making pull requests for new icons or is it still possible to make branches based off my already existing master branch that has this icon in it?

**Comment by palob** [comment]
It is possible without doing so but sure, you can close it and open a new one so you don't need any git magic.

**Comment by maxtron95** [comment]
@palob I am going to close this now so I can reopen this as a new branch.

**Pull request closed without merging**
