### PR TITLE
baseplate gradient fixes

### PR DESCRIPTION
**Pull request by palob**
Fixed a few baseplates where the gradient oviously exceeded the 10L span.

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
If we're touching these, can we nuke the border on `league-of-legends` and switch it to use some less harsh colours? Struck me looking at it just now how harsh it looks

**Comment by palob** [comment]
You mean the outer rim?

**Comment by Foggalong** [comment]
@palob Aye, the outer yellow rim :)

**Comment by palob** [comment]
Pushed these
lol-ci
lol-sq

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
