### PR TITLE
Icons for usbguard

### PR DESCRIPTION
**Pull request by palob**
https://github.com/USBGuard/usbguard

usbguard-icon
usbguard-icon-ci
usbguard-icon-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
Can we get a dark navy blue for the symbol colour instead?

**Comment by palob** [comment]
This?
usbguard2

**Comment by Foggalong** [comment]
Yeah that's good with me! Just noticed, a wee bit naughty that they're using the Google G but not our place to change that I don't think :P

**Comment by palob** [comment]
Pushed for both.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
