### PR TITLE
Icons for sk1

### PR DESCRIPTION
**Pull request by palob**
https://github.com/sk1project/sk1-wx

sk1
sk1-numix

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I'm a bit unsure on the colors chosen here, they seems to clash a bit. So we can keep the ones from the original icons, possibly change the background?

**Comment by palob** [comment]
2 options with neutral baseplate:
sk1-alt

**Comment by Foggalong** [comment]
With with the dark grey, everything stands out much better there :)

**Comment by palob** [comment]
Where exactly? :)

**Comment by Foggalong** [comment]
Sorry, I meant push sk1-0 :)

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
