### PR TITLE
Add mkchromecast icon

### PR DESCRIPTION
**Pull request by W-Floyd**
iconified_mkchromecast

I have based the design from the Google provided Chromecast symbol, not the mkchromecast provided symbol, so it's slightly different.

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Symbol is fine but there is this cruft in the source again.

**Comment by W-Floyd** [comment]
ugh, right. Just remove it manually again then?

**Comment by palob** [comment]
Yep, it doesn't look broken afterwards or does it?

**Comment by W-Floyd** [comment]
Nah, it's always fine, so long as the opacity and colour is retained.

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
