### PR TITLE
Icons for mapton

### PR DESCRIPTION
**Pull request by palob**
https://github.com/trixon/mapton
mapton
mapton-ci
mapton-sq

Wondering if this is viable or I should stick to a standard earth design.

### CODE REVIEW

**Comment by maxtron95** [comment]
Well the description of the program is literally "Some kind of map application" on the github repo.

**Comment by maxtron95** [comment]
@palob You might have to change that design, due to #5153.

**Comment by palob** [comment]
But I for one haven't come up with an idea how to fix that one yet.

**Comment by maxtron95** [comment]
@palob Maybe a map design might work here?

**Review by Foggalong — CHANGES_REQUESTED** [review]
I like this _idea_ of a design, but I'm blocking icons like this until #5153 just is addressed to just decrease work down the line. I think this icon though highlights that maybe some of these redesigns would be beneficial to keep a design rooted in real-world continents rather than fantasy continents.

**Comment by palob** [comment]
Alternatively mapton could be implemented as a symlink in #5350.

**Comment by palob** [comment]
Since this is "some kind of map application"...

mapton2

I'm unsure about the buttons, what do you think @Foggalong ?

**Pull request merged**
