### PR TITLE
Icons for Polar Bookshelf

### PR DESCRIPTION
**Pull request by palob**
https://github.com/burtonator/polar-bookshelf

polar-bookshelf
polar-bookshelf-ci
polar-bookshelf-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
Can we switch the background for a very pale yellow?

**Comment by palob** [comment]
Maybe this?
polar2

**Comment by Foggalong** [comment]
@palob That works for me!

**Comment by palob** [comment]
Pushed.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
