### PR TITLE
Updated MS Office Suite Design

### LINKED ISSUE #4971: Icon Request: Microsoft Teams
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Microsoft Teams`| `teams` | `teams.desktop` | original |

Description: `Microsoft Teams is the hub for team collaboration in Office 365 that integrates the people, content, and tools your team needs to be more engaged and effective.`

Website: [`Microsoft Teams`](https://products.office.com/en-us/microsoft-teams/group-chat-software)

### LINKED ISSUE #5159: Update MS Office Icons
As @creepertron95 pointed out [here](https://github.com/numixproject/numix-core/pull/5133#issuecomment-606432270), since we made our MS Office icons the upstream designs have all been overhauled. We're already there Teams but it'd be nice to have the whole suite updated, especially Skype which is Linux compatible.

77995300-2748f900-72f1-11ea-860e-06ccd2261eb3

### PR DESCRIPTION
**Pull request by Foggalong**
Fxes #4971 (thanks @creepertron95) and fixes #5159, with updated designs for every application in the Microsoft Office suite. 

- Updated the design for all the suite
- New icon for Microsoft Teams
- Added a retro gold variant for Outlook
- Even chucked in a redesign for #512, even though the app is almost certainly :skull: 

Screenshot from 2020-07-04 18-17-12

For each of the icons (except Skype Call Recorder) I tried to go with a background which was a similar colour to what the symbol was but I'm not entirely sure that's worked in all the cases. Also considered switching them all to a dark grey to add an extra unifying element across the suite.

### CODE REVIEW

**Comment by Foggalong** [comment]
@palob Thoughts on having gradients specific to each app or having a unified one for the entire suite?

**Comment by maxtron95** [comment]
Could I add an MS Access Icon as well?

**Comment by Foggalong** [comment]
Sure, if you fancy making one go for it :+1:

For future reference should it ever come up, the process we follow for Windows icons requests in Numix (set way back in the mists of 2014 via #1086) is if soneone requests it and 4 people :+1:, we turn the request from a "wontfix" to a "hardcoded request". The office suite has always been a popular ask though so I don't think any harm having access in there too.

**Comment by palob** [comment]
Specific gradients definitely, I think the word background could be a bit brighter.

**Review by palob — DISMISSED** [review]

**Comment by Foggalong** [comment]
Playing with a brighter baseplate across some of the icons. Thoughts @palob?

Screenshot from 2020-07-13 18-21-50

**Comment by palob** [comment]
Better all around, for acces, excel and powerpoint I'd like to see an intermediate between old and new hue-wise.
Or is this only a perceived hue change and you didn't actually touch the H value?
The access icon maybe could have the symbol a bit brighter.

**Comment by Foggalong** [comment]
@palob Oh no they're all complete colour changes, I don't think any of the HSL values were carried over. Will try tweaking hues for Access, Powerpoint, and Excel :+1:

**Comment by palob** [comment]
@Foggalong Are you going to finish this (as far as I can see it's only the gradients) or should I take over?

**Comment by Foggalong** [comment]
@palob Go for it! It's unlikely I'll get round to it in the next week or two

**Comment by palob** [comment]
Done it!

**Comment by palob** [comment]
And merged! Time for a new release, I'd say.

**Pull request merged**
