### PR TITLE
Icons for Day of Infamy

### PR DESCRIPTION
**Pull request by BlueManCZ**
| Original icon | Circle icon | Square icon |
| --- | --- | --- |
|  | ![circ][circ] | ![sqr][sqr] |

https://steamdb.info/app/447820/screenshots/

[circ]: https://user-images.githubusercontent.com/17854950/88545771-b81faf00-d01b-11ea-8a6e-6a1049868b68.png "Circle"
[sqr]: https://user-images.githubusercontent.com/17854950/88545776-bb1a9f80-d01b-11ea-891e-bf5840893d20.png "Square"

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
I'm afraid there's too much fine-grained details, could you please simplify this a bit?

**Comment by maxtron95** [comment]
Maybe we could get an icon like the official game logo here?

**Comment by BlueManCZ** [comment]
@creepertron95 It is a possibility. But I think its an old logo design. I will try to simplify the current one, and I will see. Maybe I will have to use the older one.

**Comment by palob** [comment]
@BlueManCZ  Maybe just a polygon for the red-brownish path (no planes, just a few spikes for the fringes) and pristine letters without any fringes?

**Comment by BlueManCZ** [comment]
a
b

**Review by palob — CHANGES_REQUESTED** [review]
That's it, thank you, symbol on Circle can go down 1px.

**Comment by BlueManCZ** [comment]
I moved them down both to avoid a 2px difference. It looks fine for me, what do you think?

**Review by palob — APPROVED** [review]
Due to the fringed bottom it's OK but that 2px difference isn't relevant, users won't see the icons side by side.

**Pull request merged**
