### PR TITLE
50 square icons - Round 12

### PR DESCRIPTION
**Pull request by W-Floyd**
Name | Icon
--- | ---
mynotex | iconified_mynotex
mytourbook | iconified_mytourbook
myunity | iconified_myunity
naev | iconified_naev
nagstamon | iconified_nagstamon
nasc | iconified_nasc
natronicon256_linux | iconified_natronicon256_linux
nautilus-pastebin | iconified_nautilus-pastebin
nautilus-scripts-manager | iconified_nautilus-scripts-manager
navit | iconified_navit
neovim | iconified_neovim
~~nestopia~~ | iconified_nestopia
netease-cloud-music | iconified_netease-cloud-music
~~netgen~~ | iconified_netgen
nextcloud | iconified_nextcloud
nfoview | iconified_nfoview
nginx | iconified_nginx
nightingale | iconified_nightingale
nip2 | iconified_nip2
nodejs | iconified_nodejs
nomachine-icon | iconified_nomachine-icon
nootka | iconified_nootka
notepadqq | iconified_notepadqq
~~nsight~~ | iconified_nsight
numix-folders | iconified_numix-folders
nutty | iconified_nutty
nvvp | iconified_nvvp
nwn | iconified_nwn
nylas | iconified_nylas
obozrenie-short | iconified_obozrenie-short
~~ocrfeeder~~ | iconified_ocrfeeder
ogmrip | iconified_ogmrip
openclonk | iconified_openclonk
opencpn | iconified_opencpn
opendict | iconified_opendict
openlugaru | iconified_openlugaru
openmw-cs | iconified_openmw-cs
openmw | iconified_openmw
openra-editor | iconified_openra-editor
openra | iconified_openra
opensesame | iconified_opensesame
opensong | iconified_opensong
opensonic | iconified_opensonic
open-stage-control | iconified_open-stage-control
openteacher | iconified_openteacher
opentyrian | iconified_opentyrian
openyahtzee | iconified_openyahtzee
opsu | iconified_opsu
orange-canvas | iconified_orange-canvas
oregano | iconified_oregano

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Thanks again!

*nsight* and *ocrfeeder* need to have its internal shadows shifted.

**Comment by W-Floyd** [comment]
Name | Icon
--- | ---
nsight | iconified_nsight
ocrfeeder | iconified_ocrfeeder

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
netgen symbol & shadow need moving down by 2px. Gotta love a :small_red_triangle: 

Also nestopia needs moving down by 1px. I'm not sure why the symbol looks fine in Circle but not Square :man_shrugging:

**Comment by W-Floyd** [comment]
Sure, I'll do it in the morning. Thanks to you and @palob for taking the time to go through all my PRs :)

**Comment by W-Floyd** [comment]
Name | Icon
--- | ---
 | 
nestopia | iconified_nestopia
netgen | iconified_netgen

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
