### PR TITLE
Icons for Slime Rancher

### LINKED ISSUE #3877: Icon for Slime Rancher (Steam)
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Slime Rancher`| `steam_icon_433340` (appid for the demo: `622050`) | `Slime Rancher.desktop` | unityplayer 96x96|

Description: `Slime Rancher is a life simulation game, primarily revolving around exploration, catching slimes and tending to them, selling their plorts, etc.`

Website: http://slimerancher.com/ and http://store.steampowered.com/app/433340/Slime_Rancher/

### PR DESCRIPTION
**Pull request by maxtron95**
Fixes #3877

slime-rancher-ci svg
slime-rancher-sq svg

### CODE REVIEW

**Review by palob — COMMENTED** [review]
How does it look without the white outline?
Symbol on the Circle icon can go up 1px
Please ungroup the symbols after editing, will save some disk space.

**Comment by maxtron95** [comment]
I'm not sure but I think the icon looks weird without an outline
slime-rancher-ci svg

**Comment by palob** [comment]
Probably depends on the background colour. Do you know whether the outline is present ingame?

**Comment by maxtron95** [comment]
Seeing a screenshot of the slimes in-game, I don't see an outline present.
460ae9ca-ce8e-43f5-a7e3-65fee57a9868

**Comment by palob** [comment]
Such outlines are a bit un-Numixy, we try to avoid those where possible.
What's your opinion, @Foggalong?

In case we decide to keep it, you can safely remove the inner nodes of the white path.
white

**Review by Foggalong — CHANGES_REQUESTED** [review]
Yeah ditch the white outline, that's something we avoid for Numix designs. Also tabs need replacing with spaces in the JSON

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
This is good with me! @palob?

**Review by palob — CHANGES_REQUESTED** [review]
Needs some work now to avoid a fine outline due to multiple paths sharing the same edge.
The upper path should be reduced to something like this (made the bottom path translucent for demonstration)
outline

**Review by palob — APPROVED** [review]
Thank you.

**Pull request merged**
