### PR TITLE
Icon for SpiderOakONE

### PR DESCRIPTION
**Pull request by gregorydk**
New icon for SpiderOakONE to fit the SpiderOak set.

### CODE REVIEW

**Comment by palob** [comment]
You've got the semaphor changes in this one.

**Comment by gregorydk** [comment]
Grmbl. Always happens when I do 2 PR's in a row.

**Comment by palob** [comment]
Without requiring any git magic you can avoid this by having one repo directory on your local drive for each PR.

**Comment by gregorydk** [comment]
I'll wait to fix this after the others are merged.

**Comment by gregorydk** [comment]
Just tried something, don't know if this is a fix. Otherwise I'll have to redo the PR.

**Comment by Foggalong** [comment]
@gregorydk Yeah, you've still got multiple things floating around unfortunately. PR redo required

**Pull request closed without merging**
