### PR TITLE
Icon for Livestreamer Twitch GUI

### LINKED ISSUE #3414: Icon for Livestreamer Twitch GUI
Original icon:
icon

https://github.com/bastimeyer/livestreamer-twitch-gui

[Desktop Entry]
Type=Application
Name=Livestreamer Twitch GUI
GenericName=Twitch.tv browser for livestreamer
Comment=Browse Twitch.tv and watch streams in your videoplayer of choice
Keywords=livestreamer;twitch;
Categories=AudioVideo;
Exec=/usr/bin/livestreamer-twitch-gui
Icon=livestreamer-twitch-gui

### PR DESCRIPTION
**Pull request by palob**
Fixes #3414
livestreamer-twitch-gui

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
I think this icon can be used for Gnome twitch too. The other one is good but does not look like the original one

**Comment by palob** [comment]
Did GNOME Twitch change their icon?

**Comment by bil-elmoussaoui** [comment]
Their icon is https://github.com/vinszent/gnome-twitch/blob/master/data/icons/hicolor/48x48/apps/gnome-twitch.png

**Comment by palob** [comment]
We've got that, https://github.com/numixproject/circle-core/blob/master/icons/48/gnome-twitch.svg

**Comment by Foggalong** [comment]
@palob I think the symbol needs moving down 1px

**Comment by palob** [comment]
Should I move it down one the gnome-twitch icon as well?

**Comment by Foggalong** [comment]
@palob No - the symbol on GNOME Twitch is in a different position

**Comment by palob** [comment]
Pushed
livestreamer-twitch-gui

**Comment by Foggalong** [comment]
For consistency sake can we have GNOME Twitch 1px left so they're in the same position on both?

**Comment by palob** [comment]
Yep :+1:

**Pull request merged**
