### PR TITLE
Add icon for Typora

### LINKED ISSUE #3728: Icon for Typora
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Typora`| `typora` | `Typora` | typora |

**Description:** A minimal Markdown reading and writing app.

**Website:** https://typora.io/

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|typora original 192|typora circle 192|typora square 192|

Fixes #3728

### CODE REVIEW

**Comment by palob** [comment]
As slightly as the hash is tilted, how does it look with a straight one?

**Comment by mrmeszaros** [comment]
Initially I was thinking of making the **t** tilted, but now that you ask, I think better!
So thanks for the question:

| Tilted | Straight | Straight+SlimT |
|---|---|---|
|typora circle 192 b|typora circle 192 c|typora circle 192 d|

**Comment by palob** [comment]
Straight+SlimT it's for me!

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
Fixes #3728

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
