### PR TITLE
Icons for Tauon

### PR DESCRIPTION
**Pull request by palob**
https://github.com/Taiko2k/TauonMusicBox

tauonmb
tauonmb-ci
tauonmb-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
This design doesn't translate well to being used as an entire baseplate because it's emulating a disk record which looks weird on square. Would be fine if it was maybe a purple disk on a black background for both? Or a black disk on a purple background

**Comment by palob** [comment]
How about only changing it for Square?
tauonmb-sq

**Comment by Foggalong** [comment]
@palob Looks great! I'd be leaning toward changing it for both; I've been toying with the idea of starting to move away from full-baseplate designs in Circle to have greater consistency between it and Square. Firefox is the one that got me thinking on this because the FF Focus icon looks much nicer in terms of being a centred symbol than stretched to fill the space.

**Comment by palob** [comment]
Pushed
tauonmb-ci
tauonmb-sq

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
