### PR TITLE
Icons for osu!

### PR DESCRIPTION
**Pull request by maxtron95**
https://osu.ppy.sh

osu

osu-ci
osu-sq

Note: There is a linux version but, it is appimage only.

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Could you get this closer to the original? The font looks much like [Ubuntu](https://fonts.google.com/specimen/Ubuntu) probably preinstalled on your system

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
@palob I think you accidentally approved?

But also as my actual review, regardless of what font change a lighter pink background behind where the text cut-out is would be nice

**Comment by palob** [comment]
Looking on it again, whatever happens to the font, I think it should be less close to the circle limits.

**Comment by LiquidPL** [comment]
If I'm not wrong, [this](https://www.fontsquirrel.com/fonts/aller) is the font used in the original logo.

**Comment by palob** [comment]
Additional icon names 
``sh.ppy.osu``
``sh.ppy.osulazer``

**Pull request merged**
