### PR TITLE
Monogame pipeline icon

### PR DESCRIPTION
**Pull request by hmlendea**
The Monogame Pipeline icon that I promised :D

### CODE REVIEW

**Comment by palob** [comment]
Thanks! 

Two issues to clear and you've got you first icon merged.

+ Compared to existing icons the symbol is a bit big.
    Can you please reduce the symbol size to 26px X 26px?

+ The icon looks blurry because some horizontal aren't aligned with the pixel grid (``#`` key in Inkscape).
misalign

You can fix this (and get rid of unneeded nodes and small rough edges) by recreating the symbol using path combinations/subtractions of simple shapes like circles, (rounded) rectangles like shown below:

combination2
combination3

**Comment by Foggalong** [comment]
@HoratiuMl Are you able to complete the changes needed to have this merged? If not please enable the setting on the pull request which allows other people to commit changes to your branch

**Comment by HoratiuMl** [comment]
Hi. I checked "Allow edits from maintainers", is this the right setting?

**Comment by Foggalong** [comment]
@HoratiuMl Yeah, that's the one! Thanks :)

**Comment by hmlendea** [comment]
Thanks.

**Comment by Foggalong** [comment]
@HoratiuMl No problem!

**Pull request merged**
