### PR TITLE
Rocket League icon.

### PR DESCRIPTION
**Pull request by W-Floyd**
Positioning on circle feels odd no matter what I do, tell me if you want it changed.

iconified_steam_icon_252950

### CODE REVIEW

**Review by palob — APPROVED** [review]
As far as I can see this is the best possible position.

**Comment by W-Floyd** [comment]
iconified_steam_icon_252950

Forgot to keep the symbol colour something other than straight white.

**Review by palob — APPROVED** [review]

**Comment by mmhobi7** [comment]
I mean the circle is supposed to be a ball I think, so maybe add the car? or maybe a net

**Comment by W-Floyd** [comment]
@Aaahh I thought about it, but legibility at this size would not be good (snapping to 1px increments would make it very difficult). Feel free to give your interpretation of it though :smile:

**Comment by mmhobi7** [comment]
@W-Floyd It's just that at this point it looks like an antivirus

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
