### PR TITLE
More Square optimisations 2

### PR DESCRIPTION
**Pull request by palob**
More for #3482 + Circle optimisations

### CODE REVIEW

**Review by Foggalong — COMMENTED** [review]
<p></p>

**Review by Foggalong — CHANGES_REQUESTED** [review]
@palob How does `gtkhash` look with a symbol on symbol shadow? Something looks a bit odd as is for both Circle & Square

**Comment by palob** [comment]
Is this what you mean? Looks a bit more refined.

**Comment by Foggalong** [comment]
Aye, that's the ticket :+1:

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
Aye, that's the ticket :+1:

**Pull request merged**
