### PR TITLE
Icons for A Gummy's Life

### PR DESCRIPTION
**Pull request by maxtron95**
https://store.steampowered.com/app/585190/

agummylife

agl-ci
agl-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
design wise fine, there's just some noise I'rather not have included.

``color-rendering:auto;color:#000000;dominant-baseline:auto;font-feature-settings:normal;font-variant-alternates:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-variant-numeric:normal;font-variant-position:normal;image-rendering:auto;isolation:auto;mix-blend-mode:normal;opacity:.1;paint-order:stroke fill markers;shape-padding:0;shape-rendering:auto;solid-color:#000000;text-decoration-color:#000000;text-decoration-line:none;text-decoration-style:solid;text-indent:0;text-orientation:mixed;text-transform:none;white-space:normal``
should be replaced by ``opacity:.1``
and
``color-rendering:auto;color:#000000;dominant-baseline:auto;fill:#8e1239;font-feature-settings:normal;font-variant-alternates:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-variant-numeric:normal;font-variant-position:normal;image-rendering:auto;isolation:auto;mix-blend-mode:normal;paint-order:stroke fill markers;shape-padding:0;shape-rendering:auto;solid-color:#000000;text-decoration-color:#000000;text-decoration-line:none;text-decoration-style:solid;text-indent:0;text-orientation:mixed;text-transform:none;white-space:normal``
by ``fill:#8e1239``

**Comment by maxtron95** [comment]
I have a feeling that happens every time I convert a stroke into path.

**Comment by palob** [comment]
Yep, that's where it stems from.

**Review by palob — APPROVED** [review]
Thanks.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Between the highlighting and the way the end-fist has been designed I think this has ended up looking too 3D; the design isn't bad, but it'll stand out alongside other Numix icons. Is there a way we can tone that back some?

**Comment by maxtron95** [comment]
I think I can tone it down by removing highlights but I am not sure about the rest.

**Comment by palob** [comment]
Removing the inner highlights will tone down this a lot. Then there's the outline, maybe we need "air" between the windings.

**Review by Foggalong — APPROVED** [review]
This change works for me! @palob?

**Review by palob — APPROVED** [review]

**Pull request merged**
