### PR TITLE
Icons for Coffee

### PR DESCRIPTION
**Pull request by palob**
https://github.com/nick92/coffee

icon
coffee

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
Ahh damn, those colours don't really work well enough together to be main symbol and baseplate :/

**Comment by palob** [comment]
Here's the next draft
cofee2

**Comment by Foggalong** [comment]
Yeah I'm good with that :)

**Comment by palob** [comment]
Pushed.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
