### PR TITLE
add Half Life Deathmatch: Source icon and entry

### LINKED ISSUE #2840: Half-Life Deathmatch: Source
An icon is missing for Half-Life Deathmatch: Source
The icon name `steam_icon_360`
The default icon
steam_icon_360
An easy one, just need to recolor one of the other half life icons :+1:

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Fixes #2840

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original | half-life-deathmatch-source_circle| half-life-deathmatch-source_square|

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
@palob I just saw that the square icon still has some clippath on it, how should I remove it ?

**Comment by palob** [comment]
Ah yes, this needs to be removed. You can either just delete it in a text editor. Taking a clean Square icon, adjusting the baseplate and pasting in the symbol from Circle however might result in an even cleaner icon.

**Review by palob — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
@palob I have done that, hope it's okay. My Inkscape skills still need some work :p

**Comment by andia89** [comment]
@bil-elmoussaoui Can you make a test for that as well? Would be handy to sort them out before they get merged

**Comment by bilelmoussaoui** [comment]
@wa4557 Don't worry about that :) I'm going to push a new way for testing icons using a file with a regex expression per line including comments, metadata, clippaths and other things. I just need to finish it after my finals

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
