### PR TITLE
Added Brave Dev icons (Circle & Square) w/ symlink

### PR DESCRIPTION
**Pull request by KBeDevel**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Thank you for applying the canges. Technically it's all fine now. Can you however try out a light blue, moderately saturated baseplate gradient (maybe increased H value compared to the lion symbol colour as well)?

**Comment by KBeDevel** [comment]
### Would you prefer Any of these?

brave-dev_alt1     brave-dev_alt2     brave-dev_alt3

**Comment by palob** [comment]
Symbol colour is fine, I was talking about a tinted background :)

**Comment by KBeDevel** [comment]
Oh, my error hehe

**Review by Foggalong — CHANGES_REQUESTED** [review]
@KBeDeveloper Any update on this? :)

**Comment by KBeDevel** [comment]
Hello there, sorry for my procrastination. I made these:

brave-dev-ci                 brave-dev-sq

## [Update]
And I made this another one

brave-dev-ci-alt2

**Comment by palob** [comment]
The updated one it is :+1:

**Comment by KBeDevel** [comment]
Updated PR: #4967

**Comment by KBeDeveloper** [comment]
New PR: #4967

**Pull request closed without merging**
