### PR TITLE
Icons for Zoom

### LINKED ISSUE #5005: Zoom
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Zoom`| `Zoom.png` | `Zoom.desktop` |Original|

Description: `Video Calling`

Website: `https://zoom.us/`

### PR DESCRIPTION
**Pull request by maxtron95**
Fixes #5005

zoom-ci svg
zoom svg

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
+ Square icon has symbol+shadow sitting 1px too high and 0.29px too far to the right.
+ The symlinks need to be reordered.

**Review by palob — APPROVED** [review]
Icons are alright, but the ``us.`` symlink must be first.

**Comment by maxtron95** [comment]
I reordered the symlinks alphabetically and fixed the square icon.

**Comment by maxtron95** [comment]
I did fix that `us.` symlink but travis still is failing.

**Comment by palob** [comment]
The reason is you capitalised *zoom* in the root. All files in the core repo should be lowercase, ``Zoom`` needs to be implemented as symlink.

**Comment by maxtron95** [comment]
@palob I see, I will fix that after I make a pull request for Microsoft Teams.

**Comment by palob** [comment]
Hmm.

**Comment by palob** [comment]
Hmm, converted the tab before ``zoom`` to 4 spaces, still failing.

**Comment by maxtron95** [comment]
@palob Is the script case-sensitive to symlinks?

**Comment by palob** [comment]
Don't get the error message. Missing ``,`` but there is no line 21601.

**Comment by palob** [comment]
What did you edit ``data.json`` with? Did you change your editor, maybe some line break encoding stuff?

**Comment by maxtron95** [comment]
@palob I usually use Featherpad to edit the file, but I also have Notepadqq (flatpak) installed as well. I use MX Linux 19 as my linux distro if that helps.

**Comment by maxtron95** [comment]
@palob What do you use as a text editor on your system?

**Comment by palob** [comment]
Ah, one ``}`` is missing at the end. We should revert the ``Zoom`` decapitalisation then (in case there really is no lowercase ``zoom`` icon name) because ``zoom`` reads like an action icon name and having the Zoom app icon in place of a zoom button will look pretty bad.

**Review by palob — APPROVED** [review]

**Comment by maxtron95** [comment]
@palob There is an android port of this program. Should I go ahead and add the symlink for it?

**Comment by palob** [comment]
Aye, you can go ahead. This is a 1:1 symlink anyway.

**Comment by palob** [comment]
Is this just how it looks in GitHub or is there something wrong with spaces in the symlink section?

**Comment by Foggalong** [comment]
@palob Good catch, there was indeed an extra tab in there. Removed some other once I'd missed too

**Pull request merged**
