### PR TITLE
Icons for dotpict (Android)

### PR DESCRIPTION
**Pull request by maxtron95**
https://dotpict.net/
https://play.google.com/store/apps/details?id=net.dotpicko.dotpict

dotpict

dotpict-ci
dotpict-sq

### CODE REVIEW

**Comment by maxtron95** [comment]
@palob I think that is supposed to be a merge label.

**Review by palob — APPROVED** [review]
This looks cool but it's another pixel art design. But how to do it without?

**Comment by maxtron95** [comment]
@palob I'm not sure because the app is a pixel art editor and the entire interface looks like pixel art.

**Comment by Foggalong** [comment]
Another one to deal with in #5398, but chill for now :+1:

**Pull request merged**
