### PR TITLE
Square icon for syncthing-gtk

### PR DESCRIPTION
**Pull request by W-Floyd**
| Existing Circle icon | Square icon |
|  :-- | :-- |
| circle | square |

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Can you please save the file as 'Optimised SVG' from Inkscape?

I wonder if the symbol could go up 1px more. Can you try if it's any good?

**Comment by W-Floyd** [comment]
Done, the 1px shift does look better.
Now the question is if my signed commits will cause issues...

**Comment by palob** [comment]
They will. You'll have to close your PRs and open new ones without signed commits.

One more thing about the icon. Please remove the
```
<!-- Created with Inkscape (http://www.inkscape.org/) -->
```
comment line. For some reason it can cause issues with Qt.

**Comment by W-Floyd** [comment]
Hopefully this is good now.

**Comment by palob** [comment]
Yeah, looks like there's no signed commit left.

**Comment by W-Floyd** [comment]
Cool, hope it's all good to go then :)

**Review by palob — APPROVED** [review]

**Pull request merged**
