### PR TITLE
Icons for Friday Night Funkin'

### PR DESCRIPTION
**Pull request by maxtron95**
https://github.com/ninjamuffin99/Funkin

funkin-ci
funkin

### CODE REVIEW

**Comment by palob** [comment]
Is it a fish or a guy wearing a hat? Is there a way to have the 3 white shapes look like eyes + mouth?
Maybe the eyebrow line connecting the eyes + the line left to the mouth is needed?

**Comment by maxtron95** [comment]
@palob The icon is supposed to be the main character, the boyfriend from the game.

funkin-icon

**Comment by palob** [comment]
Ah, I see, I'd say just use those colours sans the outlines, will be much more recognisable.

**Comment by maxtron95** [comment]
I think the baseplate would have to changed as well because I think the new colors would clash with the current baseplate color.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Agree with both, add skin shape and change b/g colour - a dark purple might work?

**Pull request merged**
