### PR TITLE
Add contributions section to readme

### LINKED ISSUE #2647: How to contribute ?
I'd like to submit some icons instead of just requesting.

I have Inkscape, but I don't know where to start. Is there a template file somewhere that you have to start with ? Do I just modify an existing icon ?
Is there a list of guidelines to follow ?

Thanks :)
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28100990-how-to-contribute?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mymindstorm**
Continuing from #2656, fixes #2647.

@Foggalong Since you made a wiki page about contributing, should we just have it say "More info in the wiki" and link the wiki's contributing page?

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
@mymindstorm Aye, idea is to put the technical stuff in the wiki and just point people in that direction if they want to get involved.

It should probably go underneath "Hardcoded Icons" too because those two sections are linked.

**Comment by mymindstorm** [comment]
@Foggalong first change was made, but I'm not sure about moving it below hardcoded icons. I think that "Icon Requests" and "Contributions" should be next to each other. What about moving hardcoded icons to the top if you still think it should be moved? 

On a side note, I don't really see what hardcoded icons has to do with the artwork section. Doesn't it just fix icons that aren't themed because an application didn't use `/usr/share/icons/`? If so, wouldn't it make more sense to give it it's own section?

**Comment by mymindstorm** [comment]
Another idea: move "Hardcoded Icons" to the top of the "Artwork" section and rename it to "Unthemed Icons", and have it link [here](https://github.com/numixproject/numix-core/wiki/Unthemed-Icons).

**Comment by Foggalong** [comment]
@mymindstorm it's currently under artwork because that's the part of the repo that it links to: the icons themselves rather than the script for generating the themes. The idea of it being next to Icon Requests is that you should be checking if the icon is hardcoded when you make a request.

The restructuring you've suggested makes sense, but I think it's more an indication that the README will have to be rewritten after the wiki has been updated so it better compliments the information there. I'll merge this for now and we can come back to further changes after that has been done :+1:

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
