### PR TITLE
Icons for Besiege

### PR DESCRIPTION
**Pull request by maxtron95**
https://store.steampowered.com/app/346010/
jrxEuigkjfm88Yy0fsKrc3ckJmdpTwZFAih1k-hsQ2U

besiege-ci svg
besiege-sq svg

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
Much love for Besiege! I think this one would probably look better if the symbol was on a red banner as the original (though maybe with a simplified banner design) with a dark grey or black baseplate; the current symbol is fine but the icon looks a little bare as is.

**Comment by maxtron95** [comment]
@Foggalong Should I go ahead and make the symbol cracked like the original or would that be too detailed?

**Comment by Foggalong** [comment]
@creepertron95 I think yeah cracked would perhaps be too details and potentially not scale too well to smaller sizes

**Comment by maxtron95** [comment]
@palob @Foggalong Do you think this design is good enough and should I go ahead and push this to the PR.
besiege-redesign

**Comment by palob** [comment]
Yeah, looks ace, thank you!
Symbol should be placed 1px lower.

**Comment by Foggalong** [comment]
@creepertron95 Definitely push that, it looks great!

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
