### PR TITLE
Writefull and LayoutEditor (3D and TextEdit)

### PR DESCRIPTION
**Pull request by leoheck**
Pull request for Writefull.svg

Using Inkscape 0.92. Starting from an existing icon. I selected the ignore option at this time. What do you recommend to do for the next time? This makes any difference for the final product?
image

### CODE REVIEW

**Comment by leoheck** [comment]
Also addressing this issue https://github.com/numixproject/numix-core/issues/3571#issue-203773083

**Comment by bilelmoussaoui** [comment]
@leoheck Please separate each icon in a different PR

**Comment by leoheck** [comment]
Ok. Can you explain how to do that?

**Comment by bilelmoussaoui** [comment]
All you have to do is to create separate branch for each icon. For now all the icons you have added are on master(on your fork). Delete all of them from master. Create a branch for each icon, and commit to that branch instead of master. Once you've done go to your Github fork, and choose each branch, compare it with origin (the Numix core) and create a PR. Don't forget to add the icon entry on the json data file 👍

**Comment by leoheck** [comment]
Good @bil-elmoussaoui, can I put the 2 icons related with layout editor in the same branch?

**Comment by bilelmoussaoui** [comment]
It's better to keep each icon in a separate branch/PR. @palob What do you think about that?

**Comment by leoheck** [comment]
Oh, I just put them in the same PR, sorry. I didn't know these rules. @palob should I change this or is it fine this time?

**Comment by palob** [comment]
Better one per PR, now that we need to keep track of ``data.json`` an both Circle+Square.
Both layouteditor icons may go into one, might help with keeping the design in line.

About the Inkscape popup, I haven't investigated thoroughly (0.92.1 will adress it) but ``Ignore`` is what I go with. Our graphics aren't for printing.

**Comment by bilelmoussaoui** [comment]
@leoheck Also, both of  your PR doesn't include a square icon, can you get that fixed ?

**Comment by leoheck** [comment]
Sure. So I have to give both circle and squared? It will be nice to have these instructions in readme/wiki so you just need to point that for the next time. 

Some section like: `Pull Requests Rules`:
- Create a single icon for each pull request
- Add the icon in data.json
- Add both circle and squared version.

What do you think?

Also, what about giving just the icon emblem, and a custom script to generate the circle/square bg.
Or giving the circle icon and generating the squared version and vice-versa.

Also, it will be nice to have an icon template to start with.

**Comment by bilelmoussaoui** [comment]
For the templates, you can get them from here https://github.com/numixproject/numix-core/tree/master/templates, for the rest @Foggalong will give you a better answer!

**Comment by palob** [comment]
Yeah, we need to write a thorough icon design guide some time.

**Comment by leoheck** [comment]
This will be great because anyone can help without being rejected every time. Sometimes good people just lose the will as they discover the rules after each modification.

**Pull request closed without merging**
