### PR TITLE
Redesign openshot icon to match new logo.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #3858

iconified_openshot

Not sure about the baseplate colour, but I think it's alright.

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Does it look nicely at 16px?

**Comment by W-Floyd** [comment]
16, not that great. I'll be honest though, I don't think many icons can scale to 16 nicely :laughing:

iconified_openshot

**Comment by palob** [comment]
I think it looks somewhat busy. Maybe it's the red background which contrasts too much here.
How about dark blueish grey?

**Comment by W-Floyd** [comment]
iconified_openshot

Sorry, misread that as light blue!

As for the dark blue/grey, how about:

iconified_openshot

**Review by Foggalong — CHANGES_REQUESTED** [review]
That dark blue :heart:

**Comment by W-Floyd** [comment]
Again, forgot to push a commit :laughing:

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
