### PR TITLE
Icons for zdoom & gzdoom - fixes #3696

### LINKED ISSUE #3696: ZDoom and GZDoom
Popular Doom source code ports.

https://zdoom.org

`Icon=zdoom`

https://gzdoom.drdteam.org/index.php

`Icon=gzdoom`

A symlink to doomseeker.svg would suffice.

### PR DESCRIPTION
**Pull request by Foggalong**
| Name | Original icon | Circle icon | Square icon |
| --- | --- | :-- | :-- |
| zdoom | zdoom | zdoom-c | zdoom-s |
| gzdoom | gzdoom | gzdoom-c | gzdoom-s |

### CODE REVIEW

**Comment by palob** [comment]
Alignment isn't spot on where the **G** curves, should be corrected to something like this:
g


Makes it a good deal crisper. Same holds true for the **D** curve which is basically the **G** one mirrored.

I think the contour contrast is a bit weak. Maybe a darker grey (L128) or dark blue / dark red?

**Comment by Foggalong** [comment]
@palob I couldn't seem to find a dark blue which didn't end up blending into the drop shadow so went in the other direction; a lighter contour which matches the baseplate colour. It seems to be a bit more distinguishable at smaller sizes.

**Review by palob — APPROVED** [review]

**Comment by Foggalong** [comment]
This is being held back by a GitHub bug! Because it's my own PR I can't actually review it and all the checks show up green, but when I got to merge I get an error saying that it can't be merged because it hasn't been reviewed by Foggalong.

2017-12-27-085509_812x339_scrot
2017-12-27-085628_795x96_scrot

**Comment by palob** [comment]
I can't merge either :-(

**Comment by Foggalong** [comment]
I've contacted GitHub to see if it really is a bug or something I've set up wrong :P

**Comment by bilelmoussaoui** [comment]
@Foggalong Is it ready? I have the merge pull request button, I can try doing that? :)

**Comment by Foggalong** [comment]
Reply from GitHub:

> Thanks for writing in and I'm sorry for the trouble. This is currently a known issue that our engineering team is working on. In the meantime, our suggestion is to temporarily disable the option for requiring reviews from code owners in the protected branch settings. I can't promise an ETA of when this behavior will be resolved but we'll follow up once we have an update for you.

I've disabled the "requires reviews" option for now so that we can carry on with development, but will update y'all as I find out more :smile:

**Comment by bilelmoussaoui** [comment]
I wasn't able neither. I can't ask a review from you :( which is the reason why we can't merge this. I guess, it's an issue on Github. We can just remove this branch and merge it directly to master

**Comment by Foggalong** [comment]
@bil-elmoussaoui See above :)

**Pull request merged**
