### PR TITLE
Icons for Vital synth

### PR DESCRIPTION
**Pull request by really-need-an-api-key**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original | circle | square |

A synth plug-in for VST hosts (https://vital.audio), although there's also a standalone version with a launcher menu entry.

### CODE REVIEW

**Review by palob — APPROVED** [review]
Thanks for coming back!

**Comment by palob** [comment]
This also has the gradient issue. It should start at L22 at the bottom.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Gradient needs fixing

**Comment by really-need-an-api-key** [comment]
| circle | square |
| ------- | --------- |
| vital-circle | vital-square

**Review by palob — CHANGES_REQUESTED** [review]
The gradient range is alright now but with 16L at the bottom this would be (one of) our darkest icons. Could you please make this a 22->26 or 20->24 gradient?

**Comment by really-need-an-api-key** [comment]
Sure.
| circle | square |
| ------- | --------- |
| vital-circle | vital-square |

Made it go 22 - 26.

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
