### PR TITLE
Icon for Keybase

### LINKED ISSUE #3614: Icon Request - Keybase
Icon for [Keybase](https://github.com/keybase/client).

```
[Desktop Entry]
Name=Keybase
Exec=run_keybase
Icon=keybase
Terminal=false
Type=Application
Categories=Network;
StartupNotify=false
```

image

### PR DESCRIPTION
**Pull request by palob**
Fixes #3614

keybase-numix

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
Those high contrast colours only worked in the original because of the black border separating them, but we can't have that because it breaks design guidelines.

Maybe try using the lock from [this image in their readme](https://github.com/keybase/client#warnings)?

**Comment by palob** [comment]
Some new drafts:
keybase

**Comment by Foggalong** [comment]
3 :+1:

**Comment by palob** [comment]
Pushed.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
