### PR TITLE
Icons for Draw.io

### PR DESCRIPTION
**Pull request by noam09**
https://github.com/jgraph/drawio-desktop

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Hi,

thanks for your contribution.

* The rounded rectangles should be aligned with the pixel grid (``#`` in Inkscape)
bildschirmfoto vom 2018-12-30 17-59-36

* The symbol should be exactly 26 px X 24 px in size
* The baseplate gradient should only change the L value (top node 10L lighter)
* Please save the Icons as *Optimised SVGs* with presets as shown here https://github.com/numixproject/numix-core/wiki/Guidelines
* The Circle icon should have the symbol moved up 1px.

**Comment by noam09** [comment]
Hi @palob, I'm not sure if I got all the fixes mentioned. Please let me know if I missed something.

**Review by palob — CHANGES_REQUESTED** [review]
Thank you, it's better now but not quite there.
The boxes need to be slightly higher and narrower. See the transparent rounded rectangle (W 10px H 9px R 2px) for comparison.
boxes

**Review by palob — CHANGES_REQUESTED** [review]
Thank you, alignement is spot-on now.

The symbol shadow in the Square icon needs to be shifted 1px to the left. For Square the shadows are only shifted 1 px down generally.

Symbol+shadow should be moved up by even 1px more for the Circle icon to counter the illusion of it being off-centre.

**Review by palob — CHANGES_REQUESTED** [review]
There is one issue left now (sorry I didn't spot that earlier on): The baseplate gradient are wrong.
The baseplates should be 10L lighter on top.

The Square baseplate slipped somehow. It isn't located at Y1 anymore.

**Review by palob — CHANGES_REQUESTED** [review]
The Square baseplate needs to be moved up
base

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
