### PR TITLE
add appfilter.xml generation

### LINKED ISSUE #3452: Implement Full Android Support
_This issue was originally core-demo#3. It has been transferred here for archiving._

---

Foggalong, 14 Feb 2016

> To properly theme Android icons you need both the icon name and the activity name. We'd hoped to automate the lookup of the activity name but it seems there's no easy way to do this. Instead we'll have to make us of [this website](http://activities.tundem.com/) and then add them manually to the database file.

bil-elmoussaoui, 15 May 2016

> What do you mean by the icon name and the activity name? The android icons uses the activity name or i'm mistaken ?

Foggalong, 15 May 2016

> Icon name ≠ activity name on Android. Multiple activities can use the same icon name, so the system of using the same for both doesn't work perfectly. Android also doesn't support symlinks for icon themes so it requires carbon copies of the same file to be used.

bil-elmoussaoui, 8 Aug 2016 

> Maybe talking to the dev of the website if it's possible to provide an API so we can fix this easily?:) Or if he use Github Pages, this way we can use his database file

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Generate the appfilter.xml
Fixes #3452 

Here's an example
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<item component="ComponentInfo{com.adobe.reader}" drawable="acroread"/>
	<item component="ComponentInfo{com.amazon.mShop.android.shopping}" drawable="amazon_store"/>
	<item component="ComponentInfo{hu.donmade.menetrend.budapest}" drawable="budapest_public_transit"/>
	<item component="ComponentInfo{org_thoughtcrime_securesms}" drawable="chrome_bikioccmkafdpakkkcpdbppfkghcmihk_Default"/>
	<item component="ComponentInfo{com.dropbox.android}" drawable="dropbox"/>
	<item component="ComponentInfo{io.enpass.app}" drawable="enpass"/>
	<item component="ComponentInfo{com.facebook.orca}" drawable="fbmessenger"/>
	<item component="ComponentInfo{com.amaze.filemanager}" drawable="file_manager"/>
	<item component="ComponentInfo{org.mozilla.firefox}" drawable="firefox"/>
	<item component="ComponentInfo{org.mozilla.firefox_beta}" drawable="firefox_beta"/>
	<item component="ComponentInfo{com.justgetflux.flux}" drawable="fluxgui"/>
	<item component="ComponentInfo{com.foxit.mobile.pdf.lite}" drawable="foxit_reader"/>
	<item component="ComponentInfo{ch.ihdg.calendarcolor}" drawable="gcolor2"/>
	<item component="ComponentInfo{im.gitter.gitter}" drawable="Gitter"/>
	<item component="ComponentInfo{com.google.android.gm}" drawable="gmail"/>
	<item component="ComponentInfo{com_google_android_apps_authenticator2}" drawable="google_authenticator"/>
	<item component="ComponentInfo{com.android.chrome}" drawable="google_chrome"/>
	<item component="ComponentInfo{com.chrome.beta}" drawable="google_chrome_beta"/>
	<item component="ComponentInfo{com.google.android.apps.docs.editors.docs}" drawable="google_docs"/>
	<item component="ComponentInfo{com.google.android.talk}" drawable="google_hangouts"/>
	<item component="ComponentInfo{com.google.android.keep}" drawable="google_keep"/>
	<item component="ComponentInfo{com.google.android.apps.books}" drawable="google_play_books"/>
	<item component="ComponentInfo{com.google.android.apps.docs.editors.sheets}" drawable="google_sheets"/>
	<item component="ComponentInfo{com.google.android.apps.plus}" drawable="googleplus"/>
	<item component="ComponentInfo{com.imdb.mobile}" drawable="imdb"/>
	<item component="ComponentInfo{org.xbmc.kodi}" drawable="kodi"/>
	<item component="ComponentInfo{com.microsoft.office.excel}" drawable="ms_excel"/>
	<item component="ComponentInfo{com.microsoft.office.onenote}" drawable="ms_onenote"/>
	<item component="ComponentInfo{com.microsoft.office.powerpoint}" drawable="ms_powerpoint"/>
	<item component="ComponentInfo{com.microsoft.office.word}" drawable="ms_word"/>
	<item component="ComponentInfo{com.netflix.mediaclient}" drawable="netflix_desktop"/>
	<item component="ComponentInfo{om.microsoft.skydrive}" drawable="onedrive"/>
	<item component="ComponentInfo{com.skype.raider}" drawable="skype"/>
	<item component="ComponentInfo{com.Slack}" drawable="slack"/>
	<item component="ComponentInfo{com.soundcloud.android}" drawable="soundcloud"/>
	<item component="ComponentInfo{com.spotify.music}" drawable="spotify_client"/>
	<item component="ComponentInfo{com.valvesoftware.android.steam.community}" drawable="steam"/>
	<item component="ComponentInfo{com.teamviewer.teamviewer.market.mobile}" drawable="teamviewer"/>
	<item component="ComponentInfo{org.telegram.messenger}" drawable="telegram"/>
	<item component="ComponentInfo{com.instagram.android}" drawable="unity_webapps_instagram"/>
	<item component="ComponentInfo{com.viber.voip}" drawable="viber"/>
	<item component="ComponentInfo{org.videolan.vlc}" drawable="vlc"/>
	<item component="ComponentInfo{com.ninegag.android.app}" drawable="web_9gag"/>
	<item component="ComponentInfo{com.google.android.apps.inbox}" drawable="web_inbox"/>
	<item component="ComponentInfo{com.microsoft.office.outlook}" drawable="web_outlook"/>
	<item component="ComponentInfo{com.ideashower.readitlater.pro}" drawable="web_pocket"/>
	<item component="ComponentInfo{com.pushbullet.android}" drawable="web_pushbullet"/>
	<item component="ComponentInfo{com.twitter.android}" drawable="web_twitter"/>
	<item component="ComponentInfo{com.whatsapp}" drawable="web_whatsapp"/>
	<item component="ComponentInfo{org.wikipedia}" drawable="wikipedia"/>
	<item component="ComponentInfo{org.wordpress.android}" drawable="wordpress"/>
	<item component="ComponentInfo{com.wunderkinder.wunderlistandroid}" drawable="wunderlist"/>
	<item component="ComponentInfo{com.google.android.youtube}" drawable="youtube"/>
</resources>
```

What I did, is that I used the icon name that entry name (the icon that we can find in square/circle here in the core repo) as a drawable icon name name with replacing the "." with "_" and the "-" with "."
This way, the android entry in each icon must only provide the componentInfo.

The last step is to update the android entries to use ComponentInfo instead of the packageID

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
@Foggalong Should I update the data.json file with the correct entries in the same PR?

**Comment by Foggalong** [comment]
@bil-elmoussaoui Yeah just do that in this PR :)

**Review by paolorotolo — CHANGES_REQUESTED** [review]
Hey @bil-elmoussaoui! Nice work, how are we going automate fetching the correct Activity name in appfilter.xml?

For example, right now I see:
```xml
ComponentInfo{com.facebook.orca}
```
but the correct one is 
```xml
ComponentInfo{com.facebook.orca/com.facebook.orca.auth.StartScreenActivity}
```

**Comment by bilelmoussaoui** [comment]
@paolorotolo I will update the correct activities by myself. They are in the data.json file; currently few of them are incorrect, but as I said I'm going to take care of that within the same PR

**Comment by paolorotolo** [comment]
Awesome, keep us updated on this. As you said I'll merge as soon as the right Activities are available in ```data.json```.

**Comment by bilelmoussaoui** [comment]
Finally got the time to fix this one. @Foggalong Can be merged now :+1:

**Review by paolorotolo — APPROVED** [review]

**Comment by paolorotolo** [comment]
Looks good for me now, thanks!

**Comment by paolorotolo** [comment]
@Foggalong is it ok to merge this?

**Comment by bilelmoussaoui** [comment]
@paolorotolo @Foggalong The next step would be to review this PR and merge it 
https://github.com/numixproject/com.numix.icons_circle/pull/50
Once it's done, the main application could be moved to another repository and we can keep the circle/square and other themes repositories for building purposes :+1:

**Pull request merged**
