### PR TITLE
Icons for 23andMe (Android)

### PR DESCRIPTION
**Pull request by maxtron95**
https://play.google.com/store/apps/details?id=com.twentythreeandme.app

23andme

23andme-ci
23andme-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Design wise good to go, issues:

+ Files have plenty of SVG cruft left from the stroke conversion.

+ Square symbol should be moved 1px to the right

+ database entry should not have a ``,`` after the ``]``

**Comment by maxtron95** [comment]
What kind of SVG cruft am I looking for exactly?

**Comment by palob** [comment]
There's 4 big ``style`` text blocks. Each one has got only 1 relevant element, either ``opacity:.1`` or ``fill:#something``

**Review by palob — APPROVED** [review]
Thanks!

**Pull request merged**
