### PR TITLE
Improved World of Goo icons.

### PR DESCRIPTION
**Pull request by W-Floyd**
The existing World of Goo icons aren't strictly accurate to the game.

These icons are more accurate to the original icon, and look better in my opinion.

Existing:
iconified_steam_icon_22000

New:
iconified_steam_icon_22000

### CODE REVIEW

**Comment by palob** [comment]
Can you please try a coloured baseplate for better contrast?

**Comment by W-Floyd** [comment]
Sure, I'll try some options tomorrow.

**Comment by W-Floyd** [comment]
How about this?
iconified_steam_icon_22000

**Comment by palob** [comment]
That's better for sure.

**Comment by palob** [comment]
Can you please resize the wobbly circle to 25x24 and place it at X11 Y12?

Same thing for the eyes. I'd prefer them in exactly 11x12 and 9x9 and aligned with the grid.

**Comment by W-Floyd** [comment]
Sure.

**Comment by W-Floyd** [comment]
I also found the shadows on the eyes were using masking, so I cleaned that out.
iconified_steam_icon_22000

**Comment by palob** [comment]
Thanks, for some reason the symbol shadow has a lot of nodes around the eyes.

**Comment by W-Floyd** [comment]
I'll take a look soon then...

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
New design is vastly superior to what we had before, but the shadows on the eyes conflicts with how we handle shadow & light in the theme

**Comment by W-Floyd** [comment]
How's this?
iconified_steam_icon_22000

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
