### PR TITLE
Icons for 1C

### PR DESCRIPTION
**Pull request by maxtron95**
1C:
http://www.1c.com/
1cestart
1c-ci
1c-sq

1C Enterprise Dev Tools:
https://edt.1c.ru/
1c-edt
1c-edt-ci
1c-edt-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
The symbol should be stacked underneath the baseplate bezel
bezel

Is it on purpose that the hexagons don't use a constant stroke width and aren't symmetrical (in order to get them connect)?
Looking a bit askew.
hexagon

**Review by Foggalong — CHANGES_REQUESTED** [review]
A brighter baseplate for 1C too!

**Comment by maxtron95** [comment]
I did the hexagons to try to connect the cubes in the 1C EDT icon.

**Comment by palob** [comment]
Did you use the original icon as template, opening in Inkscape, resizing and stenciling by means of  transparent paths?
If not, maybe this could help.

**Comment by maxtron95** [comment]
@palob I improved the 1c icon and tried a new design for 1C EDT

1cedt-alt-ci

**Comment by palob** [comment]
That looks better but will it be recognisable without the hexagons?

**Comment by maxtron95** [comment]
@palob Is there anything I need to do to the 1C icons before they are approved?

**Comment by palob** [comment]
Since pixel grid alignment of lines/shapes >> pixel grid alignment of nodes, could you please build the hexagons using a constant 2px wide stroke? The horizontal lines should be aligned with the grid, the node coordinates don't need to be integers.

Is this possible or won't the hexagons meet then?

**Pull request merged**
