### PR TITLE
Icons for Micro

### PR DESCRIPTION
**Pull request by palob**
https://github.com/zyedidia/micro

micro
micro-ci
micro-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
Symbol needs moving 1px, 2px at most, to the left in Square to counteract the off-centre illusion

**Comment by palob** [comment]
1px
micro-1px

2px
micro-2px

**Comment by palob** [comment]
Yeah, 1px to the left is the way to go.

**Comment by palob** [comment]
@Foggalong Can't merge this one, might be because I can't overrule a "changes requested" review (can't approve my own PR) for my own PR.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
