### PR TITLE
distributor-logo-illumos - Add icons and entry for Illumos.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #2183

iconified_distributor-logo-illumos

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Maybe the baseplate could use the hue from the logo typeface as seen here https://wiki.illumos.org/display/illumos/illumos+Home?

**Comment by W-Floyd** [comment]
Like this?

image

Or just a shade of that?

**Comment by palob** [comment]
The colour I was referring to is #544a58 but this one might work as well. Definitely brighter though since the general illumos theme seems to "air brightness"

**Comment by W-Floyd** [comment]
Huh, I don't see that colour on the page. Doesn't matter, I like it anyway :laughing: 

Maybe this?

image

**Comment by palob** [comment]
Yes. Maybe the symbol could go 1px up on Circle?

**Comment by W-Floyd** [comment]
iconified_distributor-logo-illumos

**Review by palob — COMMENTED** [review]
Now that I see the effect how's the Square one with the symbol 1px up?

**Comment by W-Floyd** [comment]
Better as well. I think it's the light wing-tip that makes it work that way.

iconified_distributor-logo-illumos

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
