### PR TITLE
Icons for Altus

### PR DESCRIPTION
**Pull request by maxtron95**
https://github.com/amanharwara/altus

altus

altus-ci
altus-sq

### CODE REVIEW

**Comment by palob** [comment]
How would it look with just the bird on baseplate?
If we decide to keep this "squared circle" it needs to go 1px up and to the right.

**Comment by maxtron95** [comment]
Should I go ahead and ditch the "squared circle"?

**Comment by palob** [comment]
I'm excited to see whethr it works without, the symbol might be too small then.

**Review by Foggalong — COMMENTED** [review]
I'd be fine to merge this design but agreed, curious what one without the droplet design would look like

**Pull request merged**
