### PR TITLE
Add icon for Expand (game)

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Original icon | Circle icon | Square icon |
| --- | --- | --- |
|expand-game original 192|expand-game circle 192|expand-game square 192|

http://expandgame.com/

### CODE REVIEW

**Review by palob — APPROVED** [review]
Or does it look much better with the contour colour of the square set as baseplate colour?

**Comment by mrmeszaros** [comment]
With all this black and white it looks a bit plain.
Here are some options I came up with:

| A (current) | B | C |
|---|---|---|
| expand-game 192-96-48 a | expand-game 192-96-48 b|expand-game 192-96-48 c|

**Comment by palob** [comment]
What I meant was a colour arrangement which picks up all original colours but avoids a whitish baseplate and the contour on the square.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Yeah, would like to see this with @palob's suggestion first. With the border it looks kinda weird

**Comment by mrmeszaros** [comment]
Agreed - here's the next iteration - now with the red that is also included in the game (called _monza_, apparently):

| v1 | v2 | v3 |
|---|---|---|
| expand-game circle 192 v1 | expand-game circle 192 v2 | expand-game circle 192 v3 |

**Comment by palob** [comment]
v3 :+1:

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
