### PR TITLE
Some symlinks

### PR DESCRIPTION
**Pull request by palob**

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
is there something to do, to get this merged?

**Comment by palob** [comment]
We are restructuring things a bit behind the scenes but a new release is on the horizon!

**Comment by Stunkymonkey** [comment]
i am thrilled for a new release, because a long time only a few changes occured

**Comment by palob** [comment]
Great to hear we've got some fans out there.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
