### PR TITLE
Square icon for chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Default.

### PR DESCRIPTION
**Pull request by W-Floyd**
iconified_chrome-bikioccmkafdpakkkcpdbppfkghcmihk-default

### CODE REVIEW

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
Thank you so much for giving us a helping hand with Square porting :+1: 

If you are going to do even more Square ports, feel free to collect some in one PR.

**Comment by W-Floyd** [comment]
No problem, it's a lot easier than coming up with original designs :)
Sure, that might be best, seeing as PRs seem to have adequate between submission and merging.

**Comment by W-Floyd** [comment]
Didn't realise, but this, and a number of my other PRs, are already in #3752.
None of the icons are mentioned by name in that PR, so searching failed me. Perhaps that should be added?
Up to you whether you want to close this or not, but I'll avoid any of those others for the time being.

**Comment by palob** [comment]
Ah yes, that's gonna clash but we'll sort it out.

**Pull request merged**
