### PR TITLE
Found and optimised any files with "Created with Inkscape"

### PR DESCRIPTION
**Pull request by W-Floyd**
Don't know if I did the right thing, but I went through and optimized any files that contained "Created with Inkscape".

### CODE REVIEW

**Comment by palob** [comment]
Which commands did you run?

**Comment by andia89** [comment]
I would prefer something that deletes only the appropriate line, honestly.

`find . -type f -iname *.svg -exec sed -i '#<!-- Created with Inkscape (http://www.inkscape.org/) -->#d' {} +`

should also do the trick (the string needs to be escaped properly probably)

**Comment by W-Floyd** [comment]
Hmm. I believe it was scour, and sed to remove the Inkscape bit. However,
I've been seeing some different instructions on what settings to use, so I
may redo this. I guess the question is if it's even necessary, and welcome.
If it's not, then feel free to close this down.

**Comment by palob** [comment]
Actually all Numix Circle icons are already SVGcleaned.
Numix Square icons don't need to be before #3482.

Scour must be run with the options 
```
--disable-style-to-xml --enable-viewboxing --enable-comment-stripping
```
in order not to harm Inkscape editability. 

Generally speaking [``svgcleaner``](https://github.com/RazrFalcon/svgcleaner) is more robust and provides better cleaning as well as finer tuning options.

**Pull request closed without merging**
