### PR TITLE
100 square icons - Round 1

### PR DESCRIPTION
**Pull request by W-Floyd**
Name | Icon
--- | ---
distributor-logo-android | iconified_distributor-logo-android
distributor-logo-antergos | iconified_distributor-logo-antergos
distributor-logo-backbox | iconified_distributor-logo-backbox
distributor-logo-bodhi | iconified_distributor-logo-bodhi
distributor-logo-centos | iconified_distributor-logo-centos
distributor-logo-connochaetos | iconified_distributor-logo-connochaetos
distributor-logo-cub | iconified_distributor-logo-cub
distributor-logo-dragonflybsd | iconified_distributor-logo-dragonflybsd
distributor-logo-elementaryos | iconified_distributor-logo-elementaryos
distributor-logo-endlessos | iconified_distributor-logo-endlessos
distributor-logo-freebsd | iconified_distributor-logo-freebsd
distributor-logo-ghostbsd | iconified_distributor-logo-ghostbsd
distributor-logo-guixsd | iconified_distributor-logo-guixsd
distributor-logo-handylinux | iconified_distributor-logo-handylinux
distributor-logo-kaos | iconified_distributor-logo-kaos
distributor-logo-kdeneon | iconified_distributor-logo-kdeneon
distributor-logo-mageia | iconified_distributor-logo-mageia
distributor-logo-maui | iconified_distributor-logo-maui
distributor-logo-netbsd | iconified_distributor-logo-netbsd
distributor-logo-netrunner | iconified_distributor-logo-netrunner
distributor-logo-nixos | iconified_distributor-logo-nixos
distributor-logo-openbsd | iconified_distributor-logo-openbsd
distributor-logo-openmandriva | iconified_distributor-logo-openmandriva
distributor-logo-parabola | iconified_distributor-logo-parabola
distributor-logo-parsix | iconified_distributor-logo-parsix
distributor-logo-pcbsd | iconified_distributor-logo-pcbsd
distributor-logo-qubes | iconified_distributor-logo-qubes
distributor-logo-rhel | iconified_distributor-logo-rhel
distributor-logo-rosa | iconified_distributor-logo-rosa
distributor-logo-sabayon | iconified_distributor-logo-sabayon
distributor-logo-salix | iconified_distributor-logo-salix
distributor-logo-scientificlinux | iconified_distributor-logo-scientificlinux
distributor-logo-slackware | iconified_distributor-logo-slackware
distributor-logo-solus | iconified_distributor-logo-solus
distributor-logo-tanglu | iconified_distributor-logo-tanglu
distributor-logo-trisquel | iconified_distributor-logo-trisquel
distributor-logo-ubuntu-gnome | iconified_distributor-logo-ubuntu-gnome
distributor-logo-ubuntu-mate | iconified_distributor-logo-ubuntu-mate
distributor-logo-windows | iconified_distributor-logo-windows
distributor-logo-xubuntu | iconified_distributor-logo-xubuntu
distributor-logo-zenwalk | iconified_distributor-logo-zenwalk
distributor-logo-zorin | iconified_distributor-logo-zorin
gnome-power-manager | iconified_gnome-power-manager
mediainfo | iconified_mediainfo
multimedia-audio-player | iconified_multimedia-audio-player
obs | iconified_obs
openxcom | iconified_openxcom
peek | iconified_peek
processing-pde | iconified_processing-pde
sparkleshare | iconified_sparkleshare
sqlitebrowser | iconified_sqlitebrowser
steam_icon_248570 | iconified_steam_icon_248570
steam_icon_287980 | iconified_steam_icon_287980
telegram | iconified_telegram
userinfo | iconified_userinfo
warmux | iconified_warmux
warspear | iconified_warspear
web-9gag | iconified_web-9gag
web-bandcamp | iconified_web-bandcamp
webby | iconified_webby
webcamoid | iconified_webcamoid
web-delicious | iconified_web-delicious
web-duckduckgo | iconified_web-duckduckgo
webissues | iconified_webissues
web-pocketcaster | iconified_web-pocketcaster
web-pushbullet | iconified_web-pushbullet
web-trello | iconified_web-trello
web-whatsapp | iconified_web-whatsapp
whatsie | iconified_whatsie
wifiguard | iconified_wifiguard
wings3d | iconified_wings3d
wolf4sdl | iconified_wolf4sdl
wolfenstein | iconified_wolfenstein
wolfenstein-the-new-order | iconified_wolfenstein-the-new-order
wordpress | iconified_wordpress
wxcas | iconified_wxcas
wxformbuilder | iconified_wxformbuilder
wxglade | iconified_wxglade
wxmaxima | iconified_wxmaxima
wxmedit | iconified_wxmedit
wyrmsun | iconified_wyrmsun
xcaliber | iconified_xcaliber
xcircuit | iconified_xcircuit
xcos | iconified_xcos
xdman | iconified_xdman
xfce4-panel-restart | iconified_xfce4-panel-restart
xfdashboard | iconified_xfdashboard
xilinx-ise | iconified_xilinx-ise
xmlcopyeditor | iconified_xmlcopyeditor
xneur | iconified_xneur
xt7-player-mpv | iconified_xt7-player-mpv
xware-desktop | iconified_xware-desktop
yacreader | iconified_yacreader
yacreader-library | iconified_yacreader-library
yagf | iconified_yagf
yandex-browser-beta | iconified_yandex-browser-beta
yate | iconified_yate
yokadi | iconified_yokadi
youdao-dict | iconified_youdao-dict
zandronum | iconified_zandronum
zanshin | iconified_zanshin
zathura | iconified_zathura
zbstudio | iconified_zbstudio

### CODE REVIEW

**Comment by W-Floyd** [comment]
For future reference, here's how I unsign all commits on a branch since master:
```
git rebase --exec 'git commit --amend --no-edit -n --no-gpg-sign' -i master 
```

**Review by palob — APPROVED** [review]
Impeccable!

**Comment by W-Floyd** [comment]
Phew!

**Review by Foggalong — CHANGES_REQUESTED** [review]
Very small tweak to make: could you move the symbol & symbol shadow in zuluMount up 1px so that the `Y` values for Circle & Square are 10px & 11px respectively.

I'd not noticed it before but because the key is so bottom heavy it has the illusion of being off centred which the above change should remedy.

screenshot_2017-07-21_14-18-47

**Comment by W-Floyd** [comment]
I notice this icon isn't in the preview list above (since I cherry picked this branch), hope there aren't too many like that...
iconified_zulumount

**Comment by Foggalong** [comment]
@W-Floyd I looked through the actual icons not the preview (though the previews are helpful for a quick oversight too). There were a few missing from the previews in this PR, but none of those had problems so I wouldn't worry.

**Review by Foggalong — APPROVED** [review]

**Comment by W-Floyd** [comment]
Okay, cool. I include them because they look nice, but it's good to know you're checking everything :)

**Comment by palob** [comment]
The sparkleshare icon is buggy and doesn't use symbol+shadow from Circle, should be fixed down the road. That sai, for Circle symbol+shadow need to be moved 1px up anyway.

**Comment by W-Floyd** [comment]
Ah yeah, I remember that. I fixed it in #3827, so I'll shift it there.

**Pull request merged**
