### PR TITLE
Icons for GNOME Keysign

### PR DESCRIPTION
**Pull request by palob**
https://wiki.gnome.org/Apps/Keysign

gnome-keysign
gnome-keysign-ci
gnome-keysign-sq

### CODE REVIEW

**Comment by RyuzakiKK** [comment]
One of the GNOME Keysign dev here.
@palob the icon you made looks awesome! It is way better than the very basic we have right now.

If you are ok with it, we'd like to replace our icon with yours and credit you in the about of the program (once we add this feature).

**Comment by palob** [comment]
Sure thing.

Given that the GNOME/Adwaita app icons [are being redesigned](https://gitlab.gnome.org/GNOME/Initiatives/issues/2) I could even make one in accordance with the new guidelines and in the appropriate size.

**Comment by RyuzakiKK** [comment]
wow thanks, that would be fantastic.

**Review by Foggalong — APPROVED** [review]

**Comment by RyuzakiKK** [comment]
@palob are you still interested in doing an icon in accordance to the GNOME guidelines? Otherwise we can just pick the one you did here for numix.

**Comment by palob** [comment]
Sure, I'm just a bit pressed for time currently. Is there any deadline to meet? I'll open a merge request against your GitLab repo.

**Comment by RyuzakiKK** [comment]
Ah no don't worry. I wrote only to check if you were still interested.
We did a new release few days ago and we plan to change the icon before the next one (the 1.0 release), but maybe it will take another month or so.

**Comment by RyuzakiKK** [comment]
Hi @palob I tried to contact you with an email but I got a delivery error.
Anyway I wanted to let you know that soon (1-2 weeks maybe) we will release GNOME-Keysign 1.0 and we'd love to use a new icon for it.
For this reason I'm asking if you have time these days to create an icon for it that follows the GNOME guidelines.

Thank you and sorry to bother you again.

**Comment by palob** [comment]
Luckily it is the next 2 weeks when I will have more time. I will acquaint myself with the GNOME 3.32 icons HIG and open a merge request against your Gitlab instance

**Pull request merged**
