### PR TITLE
Icons for Forager

### PR DESCRIPTION
**Pull request by maxtron95**
https://store.steampowered.com/app/751780/

forager

forager-ci
forager-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Could you please remove the stroke-path conversion SVG cruft blocks?

**Review by palob — APPROVED** [review]
This is good to go if the outline is OK.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Yeah the outline stops this being Numixy. There are a couple of other tweaks I would have suggested like changing the shape of the eyes slightly, making the mouth the open variant, and removing the bottom shadow (it looks weird without the outline) buuuuut....

**Comment by Foggalong** [comment]
... in making an icon to compare it without the outline I ended up getting carried away and making those changes. It's just too cute an icon :heart_eyes: 

 forager-circle forager-square

**Review by palob — APPROVED** [review]

**Comment by maxtron95** [comment]
@Foggalong Your icon definitely looks better than mine.

**Pull request merged**
