### PR TITLE
Add icon for Cryptomator

### LINKED ISSUE #3926: Icon for Cryptomator
`Cryptomator`
`Icon=/opt/Cryptomator/Cryptomator.png`
 `Cryptomator.desktop`

cryptomator-logo

Description: Free client-side encryption for your cloud files.

Website: https://cryptomator.org/

### PR DESCRIPTION
**Pull request by mrmeszaros**
| Circle icon | Square icon |
| :-- | :-- |
| cryptomator a circle 192 | cryptomator a square 192 |

Fixes #3926

### CODE REVIEW

**Comment by mrmeszaros** [comment]
Hi, so I thinking of a 'beefy' version. what do you think?

| Normal | Beefy |
|:-:|:-:|
| cryptomator a circle 192 | cryptomator b circle 192 |

**Comment by palob** [comment]
Beefy nails it :+1:

**Review by Foggalong — COMMENTED** [review]
The shadow doesn't appear to be showing up on the GitHub preview. Not sure but it might be a sign of something being wrong with it (@palob?)

**Comment by mrmeszaros** [comment]
@Foggalong my bad - forgot to commit the drop shadow.
Added it with the more beefy arms.
The code needs some optimization. If the symbol looks OK, I will remove these scaffoldings

**Comment by palob** [comment]
Yeah, apart from the shadow path it's all fine.

**Comment by palob** [comment]
There's still a path inside the shadow path. I think you can get rid of it by just performing *Path > Union* on it.

**Review by palob — COMMENTED** [review]
There's still two loops which shine through in Qt.
loops

**Comment by mrmeszaros** [comment]
Yeah, right - forgot about that. Should be fixed now :smile: 
Also:
* does **Qt** default to a different **fill-rule** (the default should be _nonzero_)?
* or is it an implementation bug?

**Comment by palob** [comment]
AFAIK QtSVG still only implements TinySVG, a subset of the full SVG standard.
Stacked opacities add up with Qt which I actually think is logic.

**Comment by mrmeszaros** [comment]
Ok, good to know - I will try to optimize for that standard in the future.
Adding up stacked opacities is the logical way :+1:

**Comment by mrmeszaros** [comment]
@palob I amended my last commit, so this is done.

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
