### PR TITLE
100 square icons - Round 3

### PR DESCRIPTION
**Pull request by W-Floyd**
All (excluding symlinked) steam icons are now covered by this :)

Name | Icon
--- | ---
remotebox | iconified_remotebox
retext | iconified_retext
ricin | iconified_ricin
ricochet | iconified_ricochet
ring | iconified_ring
rkward | iconified_rkward
~~robocode~~ | iconified_robocode
roccat | iconified_roccat
rocketchat | iconified_rocketchat
rocs | iconified_rocs
rodeo | iconified_rodeo
roger | iconified_roger
rosegarden | iconified_rosegarden
roxterm | iconified_roxterm
rsibreak | iconified_rsibreak
rtcw | iconified_rtcw
rubyripper | iconified_rubyripper
runescape | iconified_runescape
sabnzbdplus | iconified_sabnzbdplus
saga | iconified_saga
sage-notebook | iconified_sage-notebook
samplv1 | iconified_samplv1
sayonara | iconified_sayonara
scforgedalliance | iconified_scforgedalliance
sc_ide | iconified_sc_ide
~~scilab~~ | iconified_scilab
~~scinotes~~ | iconified_scinotes
scorched3d | iconified_scorched3d
scudcloud | iconified_scudcloud
sdl-ball | iconified_sdl-ball
seafile | iconified_seafile
securecrt | iconified_securecrt
securefx | iconified_securefx
selektoricon | iconified_selektoricon
serialplot | iconified_serialplot
setbfree | iconified_setbfree
sflphone | iconified_sflphone
shadowsocks-qt5 | iconified_shadowsocks-qt5
shotcut | iconified_shotcut
shuriken | iconified_shuriken
silverjuke | iconified_silverjuke
simplenote | iconified_simplenote
simplesok | iconified_simplesok
simsu | iconified_simsu
sirikali | iconified_sirikali
skrooge | iconified_skrooge
slgui | iconified_slgui
slimevolley | iconified_slimevolley
~~slingscold~~ | iconified_slingscold
smartsynchronize | iconified_smartsynchronize
sm-ssc | iconified_sm-ssc
soapui | iconified_soapui
solfege | iconified_solfege
soundnode | iconified_soundnode
spark | iconified_spark
spice | iconified_spice
splashtopstreamer | iconified_splashtopstreamer
sportstracker | iconified_sportstracker
sqlectron | iconified_sqlectron
sqlitestudio | iconified_sqlitestudio
squirrel-sql | iconified_squirrel-sql
sr-editor | iconified_sr-editor
starfighter | iconified_starfighter
steam_icon_10500 | iconified_steam_icon_10500
steam_icon_112100 | iconified_steam_icon_112100
steam_icon_115100 | iconified_steam_icon_115100
steam_icon_1510 | iconified_steam_icon_1510
steam_icon_200510 | iconified_steam_icon_200510
steam_icon_209190 | iconified_steam_icon_209190
steam_icon_214770 | iconified_steam_icon_214770
steam_icon_215080 | iconified_steam_icon_215080
steam_icon_215160 | iconified_steam_icon_215160
steam_icon_217690 | iconified_steam_icon_217690
~~steam_icon_219680~~ | iconified_steam_icon_219680
steam_icon_221180 | iconified_steam_icon_221180
steam_icon_22120 | iconified_steam_icon_22120
steam_icon_22140 | iconified_steam_icon_22140
steam_icon_22180 | iconified_steam_icon_22180
steam_icon_221830 | iconified_steam_icon_221830
steam_icon_224260 | iconified_steam_icon_224260
steam_icon_225140 | iconified_steam_icon_225140
steam_icon_227200 | iconified_steam_icon_227200
steam_icon_227300 | iconified_steam_icon_227300
steam_icon_231160 | iconified_steam_icon_231160
steam_icon_231430 | iconified_steam_icon_231430
steam_icon_231670 | iconified_steam_icon_231670
steam_icon_232430 | iconified_steam_icon_232430
steam_icon_232790 | iconified_steam_icon_232790
steam_icon_233450 | iconified_steam_icon_233450
steam_icon_234650 | iconified_steam_icon_234650
steam_icon_236390 | iconified_steam_icon_236390
steam_icon_236850 | iconified_steam_icon_236850
steam_icon_238210 | iconified_steam_icon_238210
steam_icon_238320 | iconified_steam_icon_238320
steam_icon_238460 | iconified_steam_icon_238460
steam_icon_239030 | iconified_steam_icon_239030
steam_icon_239200 | iconified_steam_icon_239200
steam_icon_241930 | iconified_steam_icon_241930
steam_icon_249990 | iconified_steam_icon_249990
steam_icon_250900 | iconified_steam_icon_250900

### CODE REVIEW

**Comment by W-Floyd** [comment]
By my count, 522 left. The weekend lies ahead... I might try for those odd 22 tonight, they mock me.

**Review by palob — CHANGES_REQUESTED** [review]
The party's going on!

I found 2 things:
*robocode*: internal shadow isn't adjusted
*steam_icon_29680*: baseplate bezel isn't visible

**Comment by W-Floyd** [comment]
Ah, thanks! I'll get to them in a couple hours.

**Comment by W-Floyd** [comment]
Done.

Name | Icon
--- | ---
robocode | iconified_robocode
steam_icon_219680 | iconified_steam_icon_219680

**Review by palob — APPROVED** [review]

**Review by Foggalong — CHANGES_REQUESTED** [review]
I noticed this pull request has a Square icon for securefx. We such an icon in [Numix Folders](https://github.com/numixproject/numix-folders/tree/master/styles/6/Numix-Square/48/apps) but for some reason it didn't get copied over to here. If you come across icons using folders which are missing it might be worth checking there to see if the same thing happened. Similarly, if you modify any icons which have folders in them here they need a respective pull request there.

---

Scilab symbol & symbol shadow need moving down 1px in Square. In Circle it looks okay because the circular baseplate lessens the bottom heavy look (so don't change it there), but in Square its more obvious so needs adjusting.

screenshot_2017-07-21_16-43-40


---

Took me a little while to work out what was up with scinotes: the symbol is actually off centre because it was made with an odd width. In both Circle & Square simply widen the notebook by 1px to the left, move over the left hand yellow rings 2px to the left, and the grey text by 1px to the left. The logo stamp and pencil can stay where they were.

| Before | After |
| --- | --- |
| screenshot_2017-07-21_16-37-19 | screenshot_2017-07-21_16-37-34 |

The result is everything looking a lot nicer and centred.
screenshot_2017-07-21_16-41-40


----

The symbol & symbol shadow in slingscold could do with moving up 1px. Circle got away with it thus far because of the circular baseplate disguising the effect but on the Square its more evident it's too far down.
screenshot_2017-07-21_16-20-43

**Comment by W-Floyd** [comment]
Name | Icon
--- | ---
 | 
scilab | iconified_scilab
scinotes | iconified_scinotes
slingscold | iconified_slingscold

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
