### PR TITLE
Icons for corectl

### PR DESCRIPTION
**Pull request by palob**
https://gitlab.com/corectrl/corectrl

corectl
corectl-ci
corectl-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I get what you were going for, but I really dislike that brown background :confused:

**Comment by palob** [comment]
Maybe this?
corectl-ci

**Comment by Foggalong** [comment]
@palob That's much better :+1:

**Comment by palob** [comment]
Pushed.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
