### PR TITLE
Added Outline VPN icons

### LINKED ISSUE #5781: Icon request: Outline Client
**App name:**
`Outline`, [wiki](https://en.wikipedia.org/wiki/Outline_VPN), [website](https://getoutline.org/), [github](https://github.com/Jigsaw-Code/outline-client)

**Icon name:**
`outline-client`

**Desktop filename:**
`outline-client.desktop`

**Original icon:**

|  Manager | Client |
| ------------- | ------------- |
|   |  |

**Description:**
The Outline Client is a cross-platform VPN or proxy client for Windows, macOS, iOS, Android, and ChromeOS.

### PR DESCRIPTION
**Pull request by ingria**
Removed the gradient, reduced the "nut" size.

**Original icons**

|  Manager | Client |
| ------------- | ------------- |
|   |  |

**Preview:**

Fixes #5781

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Thank you. Alignment and sizes are fine.

Can you please make the baseplate a bit brighter so that the L(lightness) range spans from 18 to 22?

We also need icons for Numix Square. Same gradient but the icons sit 1px further up compared to Numix Circle and symbol shadow is just 1px below the symbol without horizontal displacement.

**Comment by ingria** [comment]
Any good?

|  |  |
| ------------- | ------------- |

**Comment by palob** [comment]
Yep, fine :+1:

**Comment by ingria** [comment]
|  |  |
| ------------- | ------------- |

|  |  |
| ------------- | ------------- |

**Review by palob — APPROVED** [review]
Thank you.

**Comment by palob** [comment]
I've already fixed this but as a hint for future contributions: symbol shadows should be pure black (L=0, Alpha=100) with opacity set to 10%.

Please save as *Optimised SVG* with options as described here:
https://github.com/numixproject/numix-core/wiki/Optimise-Options

**Pull request merged**
