### PR TITLE
Icons for Laigter

### PR DESCRIPTION
**Pull request by palob**
https://github.com/azagaya/laigter

io itch azagaya Laigter
io itch azagaya Laigter-ci
io itch azagaya Laigter-sq

### CODE REVIEW

**Comment by Foggalong** [comment]
I've gone back and forth on whether we should correct the design error in the flame having a flat bottom (which is why this wasn't approved with the last batch). Given that it's used throughout the app as a UI element like that I think probably leave it but aghhhhh.

**Review by Foggalong — APPROVED** [review]

**Comment by maxtron95** [comment]
@Foggalong @palob Should we update our icon to the new Laigter icon? It has been redesigned.

laigter256

**Comment by palob** [comment]
Well, it looks a bit better.

**Comment by Foggalong** [comment]
Agreed, that's a much nicer base icon!

**Pull request merged**
