### PR TITLE
Icon for the Signal Chrome App

### PR DESCRIPTION
**Pull request by kpuljek**
I'm submitting the icon for the Signal Chrome App, requested #2997

### CODE REVIEW

**Comment by Foggalong** [comment]
@kpuljek Can you also add the lines needed for the `data.json` file?

**Comment by Foggalong** [comment]
I switched it over to design two because that fit in with the Numix guidelines better. Thanks for the contribution :heart:

**Comment by kpuljek** [comment]
Hey! Sorry for the late response, but I've been away from my PC for a while. I didn't know that I had to add data.json lines as well. I'll make sure I do in any future contributions. Just received the update, feels good :D

**Comment by Foggalong** [comment]
No problem :+1:

**Pull request merged**
