### PR TITLE
Icons for Alias

### PR DESCRIPTION
**Pull request by palob**
https://github.com/bartzaalberg/alias

alias-ci
alias-sq

### CODE REVIEW

**Review by Foggalong — COMMENTED** [review]
Can we try a black label on the tag rather than cutout? Not a demand but I have a feeling it'll look better

**Comment by bilelmoussaoui** [comment]
Why this was closed?😐

**Comment by palob** [comment]
Deleted the branch inadvertently. Up again.

**Comment by palob** [comment]
alias-ci
alias-sq

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
