### PR TITLE
added icons for 4chan.org and pr0gramm.com

### LINKED ISSUE #3526: Icons for 4chan.org and pr0gramm.com
I would like to request icons for two image boards, [4chan.org](http://www.4chan.org/) and [pr0gramm.com](http://pr0gramm.com/). To access these boards I use Chrome(ium) **application shortcuts** which have own `.desktop` files.

## 4chan.org
`chrome-http___www.4chan.org_.desktop`
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=4chan
Exec=/usr/bin/chromium-browser --app=http://www.4chan.org/
Icon=/home/USER/.local/share/applications/icons/4chan_128.png
StartupWMClass=www.4chan.org
```

4chan_128

## pr0gramm.com
`chrome-http___pr0gramm.com_.desktop`
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=pr0gramm.com
Exec=/usr/bin/chromium-browser --app=http://pr0gramm.com/
Icon=/home/USER/.local/share/applications/icons/pr0gramm_128.png
StartupWMClass=pr0gramm.com
```

pr0gramm_128

SVG files: [icons.zip](https://github.com/numixproject/numix-core/files/658497/icons.zip)

### PR DESCRIPTION
**Pull request by 0b11001111**
A bit late but here's my request as discussed to fix #3526.

**4chan circle**
4chan org

**4chan square**
4chan_s org

**pr0gramm circle**
pr0gramm com

**pr0gramm square**
pr0gramm_s com

### CODE REVIEW

**Comment by palob** [comment]
Hi, thanks for the PR.

The heart objects inside the 4chan icon are composed of a path + a countour. Can you realise the symbol just using paths and use less nodes?
4chan


The pr0gram icons contains some elements which aren't aligned to the pixel grid (to be togled by the ``#`` key in Inkscape). This causes the icon to look blurry. 
pr0gram

Can you please align the underscore to the grid and recreate the ``>`` char as a combination of 2 rounded rectangles?

Something like this rotated 45°. You'll get a smoother object this way.

pr0gram2

**Comment by palob** [comment]
In ``data.json`` the ``root`` names should be exactly the icon file names minus ``.svg``.

**Review by Foggalong — CHANGES_REQUESTED** [review]
Needs aligning to grid and cleaning up before it can be merged

**Comment by W-Floyd** [comment]
Again, not sure what the protocol is, but I've updated this and PR'ed it over at https://github.com/luoc0815/numix-core/pull/1/

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
