### PR TITLE
Icons for Lara Croft and the Temple of Osiris

### PR DESCRIPTION
**Pull request by BlueManCZ**
| Original icon | Circle icon | Square icon |
| --- | --- | --- |
| ![orig][orig] | ![circ][circ] | ![sqr][sqr] |

https://steamdb.info/app/289690/screenshots/

[orig]: https://user-images.githubusercontent.com/17854950/88532473-f52c7700-d004-11ea-9a5f-6aa0b860bd2e.png "Original"
[circ]: https://user-images.githubusercontent.com/17854950/88532484-f8bffe00-d004-11ea-8035-efa685aea8e2.png "Circle"
[sqr]: https://user-images.githubusercontent.com/17854950/88532493-fbbaee80-d004-11ea-9698-949df7e1634c.png "Square"

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Could we please have all elements brighter?
As a rule of thumb we don't use colours darker than 20L (Inkscape 1.0+ L).

**Comment by palob** [comment]
Brighter colours for the rim+letters and rectangle as well, please :)

**Comment by palob** [comment]
Thanks, baseplate could be lighter still and the rectangle in the centre is still markedly dark.

**Comment by BlueManCZ** [comment]
a

**Review by palob — APPROVED** [review]
Yeah, that's it, thank you.

**Pull request merged**
