### PR TITLE
Icons for Pixel Vision 8

### PR DESCRIPTION
**Pull request by maxtron95**
https://www.pixelvision8.com/

pixelvision8

pv8-ci
pv8-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Square symbol should go 1px upwards.

**Comment by maxtron95** [comment]
But If I do that, the pixel logo will end up being blurry at 24px.

**Comment by palob** [comment]
Hmm, @Foggalong what do you think is to be prioritised?

**Comment by Foggalong** [comment]
Stick it 1px up for now - icons optimised for smaller sizes is something to return to at a later date

**Review by palob — APPROVED** [review]

**Pull request merged**
