### PR TITLE
Icons for Theia

### PR DESCRIPTION
**Pull request by palob**
https://github.com/eclipse-theia/theia

theia
theia-ci
theia-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
Looking at [the screenshots](https://projects.eclipse.org/projects/ecd.theia) can we maybe get a blue baseplate?

**Comment by palob** [comment]
In combination with a white symbol I take it?
That logo from the link makes me wonder whether Eclipse got/will get a new icon.

**Comment by Foggalong** [comment]
Yeah white symbol still works :+1: [Eclipse looks to be the current design](https://projects.eclipse.org/), at least for now

**Comment by palob** [comment]
Pushed
theia-ci
theia-sq

**Comment by Foggalong** [comment]
This is brilliant, thanks @palob!

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
