### PR TITLE
Add starcraft-2 symlink

### PR DESCRIPTION
**Pull request by mrmeszaros**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I have removed the symlink as empty space on an icon name causes an issue with gtk-update-icon-cache.

**Comment by mrmeszaros** [comment]
@bil-elmoussaoui sure. Do you know if this issue will be resolved any time in the future? Could you link to a bug report in their issue tracker (if you know of one)?

**Comment by palob** [comment]
Spaces in icon names aren't allowed as per the [freedesktop spec](https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html).

**Comment by bilelmoussaoui** [comment]
it's more an issue of wine than gdk-pixbuf

**Pull request closed without merging**
