### PR TITLE
Icons for Fiddler

### PR DESCRIPTION
**Pull request by really-need-an-api-key**
https://www.telerik.com/fiddler

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  fiddler |  circle | square |

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Everything fine here. Maybe a darker green for the symbol + a slight greenish hue for the baseplate is worth a try.

**Comment by really-need-an-api-key** [comment]
green1
green2
green3

Not sure how I feel about the first one, so made some variations. I think the green base ones aren't as immediately recognizable as just the green square version though. Green on white seems to be the company's theme, as seen in the splash screen here:
fiddler_-_telerik

**Comment by Foggalong** [comment]
The third one (white F, dark green diamond, mid green base) for sure :+1:

**Review by Foggalong — CHANGES_REQUESTED** [review]
The third one (white F, dark green diamond, mid green base) for sure :+1:

**Comment by really-need-an-api-key** [comment]
| Circle | Square |
| :--- | :--- |
| circle | square |

**Review by Foggalong — APPROVED** [review]

**Comment by Foggalong** [comment]
I approve of this, but will see what @palob thinks before merging since it was their suggestion :)

**Comment by palob** [comment]
Yeah, thats's as green as it gets :+1:

**Review by palob — APPROVED** [review]

**Pull request merged**
