### PR TITLE
distributor-logo-solaris-oracle/sun - Icons and entry for Oracle & Sun Solaris.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #2183

iconified_distributor-logo-solaris-sun

iconified_distributor-logo-solaris-oracle

I'm not really sure what else could be done for the Oracle version, there itsn't really any sort of symbol.

### CODE REVIEW

**Review by palob — COMMENTED** [review]
Maybe the background tinted with the colour of the *solaris* typeface and a reddish or blackish baseplate for the oracle one?

**Comment by W-Floyd** [comment]
How about like this? Having a blue tint on the sun one felt wrong. I like that contrast, works really well.

iconified_distributor-logo-solaris-oracle
iconified_distributor-logo-solaris-sun

**Comment by palob** [comment]
Oh yeah 🥇

**Review by Foggalong — CHANGES_REQUESTED** [review]
Make the tinting changes because they are :heart:

**Comment by W-Floyd** [comment]
Huh, guess I forgot to push my commit...

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
