### PR TITLE
Icons for Loginized

### PR DESCRIPTION
**Pull request by palob**
https://github.com/juhaku/loginized

loginized
loginized-ci
loginized-sq

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
This design feels too sparse as is. Would adding the roller and in-progress password to an existing login icon (but with the new green baseplate) work?

**Comment by palob** [comment]
Maybe this?
loginized2

**Review by Foggalong — COMMENTED** [review]
Idea is better, but it looks weird having colour in the brush but not the input box. Maybe add a white background to that?

**Comment by palob** [comment]
loginized2

**Comment by Foggalong** [comment]
No, I meant still green breastplate but a white background to the entry box :)

**Comment by palob** [comment]
loginized-ci

**Comment by palob** [comment]
Pushed.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
