### PR TITLE
100 square icons - Round 2

### PR DESCRIPTION
**Pull request by W-Floyd**
Here are 100 more icons ported to square. Included are some minor fixes to circle icons (cleanup, re-baking shadow, adding and aligning gradients.)

Name | Icon
--- | ---
~~steam_icon_261640~~ | iconified_steam_icon_261640
steam_icon_26500 | iconified_steam_icon_26500
steam_icon_265930 | iconified_steam_icon_265930
steam_icon_274170 | iconified_steam_icon_274170
steam_icon_275390 | iconified_steam_icon_275390
steam_icon_290930 | iconified_steam_icon_290930
steam_icon_292910 | iconified_steam_icon_292910
steam_icon_293780 | iconified_steam_icon_293780
steam_icon_295690 | iconified_steam_icon_295690
steam_icon_300550 | iconified_steam_icon_300550
steam_icon_301520 | iconified_steam_icon_301520
steam_icon_302610 | iconified_steam_icon_302610
steam_icon_313740 | iconified_steam_icon_313740
steam_icon_317360 | iconified_steam_icon_317360
steam_icon_322170 | iconified_steam_icon_322170
steam_icon_322330 | iconified_steam_icon_322330
steam_icon_332970 | iconified_steam_icon_332970
steam_icon_43110 | iconified_steam_icon_43110
steam_icon_43160 | iconified_steam_icon_43160
~~steam_icon_49520~~ | iconified_steam_icon_49520
steam_icon_50300 | iconified_steam_icon_50300
steam_icon_61600 | iconified_steam_icon_61600
steam_icon_65980 | iconified_steam_icon_65980
step | iconified_step
stm32workbench | iconified_stm32workbench
stuntrally | iconified_stuntrally
subsurface-icon | iconified_subsurface-icon
sunflower | iconified_sunflower
svgcleaner | iconified_svgcleaner
sv-icon | iconified_sv-icon
swatchbooker | iconified_swatchbooker
sweethome3d-furniture-editor | iconified_sweethome3d-furniture-editor
sweethome3d | iconified_sweethome3d
sweethome3d-textures-editor | iconified_sweethome3d-textures-editor
synthv1 | iconified_synthv1
systemback | iconified_systemback
tagspaces | iconified_tagspaces
tales-of-majeyal | iconified_tales-of-majeyal
tanglet | iconified_tanglet
taskcoach | iconified_taskcoach
tasque | iconified_tasque
taxi | iconified_taxi
tea | iconified_tea
terminatorx | iconified_terminatorx
tesseract | iconified_tesseract
~~testdrive~~ | iconified_testdrive
tetzle | iconified_tetzle
~~thg_logo~~ | iconified_thg_logo
tictactoe | iconified_tictactoe
timeline | iconified_timeline
tintii | iconified_tintii
titania | iconified_titania
tixati | iconified_tixati
tkabber | iconified_tkabber
torrent-file-editor | iconified_torrent-file-editor
translator | iconified_translator
treeline | iconified_treeline
trelby | iconified_trelby
tresorit | iconified_tresorit
trimage | iconified_trimage
trine | iconified_trine
trojita | iconified_trojita
tumiki-fighters | iconified_tumiki-fighters
tvbrowser | iconified_tvbrowser
ubuntu-kylin-software-center | iconified_ubuntu-kylin-software-center
ue4editor | iconified_ue4editor
ufraw | iconified_ufraw
ugene | iconified_ugene
umbrello | iconified_umbrello
unity-editor-icon | iconified_unity-editor-icon
unity-launcherswitcher | iconified_unity-launcherswitcher
unity-monodevelop | iconified_unity-monodevelop
universalindentgui | iconified_universalindentgui
~~unknown-horizons~~ | iconified_unknown-horizons
unsettings | iconified_unsettings
urbanlightscape | iconified_urbanlightscape
urserver | iconified_urserver
utox | iconified_utox
v4l2ucp | iconified_v4l2ucp
vacuum | iconified_vacuum
valama | iconified_valama
valentina | iconified_valentina
valyriatear | iconified_valyriatear
variety-slideshow | iconified_variety-slideshow
~~vcmiclient~~ | iconified_vcmiclient
view3dscene | iconified_view3dscene
viking | iconified_viking
violetumleditor | iconified_violetumleditor
~~virtual-engineering~~ | iconified_virtual-engineering
virtualplanet | iconified_virtualplanet
virt-viewer | iconified_virt-viewer
visualparadigm | iconified_visualparadigm
~~vlmc~~ | iconified_vlmc
vmpk | iconified_vmpk
vncaddrbook | iconified_vncaddrbook
vnclicensewiz | iconified_vnclicensewiz
vncserver | iconified_vncserver
vncviewer | iconified_vncviewer
vollyball | iconified_vollyball
voxelands | iconified_voxelands

### CODE REVIEW

**Comment by W-Floyd** [comment]
Only 600 and a bit to go... lol

**Comment by bilelmoussaoui** [comment]
Thanks for the great work :100:

**Comment by W-Floyd** [comment]
@bil-elmoussaoui Someone's got to do it :stuck_out_tongue_closed_eyes:

**Review by palob — CHANGES_REQUESTED** [review]
Splendidly done again. Some nitpicking:
*steam_icon_26140*: the symbol stuff should be below the baseplate bezel shadow.

*testdrive*: the internal shadow needs to be adjusted.

**Comment by W-Floyd** [comment]
Good catch! Didn't see those.

Name | Icon
--- | ---
~~steam_icon_261640~~ | iconified_steam_icon_261640
testdrive | iconified_testdrive

**Comment by palob** [comment]
Even more nitpickier nitpicking :)
Can you please remove the nodes at the bottom of the oval?

oval

**Comment by W-Floyd** [comment]
lol Not nitpicky :)
While we're at it, what would be the best PR size for this sort of thing? 25? 50? 100?

**Review by palob — APPROVED** [review]
Yippie!

**Comment by palob** [comment]
@Foggalong What's you preferred PR size?

@W-Floyd You probably don't need to do a seperate commit for each Square conversion if that saves you any hassle.

**Comment by W-Floyd** [comment]
As far as time goes, the actual PR bit takes me a couple minutes, it's not an issue. Got a script to make my image table for me, and I generate all my images as I go. Bottom line is, if you give me a number, I'll stick to it :P

I'll probably try for another batch later today, got to go for now though. Thanks for the help :)

Edit: Got the next batch in ;)

**Comment by Foggalong** [comment]
@W-Floyd @palob For normal contributions I'd prefer 1 icon per pull request, with more only if the apps the icons are for are related. No more than 5 beyond that 

When it comes to tackling massive issues like this though I recognise that isn't really sensible since it'd mean 100s of pull requests to get it done. I'd say aim for between 25-50 since it makes it more manageable to review and means less chance of something slipping through the net.

**Comment by W-Floyd** [comment]
@Foggalong I might go for 50 then. Another PR incoming...

**Review by Foggalong — CHANGES_REQUESTED** [review]
There's some weird bowing going on in the square versions of the two Borderlands icons which isn't as prominent in the circle versions. The widest part of the left prong doesn't actually seem to be at the bottom but a little way up.

| Circle | Square |
| --- | --- |
| 
screenshot_2017-07-21_14-37-05 | screenshot_2017-07-21_14-36-26 |
| screenshot_2017-07-21_14-31-53 | screenshot_2017-07-21_14-33-30 |

My hunch is that this has happened because in Circle only the top two nodes have handles, where as in Square both top and bottom have handles. This difference is there on both the left and right prongs of the arch but is just more visible on the left one.

screenshot_2017-07-21_14-45-19
 
Above are screenshots at 48px of the icons. *-0c are the circle ones for comparison, and then *-2h are ones with the bottom handles removed and *-4h with them still there (as in this pr). The difference is smaller, but enough that it'll be noticeable when shown at larger sizes in DEs like GNOME.

The effect can be remedied further by adjusting the arc end points. You might get the top handles doing some funky things when the bottom ones are removed so watch out for that too.

---

`thg_logo.svg` (the one with the turtle) seems to look more centred if the symbol and shadow are moved 1px right and 1px right.

screenshot_2017-07-21_15-01-52

*-cs is the icon as is, *-cx is the just moved right 1px, and *-cxy is moved both right and down 1px. 

----

The gradient for both Circle & Square of `unknown-horizons` isn't actually with the Numix guidelines. Currently the bottom stop is `#2483cc` and the top stop is `#50a7e9` whereas they should be `#3f99de` and `#4fa1e1` respectively so that the only change is the lightness difference (in HSL) is only 10.

----

The symbol & symbol shadow in `virtual-engineering` is too high for the square version. The circle version has gotten away with it being as high as it is while still looking centred thus far because it's roughly semicircle on a circular background. On square that works to its disadvantage and is compounded because the dark baseplate hides the bottom bezel. 
screenshot_2017-07-21_15-29-12

My suggestion would be to move the symbol and shadow down in Circle by 1px and in Square by 2px. Keep the baseplate gradient the same, I only added the light version above for comparison. Thoughts @palob?

---

In `vlmc` the symbol and shadow looks like it could do with moving up by 2px in Square and 1px in Circle. What do you think @palob?
screenshot_2017-07-21_15-37-43
The symbol shadow also seem to be above parts of the clapperboard in both versions which needs fixing.

----

In `vcmiclient` again the baseplate shape works the the symbols advantage in Circle but not in Square. 

screenshot_2017-07-21_15-42-46

The current positioning in Circle looks reasonably centred and it actually begins to look off centred if it's moved up by 1px. In Square however it needs moving up an extra 1px to offset the symbol being top heavy. I thought it might need an extra 2px but looking at it now I think that might be just too far.

**Comment by W-Floyd** [comment]
@Foggalong Thanks for the review! I'll get to these shortly (the ones that are clear on what needs changing).
I wrestled with the borderlands icons longer than I should have, your solution seems like a good way to go.

**Comment by Foggalong** [comment]
@W-Floyd Yeah extending a shape to fill the larger square baseplate is tricky and I remember it being the biggest timesink back when Square was first created

**Comment by W-Floyd** [comment]
To be honest, they're more fun, even if they do take longer XD
As for all this work, I'm learning a lot about what makes a good icon, so that's something.

**Comment by W-Floyd** [comment]
I'll (tentatively) do the other 2 now...

Name | Icon
--- | ---
steam_icon_261640 | iconified_steam_icon_261640
steam_icon_49520 | iconified_steam_icon_49520
thg_logo | iconified_thg_logo
unknown-horizons | iconified_unknown-horizons
vcmiclient | iconified_vcmiclient

**Comment by W-Floyd** [comment]
Name | Icon
--- | ---
 | 
virtual-engineering | iconified_virtual-engineering
vlmc | iconified_vlmc

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
