### PR TITLE
LibreOffice Writer circle icon consistent with oficial branding

### PR DESCRIPTION
**Pull request by leojimenezcr**
LibreOffice Writer circle icon consistent with [look and feel of oficial branding](https://wiki.documentfoundation.org/Visual_Elements). So people will recognize it more easily.

The icon is based on libreoffice-main.svg file and mixed with [oficial graphical elements and color pallete](https://wiki.documentfoundation.org/File:LibreOffice_Initial_Icons-pre_final.svg).

proposal-libreoffice-writer

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Please take a look at our design gudelines and existing icons.

**Comment by leojimenezcr** [comment]
Hi. I think, according to design guidelines, I need to check the size of the symbol and add a shadow to it. I'm right? Any other observation?

**Comment by palob** [comment]
It is crucial that all elements be aligned with the pixel grid, otherwise the icon looks blurry.
Usually we don't use gradients in symbol elements.
Some of your icons are too fine grained to be recognisable at smaller sizes, the Math one in particular.

Some of your icons use a stroked style which is distinctly un-Numixy.

I think for all icons you took the symbol right away from the original one. This defeats the purpose of a custom icon theme (and in other cases might not be compliant with our licence).

I don't think the way the dog-ear thing overlaps the symbol works out at all. Please find a better way of incorporating it.

**Comment by leojimenezcr** [comment]
Thanks for take time to response. I will work in new propose.

**Comment by palob** [comment]
Thanks, the amont of criticism might sound heavy, so I'm glad you're still enthusiastic.

**Comment by W-Floyd** [comment]
Maybe not have gradients except the baseplate?

**Review by Foggalong — CHANGES_REQUESTED** [review]
Extra extra note as well: these design changes will also have to be carried across to the Square theme.

**Pull request closed without merging**
