### PR TITLE
Square versions of several icons

### PR DESCRIPTION
**Pull request by really-need-an-api-key**
That took way longer than I wanted it to, sorry.
I think it's for #3481.

screenshot from 2016-11-29 23-59-16

### CODE REVIEW

**Comment by palob** [comment]
Some symbols look a bit far down on the baseplate. Did you shift all up 1px compared to the Circle icon?

**Comment by really-need-an-api-key** [comment]
Whoops. Will do when I get home.

**Comment by really-need-an-api-key** [comment]
I must have the longest ways home...
Anyway, shifted them all up, but I'm not sure if Sunvox doesn't look too high when adjusted? What do you think? 
screenshot from 2016-12-05 22-59-35

And here's the rest of them:
screenshot from 2016-12-05 23-03-35

Actually, I think Vivaldi might still be a little too low. On the right, shifted 2px up.
screenshot from 2016-12-05 23-05-43

**Comment by Foggalong** [comment]
@really-need-an-api-key High one looks fine to me :+1:

**Comment by really-need-an-api-key** [comment]
screenshot from 2016-12-09 14-24-07

**Comment by palob** [comment]
On the ``steam..`` icon the upper shadow edge is strange. Is that on the Circle icon as well?
steam

Else all fine :+1:

**Comment by really-need-an-api-key** [comment]
Oh, seems I had forgotten to copy one path over from circle. Sorry about that.
screenshot from 2017-01-30 12-09-18
Should be fixed now.
screenshot from 2017-01-30 12-16-26

**Review by palob — APPROVED** [review]
Can be merged now :+1:

**Pull request merged**
