### PR TITLE
Icons for Setzer

### PR DESCRIPTION
**Pull request by palob**
https://github.com/cvfosammmm/Setzer

upstream icon redesign discussion
https://gitlab.gnome.org/cvfosammmm/setzer/issues/2

setzer
setzer-ci
setzer-sq

Alternatives
setzer0
setzer0c
setzer1
setzer4
setzer5
setzer7

### CODE REVIEW

**Review by Foggalong — CHANGES_REQUESTED** [review]
I'm not sold on any of these unfortunately, they're far enough away from both the original icon and the use of the app that I'm not sure it'd be recognised.

**Comment by palob** [comment]
*Setzer* however I think is supposed to mean typesetter.
Seeing the upstream discussion the bird might only be a temporary feature of the icon.

**Comment by palob** [comment]
Maybe a typewriter?

**Comment by palob** [comment]
Pushed this. Better or too detailed?

setzer2-sq

setzer2-ci

Maybe without the lines on the sheet?

setzer222

**Comment by palob** [comment]
Another variant
setzer3-ci
setzer3-sq

**Comment by Foggalong** [comment]
The typewriter is brilliant! Pushed that one :heart:

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
