### PR TITLE
gitkraken - Icons and entry for Gitkraken.

### PR DESCRIPTION
**Pull request by W-Floyd**
For #2880

iconified_gitkraken

### CODE REVIEW

**Comment by W-Floyd** [comment]
Cool, so that put me over the 8hr mark for numix work today :stuck_out_tongue_closed_eyes:... I really am bored...

**Review by palob — APPROVED** [review]

**Review by mrmeszaros — CHANGES_REQUESTED** [review]
Could you please remove `;paint-order:stroke fill markers`?

**Comment by W-Floyd** [comment]
Hmm yeah, Inkscape seems to be fighting me...

**Comment by mrmeszaros** [comment]
Could you lower the line between the tentacles a bit - it looks weird in comparison to the original one.
(I would provide a screen shot, but Inkscape is not rendering the symbol for me)

**Comment by mrmeszaros** [comment]
You could try [Vectr](https://vectr.com/) packaged as a `snap`.

**Comment by W-Floyd** [comment]
Ah, only optimization, usability is fine :)

iconified_gitkraken

**Comment by mrmeszaros** [comment]
Also - the background could be rewritten as a `<circle cx="24" cy="24" r="23"/>` - as done in the template PR #4028

**Comment by W-Floyd** [comment]
Yeah, that's been bothering me :/

**Review by Foggalong — APPROVED** [review]

**Comment by walker-dev** [comment]
nice 👍

**Pull request merged**
