### PR TITLE
first part of cleaner icon names

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Instead of doing all the cleaning at once; here's the first part

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
This one is ready to be merged. The tools used can be found here https://github.com/bil-elmoussaoui/numix-tools (I had to rewrite the order db script for like 10 times so I decided to put those various scripts here)

**Comment by Foggalong** [comment]
I was gonna message you privately about it, but I may as well do it here now. You might want to wait off the cleaner name changes until #4054 has been sorted :smiley:

**Review by Foggalong — CHANGES_REQUESTED** [review]
I was gonna message you privately about it, but I may as well do it here now. I'm gonna hold off merging in the cleaner name changes until #4054 has been sorted just so that no inconsistencies slip through :smiley:

**Comment by bilelmoussaoui** [comment]
@Foggalong Your PR doesn't have any steam/chrome app icons except this one https://github.com/numixproject/numix-core/blob/65065f2a3759e9cc8950b6ff629998a4236a6bed/icons/shine/48/steam_icon_22000.svg which can be renamed easily to `world-of-goo`
Other than this, i don't think there will be any merge conflicts between the two PR's

Edit: Opss, i didn't see the full icons list :p 
Let's keep this one open until the other PR is merged

**Comment by Foggalong** [comment]
@bil-elmoussaoui Aye, not gonna close this one. Shine & uTouch are out of date enough that it should be fairly minimal what changes need to be made

**Comment by bilelmoussaoui** [comment]
Don't worry about the modifications, I haven't done anything manually, it's using a script that's easily modifiable to add Shine and uTouch themes support :+1:

**Comment by bilelmoussaoui** [comment]
@Foggalong Can I work on this now? :)

**Comment by mrmeszaros** [comment]
@bil-elmoussaoui ` wargame-european-escalation.svg` is misspelled - there is an extra space at the start.

**Comment by bilelmoussaoui** [comment]
I opened a PR once again as I don't want to deal with conflicts files especially with that huge db file :p 
https://github.com/numixproject/numix-core/pull/4124

**Pull request closed without merging**
