### PR TITLE
Icons for Analogue: A Hate Story

### PR DESCRIPTION
**Pull request by maxtron95**
https://store.steampowered.com/app/209370/

analogue

analouge-a-hate-story-ci svg
analouge-a-hate-story-sq svg

I based the icon off of the game's steam header.
header

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
+ The baseplate is to bright and leaves no room for a gradient. The brightest we normally use is a L228-L238 gradient.

Not sure if the eyebrows are needed.
How about an on-symbol shadow for the hair (and eyes), @creepertron95 & @Foggalong

**Comment by maxtron95** [comment]
Maybe a shadow for the hair, but I think it would look weird for the eyes

**Comment by palob** [comment]
If we go for a hair shadow the eyes should possibly moved below the hair.

**Comment by maxtron95** [comment]
@palob I will wait and see what @Foggalong thinks about the symbol on symbol shadows.

**Comment by palob** [comment]
@creepertron95 You misnamed the icon files, ``analouge`` instead of ``analogue``.

**Review by palob — APPROVED** [review]

**Comment by palob** [comment]
``color-rendering:auto;color:#000000;dominant-baseline:auto;fill:#2d2d2d;font-feature-settings:normal;font-variant-alternates:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-variant-numeric:normal;font-variant-position:normal;image-rendering:auto;isolation:auto;mix-blend-mode:normal;shape-padding:0;shape-rendering:auto;solid-color:#000000;text-decoration-color:#000000;text-decoration-line:none;text-decoration-style:solid;text-indent:0;text-orientation:mixed;text-transform:none;white-space:normal``
should be replaced by ``fill:#2d2d2d`` here.

**Review by palob — APPROVED** [review]
Thank you.

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
