### PR TITLE
Icons for Renoise

### LINKED ISSUE #2834: Icon Request for ReNoise
- ReNoise (https://www.renoise.com/)
  renoise

Icon = renoise.png

### PR DESCRIPTION
**Pull request by really-need-an-api-key**
Fixes #2834.

| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
| renoise3 | circle | square |

On my distro the icon is called just `renoise3`, but added a symlinked `renoise` too.

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
The baseplate is really dark. It probably shouldn't be darker than L50 at the bottom so you can actually see the symbol shadow.

**Comment by really-need-an-api-key** [comment]
Yeah looking at it now on a white background it looks pretty dark. I wanted a dark background because the application has a dark theme by default, but I guess I went overboard.

This is 50 at the bottom: 
square

This is 70, but the symbol shape is starting to get lost:
square70

And 70 with a lighter symbol, which i think looks good too:
square70_2

Which one do you think looks best?

**Comment by palob** [comment]
The last one :+1:

**Comment by really-need-an-api-key** [comment]
| Circle icon | Square icon |
| :-- | :-- |
| circle | square |

**Review by palob — CHANGES_REQUESTED** [review]
blunenode
The blue node should be moved 0.5px or 1px to the left, it looks better somehow.

**Comment by really-need-an-api-key** [comment]
Moved it 1px to the left.

| Circle | Square |
| :--- | :--- |
| circle | square |

**Review by palob — APPROVED** [review]

**Review by Foggalong — APPROVED** [review]

**Pull request merged**
