### PR TITLE
HTTrack square icon

### PR DESCRIPTION
**Pull request by mymindstorm**
| Original icon | Circle icon | Square icon |
| --- | :-- | :-- |
|  original |  circle | square |

This is mostly just a cut and paste from the circle icon to the square template. Should help with #3481

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Thanks and welcome. The shadow is slightly misplaced. It should be just 1px further down relative to the symbol for Square icons.

**Comment by mymindstorm** [comment]
By 1px further down relative to the symbol, do you mean 1px below where it already is or 1px below the symbol?

**Comment by palob** [comment]
The latter, below the symbol. X coordinate should be the same as the symbol's one.
Please take a look at existing Square icons.

**Comment by mymindstorm** [comment]
That commit should fix it @palob

**Review by palob — APPROVED** [review]
Thanks.

**Pull request merged**
