### PR TITLE
Icons for Cisco Packet Tracer

### LINKED ISSUE #2693: Icon for Cisco Packet Tracer
Packet Tracer is a Cisco software for network simulations. It's used in Cisco formations and in schools teaching Networking & IT.

The icon is hardcoded, a pull request to hardcode-fixer has already been sent and can be found [here](https://github.com/Foggalong/hardcode-fixer/pull/205).
The proposed icon name is **packettracer**.

**Original Icon:**
screenshot from 2015-11-20 02-10-53
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28429206-icon-for-cisco-packet-tracer?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by maxtron95**
Fixes #2693

cisco-packet-tracer-ci svg
cisco-packet-tracer-sq

### CODE REVIEW

**Review by palob — CHANGES_REQUESTED** [review]
Love this design. One small thing, instead of this

shadows should look like this

**Comment by maxtron95** [comment]
@palob How would I go about fixing the shadows on the symbols?

**Comment by palob** [comment]
Duplicate the magnifier shadow. Merge one of the 2 with the existing symbol shadow.
Duplicate the 2 envelope paths and merge. Intersect this merged path and the remaining magnifier path.

**Review by palob — CHANGES_REQUESTED** [review]
Arrangement is correct now but the new shadow is too dark. Just like the other channels it should be black (L0) with 10% opacity with the alpha channel untouched.

**Comment by palob** [comment]
You don't need Inkscape for this, just search for ``fill:#aaa`` and replace by ``opacity:.1``.

**Review by palob — APPROVED** [review]

**Pull request merged**
